### PR TITLE
Added html summary output

### LINKED ISSUE #689: New feature: HTML Summary Output
`-H, --html-report <FILE>`オプションの追加で、より詳細なResults SummaryをHTMLに出力する。

以下の情報をHTMLに保存する：

1. "General Overview" セクション (最初に出る情報と一番最後に出るElapsed Time)
例:
```
Analyzed event files: 581
Total file size: 148.5 MB

Excluded rules: 12
Noisy rules: 5 (Disabled)

Experimental rules: 1935 (65.97%)
Stable rules: 215 (7.33%)
Test rules: 783 (26.70%)

Hayabusa rules: 138
Sigma rules: 2795
Total enabled detection rules: 2933

Elapsed Time: 00:00:29.035
```

2. "Results Summary" セクション （※各セクションをテーブルにする？）
例:
```
Saved alerts and events:  449
Total events analyzed: 76,967 
Data reduction: 76,518 events (99.42%)

Total detections: 789 
Total critical detections: 0 (0.00%) 
Total high detections: 0 (0.00%) 
Total medium detections: 0 (0.00%)
Total low detections: 0 (0.00%)
Total informational detections: 789 (100.00%)

Unique detections: 1
Unique critical detections: 0 (0.00%)
Unique high detections: 0 (0.00%)
Unique medium detections: 0 (0.00%)
Unique low detections: 0 (0.00%)
Unique informational detections: 1 (100.00%)

Dates with most total detections:
critical: n/a
high: 2019-02-22 (222)
medium: n/a
low: n/a
informational: 2021-10-25 (338)

Computers with most unique critical detections: (※標準出力ではTOP 5だけにしているが、HTMLレポートでは全部出力する）
MSEDGEWIN10 (6) (※できれば、コンピュータ名をリンクにして、クリックしたら、アラート一覧のページを表示したいが、沢山の別のHTMLファイルを作成しないといけない場合は工夫が必要。）
IEWIN7 (3)
FS03.offsec.lan (2)
rootdc1.offsec.lan (2)
srvdefender01.offsec.lan (2)

Computers with most unique high detections:
MSEDGEWIN10 (6) 
IEWIN7 (3)
FS03.offsec.lan (2)
rootdc1.offsec.lan (2)
srvdefender01.offsec.lan (2)
Computer-6 (10)
Computer-7 (5)
等々

Computers with most unique medium detections:
MSEDGEWIN10 (6) 
IEWIN7 (3)
FS03.offsec.lan (2)
rootdc1.offsec.lan (2)
srvdefender01.offsec.lan (2)

Computers with most unique low detections:
MSEDGEWIN10 (6) 
IEWIN7 (3)
FS03.offsec.lan (2)
rootdc1.offsec.lan (2)
srvdefender01.offsec.lan (2)

Computers with most unique informational detections:
MSEDGEWIN10 (6) 
IEWIN7 (3)
FS03.offsec.lan (2)
rootdc1.offsec.lan (2)
srvdefender01.offsec.lan (2)

Critical alerts: (※これもTOP 5に限らないで、全部出す）
Sticky Key Like Backdoor Usage (10)
CobaltStrike Service Installations (6)      
Meterpreter or Cobalt Strike Getsystem Service Installation (6)
Active Directory Replication from Non Machine Account (6) 
WannaCry Ransomware (4)

High alerts:
xxx (nn)
xxx (nn)

Medium alerts:
xxx (nn)
xxx (nn)

Low alerts:
xxx (nn)
xxx (nn)

Informational alerts:
xxx (nn)
xxx (nn)

```
※可能であれば、Critical alerts等々のアラート名をsigma/hayabusa YMLルールへのリンク(ファイルの絶対パス）にしたいです。アラートをトリアージする時にYMLファイルをいちいちCodeで検索して、確認しないといけないので、楽にリンクをクリックし、YMLの内容が確認できたら、かなり楽になります。

### PR DESCRIPTION
**Pull request by hitenkoku**
Closes #689

## What Changed

- Added html summary output (-H option)

## Evidence

results: 
[689.html.txt](https://github.com/Yamato-Security/hayabusa/files/9640193/689.html.txt)

<details>
<summary>
  command: ./hayabusa.exe -d ..\hayabusa-sample-evtx\ -H 689.html -o 689.csv -q</summary>

> >./hayabusa.exe -d ..\hayabusa-sample-evtx\ -H 689.html -o 689.csv -q
> Analyzing event files: 581
> Total file size: 148.5 MB
> 
> Loading detections rules. Please wait.
> 
> Excluded rules: 12
> Noisy rules: 5 (Disabled)
> 
> Experimental rules: 2020 (67.07%)
> Stable rules: 213 (7.07%)
> Test rules: 779 (25.86%)
> 
> Hayabusa rules: 138
> Sigma rules: 2874
> Total enabled detection rules: 3012
> 
> 581 / 581 [============================================================================================================================] 100.00 %
> 
> Analysis finished. Please wait while the results are being saved.
> 
> Saved file: 689.csv (16.1 MB)
> 
> Results Summary:
> 
> Events with hits / Total events: 19,545 / 76,967 (Data reduction: 57,422 events (74.61%))
> 
> Total | Unique detections: 32,702 | 561
> Total | Unique critical detections: 46 (0.14%) | 18 (3.21%)
> Total | Unique high detections: 6,152 (18.81%) | 253 (45.10%)
> Total | Unique medium detections: 1,479 (4.52%) | 160 (28.52%)
> Total | Unique low detections: 6,771 (20.71%) | 76 (13.55%)
> Total | Unique informational detections: 18,254 (55.82%) | 54 (9.63%)
> 
> Dates with most total detections:
> critical: 2019-07-19 (15), high: 2016-09-20 (3,656), medium: 2019-05-19 (165), low: 2016-09-20 (3,780), informational: 2016-08-19 (2,105)
> 
> Top 5 computers with most unique detections:
> critical: MSEDGEWIN10 (6), IEWIN7 (3), rootdc1.offsec.lan (2), srvdefender01.offsec.lan (2), FS03.offsec.lan (2)
> high: MSEDGEWIN10 (110), IEWIN7 (71), FS03.offsec.lan (31), fs03vuln.offsec.lan (28), IE10Win7 (23)
> medium: MSEDGEWIN10 (62), IEWIN7 (38), FS03.offsec.lan (17), IE10Win7 (15), fs03vuln.offsec.lan (14)
> low: MSEDGEWIN10 (35), IEWIN7 (18), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), IE10Win7 (11)
> informational: MSEDGEWIN10 (18), IEWIN7 (17), fs01.offsec.lan (16), PC01.example.corp (13), IE8Win7 (12)
> 
> ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │ Top critical alerts:                                              Top high alerts:                                    │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ Sticky Key Like Backdoor Usage (10)                               Metasploit SMB Authentication (3,562)               │
> │ Active Directory Replication from Non Machine Account (6)         Malicious Svc Possibly Installed (271)              │
> │ Meterpreter or Cobalt Strike Getsystem Service Installation (6)   Susp Svc Installed (257)                            │
> │ Windows Defender Alert (4)                                        PowerShell Scripts Installed as Services (253)      │
> │ WannaCry Ransomware (4)                                           Suspicious Service Installation Script (250)        │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ Top medium alerts:                                                Top low alerts:                                     │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ Potentially Malicious PwSh (235)                                  Logon Failure_Wrong Password (3,564)                │
> │ Proc Injection (104)                                              Susp CmdLine (Possible LOLBIN) (1,418)              │
> │ Reg Key Value Set_Sysmon Alert (103)                              Non Interactive PowerShell (325)                    │
> │ Suspicious Remote Thread Target (93)                              Rare Service Installations (321)                    │
> │ Cscript Visual Basic Script Execution (60)                        Windows Processes Suspicious Parent Directory (282) │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ Top informational alerts:                                                                                             │
> ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
> │ Proc Exec (11,173)                                                Explicit Logon (342)                                │
> │ NetShare File Access (2,564)                                      Svc Installed (331)                                 │
> │ PwSh Scriptblock (789)                                            New Non-USB PnP Device (268)                        │
> │ PwSh Pipeline Exec (680)                                          Logon (Type 3 Network) (228)                        │
> │ NetShare Access (433)                                             File Created (210)                                  │
> ╰─────────────────────────────────────────────────────────────────╌─────────────────────────────────────────────────────╯
> 
> Elapsed Time: 00:00:12.671
> 
> HTML Report was generated. Please check 689.html for details.

</details>

### CODE REVIEW

**Comment by hitenkoku** [comment]
@YamatoSecurity  ひとまずご指定いただいた箇所のすべての情報を出す形で対応をさせていただきました。少しテストコード側の修正を並行して行いますが、動作自体はこちらで出来ますのでご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
最低限の入出力についてのテストは行っておきました。ファイル出力のテストについては実行の検証時に行えていますので、検証と並行してテストコードを書くようにして、間に合えばこちらのpull-requestに追加したいと思います

**Comment by YamatoSecurity** [comment]
ありがとうございます！内容は良い感じです。あとは @nishikawaakira さんがCSSを入れて、少し格好良くしますよね？

少しだけ修正したいところがあります:
1. General Overviewの最初に開始時間を入れられますか？
例: `Start time: 2022/09/25 14:23`
2. `Computers with most unique critical detections:`の見出しはあるが、high~infoの見出しが抜けているようです。
3. アラートタイトルを`.yml`ルールへのリンクにできますか？

**Comment by hitenkoku** [comment]
ご確認ありがとうございます。

1. については対応可能です。いらないとは思いますが標準出力にも出しますか？
2. については、確認させていただきます。
3.についてはアラートタイトルを.ymlのリンクにするのは可能だとは思いますが少々確認します

**Comment by YamatoSecurity** [comment]
> 1. については対応可能です。いらないとは思いますが標準出力にも出しますか？

そうですね。あまり要らないはずですが、一応標準出力にも出力しましょう。

**Comment by YamatoSecurity** [comment]
ありがとうございます！開始時間と見出しは直りました。
ルールタイトルはYMLファイルパスだと分かりにくいので、ルールタイトルのままでYML相対パスへのhyperlinkにしたいのですが、可能ですか？
(難しいのであれば、ルールタイトルに戻したいです。）

**Comment by YamatoSecurity** [comment]
Screen Shot 2022-09-27 at 6 47 16
あと、General Overviewの項目の間にスペースが入っているようですが、Results Summaryのように出力できますか？

**Comment by YamatoSecurity** [comment]
あと、critical~lowの見出しとその項目のテキスト色をHayabusaが出している色（かそれに似ている色）で出せたら出したいですが、可能ですか？
`<p style="color:red;">hogehoge</p>`

**Comment by nishikawaakira** [comment]
@hitenkoku 
<h3>Computers with most unique critical detections:</h3>
↓
<h3 id="computers_with_most_unique">Computers with most unique critical detections:</h3>
みたいにidつけることってmarkdownの実装でも可能でしょうか？
これつけられれば、外部のcss適当にからのファイル読み込んでおいていただければ、そこ実装しようと思っていますができるんでしたっけ？（説明聞いてたはずなのにド忘れしててすみません。。）

**Comment by hitenkoku** [comment]
一旦確認します。cssの指定はhtmlでおこなって、cssはレポジトリにそのまま置いといて読み込ませるようにするイメージです

**Comment by hitenkoku** [comment]
styleのcss適用については、確認したところhtml書き込みの際に他crateを使う形であれば対応可能であることがわかったので対応します。(pulldown-cmarkだとcssへの対応はまだ出来ていないので、html出力の際にheaderを別crateを使って付与することで対応しようと思います。

ID付与については現在のpulldown-cmarkでできそうなのでそのまま行います。
一旦h2, h3などの見出しに対して行うようにします

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。ご確認のほどよろしくお願いいたします。
@nishikawaakira  ご指摘の個所の対処は完了しました。hayabusa_report.cssに記載すれば同一階層のhtmlのレポートはcssが適用されることを確認済みです。

**Comment by hitenkoku** [comment]
このpull-requestもコミットが大きくなったので、一旦今の段階でマージをさせてもらって、cssの作成は別issueとして作る形の方がよさそうですがどうしましょうか。

**Comment by nishikawaakira** [comment]
ありがとうございます！たしかに分けた方が良さそうなので現状の動作を一旦確認していただけますか？ > @YamatoSecurity 
見栄えは別でissuedえ対応しようと思います！

**Comment by hitenkoku** [comment]
@nishikawaakira  #712 で新たにissueを作っておきました。

**Comment by nishikawaakira** [comment]
@hitenkoku ありがとうございます！着手はこれがマージされたらという認識であってますか？

**Comment by hitenkoku** [comment]
はい、その認識であっています

**Comment by YamatoSecurity** [comment]
Screen Shot 2022-09-27 at 19 47 41

Results summaryで`Top critical alerts: {#top_critical_alerts}`等になっています。合計が出力されなくなったので、それだけ修正してからマージしましょう。
HTMLレポートは良い感じになりました。

**Comment by hitenkoku** [comment]
@YamatoSecurity 失礼いたしました。対象の個所の出力を修正しました。ご確認のほどよろしくお願いいたします。
「合計が出力させなくなった」と書いておりますが、よくわかっていません。どこの部分を指しているのかお教えいただけますでしょうか。

- 元の出力(現在のmain)
image

- 今回ご指摘の個所を修正したスクリーンショット
image

**Comment by hitenkoku** [comment]
https://github.com/Yamato-Security/hayabusa/issues/712#issuecomment-1259342077 について https://github.com/Yamato-Security/hayabusa/pull/709/commits/d1851c6a423da56a9595b5ede41ee7824a1793b6 で対応しておきました。htmlファイルの同一階層の./favicon.pngを参照するようにしました

**Comment by YamatoSecurity** [comment]
ありがとうございます！直りました！
最後にすみません。
HTMLファイルが既に存在している場合は、エラーになって良いのですが、スキャンが終わってから「作成できない」エラーが出るので、とても時間がかかるスキャンの場合は、最後にHTMLレポートが作成されなくて「おいおい！もっと早く言ってや〜！」wwとなるかもしれないので、HTMLファイルが既に存在している場合は、`-o`のようにエラーメッセージを出して、すぐスキャンを止めたいのですが、大丈夫ですか？
Screen Shot 2022-09-27 at 21 28 19

**Comment by hitenkoku** [comment]
承りました。タイミングはoutputオプションと同じところでチェックするように修正してみます。

**Comment by hitenkoku** [comment]
@YamatoSecurity  ご指摘いただきましたファイルの存在チェックをスキャン前に行うように修正しました。ご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
outputの存在チェックは複数個所で行ってしまっているので、別issueでリファクタリングを行おうと思います。

**Review by YamatoSecurity — APPROVED** [review]
対応ありがとうございました！
これで良いと思います。

**Comment by hitenkoku** [comment]
ありがとうございます！それではマージさせていただきます。

**Pull request merged**
