### PR TITLE
add first and last timestamp to results summary

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- added first and last timestamp to results summary.
- added Time Format options to logon-summary and metrics commands.

## Evidence

<details>
<summary>This PR ( ./938.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o test.csv -q)</summary>

 >./938.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o test.csv -q
...
Results Summary:

First Timeline: 2009-07-14 13:56:45.074 +09:00
Last Timeline: 2023-01-24 20:54:42.899 +09:00

Events with hits / Total events: 19,616 / 47,472 (Data reduction: 27,856 events (58.68%))

Total | Unique detections: 32,450 | 613
Total | Unique critical detections: 49 (0.15%) | 20 (3.26%)
Total | Unique high detections: 6,269 (19.32%) | 276 (45.02%)
Total | Unique medium detections: 1,655 (5.10%) | 190 (31.00%)
Total | Unique low detections: 6,346 (19.56%) | 74 (12.07%)
Total | Unique informational detections: 18,131 (55.87%) | 53 (8.65%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,645), medium: 2021-04-22 (198), low: 2016-09-20 (3,720), informational: 2016-08-19 (2,105)

...

Saved file: test.csv (16.4 M
</details>

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you!
1. Can you output First and Last timestamp after `Event Frequency Timeline`?
2. Can you add the First and Last timestamp in the HTML report as well?

**Review by fukusuket — APPROVED** [review]
I confirmed that the timestamp is output with the csv-timeline -U option. LGTM!🚀
This is a very helpful feature when reporting forensic results :)

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your review. The following points pointed out have been corrected

I would appreciate your confirmation.

> 
> 1. Can you output First and Last timestamp after `Event Frequency Timeline`?
> 2. Can you add the First and Last timestamp in the HTML report as well?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you!
The First and Last timestamp are being outputted correctly in the terminal now.
For the HTML report, can you move the First and Last timestamp right under the Results Summary? (Right before Events with hits)
Also the General Overview has big spaces in between the text making it very long.
Before:
Screen Shot 2023-02-21 at 7 09 04 AM
After:
Screen Shot 2023-02-21 at 7 09 14 AM

Can you reduce the spaces like it was before?

**Comment by hitenkoku** [comment]
@YamatoSecurity  IThe following remarks have been corrected I would like to ask you to please check them.

> @hitenkoku Thank you! The First and Last timestamp are being outputted correctly in the terminal now. For the HTML report, can you move the First and Last timestamp right under the Results Summary? (Right before Events with hits) Also the General Overview has big spaces in between the text making it very long. Before: Screen Shot 2023-02-21 at 7 09 04 AM After: Screen Shot 2023-02-21 at 7 09 14 AM
> 
> Can you reduce the spaces like it was before?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you so much! The HTML report is perfect now.
I just noticed that you added the Time Format options to `metrics` and `logon-summary`.
Thank you. 
I noticed that the First and Last timestamp are displayed with one file `-f` with `logon-summary`, but `logon-summary` does not display the First and Last timestamps when `-d` is used. Can you display the timestamps with `-d` also, as that option is used more?

**Comment by hitenkoku** [comment]
@YamatoSecurity  The following remarks have been corrected. We apologize for repeatedly asking for confirmation. Would you check it?
> I noticed that the First and Last timestamp are displayed with one file `-f` with `logon-summary`, but `logon-summary` does not display the First and Last timestamps when `-d` is used. Can you display the timestamps with `-d` also, as that option is used more?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you again!
度々ごめんなさい！もう１つ気づきました。。
`logon-summary`と`metrics`では、`--US-time`と`--US-military-time`が逆のようです。
`./target/release/hayabusa logon-summary -d ../hayabusa-sample-evtx/ --US-time`の場合は`2022-08-29 14:35:43.374 +09:00`のようなタイムスタンプで
`./target/release/hayabusa logon-summary -d ../hayabusa-sample-evtx/ --US-military-time`は`08-29-2022 02:35:43.374 PM +09:00`ですが、逆です。米軍時間の方が24時間のタイムスタンプです。
`csv-timeline`と`json-timeline`は、正しく`--US-time`と`--US-military-time`形式で表示しています。

**Comment by hitenkoku** [comment]
@YamatoSecurity  失礼いたしました。初期化の際に謝った値を代入していたことが原因でした。https://github.com/Yamato-Security/hayabusa/pull/939/commits/b76eca36413eb7d50b20ff9175ca4eebab9959b3  で修正を完了しました

> @hitenkoku Thank you again! 度々ごめんなさい！もう１つ気づきました。。 `logon-summary`と`metrics`では、`--US-time`と`--US-military-time`が逆のようです。 `./target/release/hayabusa logon-summary -d ../hayabusa-sample-evtx/ --US-time`の場合は`2022-08-29 14:35:43.374 +09:00`のようなタイムスタンプで `./target/release/hayabusa logon-summary -d ../hayabusa-sample-evtx/ --US-military-time`は`08-29-2022 02:35:43.374 PM +09:00`ですが、逆です。米軍時間の方が24時間のタイムスタンプです。 `csv-timeline`と`json-timeline`は、正しく`--US-time`と`--US-military-time`形式で表示しています。

**Review by YamatoSecurity — APPROVED** [review]
LGTM! ありがとうございました！

**Pull request merged**
