### PR TITLE
enhance pivot terminal output

### LINKED ISSUE #1022: Enhance pivot-keywords-list terminal output
@kazuminn 
これをお願いできますか？
1. Put spaces here:
Before:
```
583 / 583 [=============================================================] 100.00 %
The following pivot keywords were found:
Target IP Addresses: ( %DestAddress% %DestinationIp% ):
```
After:
```
583 / 583 [=============================================================] 100.00 %

The following pivot keywords were found:

Target IP Addresses: ( %DestAddress% %DestinationIp% ):
```
2. Output the headings (`Target IP Addresses: ( %DestAddress% %DestinationIp% ):`, `Subject Users: ( %SubjectUserName% ):`, etc..) in the same Green color as the hayabusa logo. (No color if `--no-color` is specified)
3. If there are no keywords, the results are just blank. Can you output the message "No keywords found." in red?
4. Can you output in the same order as defined in the `pivot_keywords.txt` file? Now it seems random but would like to determine the order. Any other way to set the order is also fine.
5. Can you move the `pivot_keywords.txt` file path to `rules/config/pivot_keywords.txt`? This is so I can update it in real time. I will create the config file there.

もし来週まで実装が難しいのであれば、無理せずに仰って下さい。次のリリースに入れたいです。

### PR DESCRIPTION
**Pull request by kazuminn**
fix #1022 

## What Changed

   - [x] Put spaces
   - [x] Output the headings (Target IP Addresses: ( %DestAddress% %DestinationIp% ):, Subject Users: ( %SubjectUserName% ):, etc..) in the same Green color as the hayabusa logo. (No color if --no-color is specified)
   - [x] If there are no keywords, the results are just blank. Can you output the message "No keywords found." in red?
   - [x] Can you output in the same order as defined in the pivot_keywords.txt file? Now it seems random but would like to determine the order. Any other way to set the order is also fine.
   - [x] Can you move the pivot_keywords.txt file path to rules/config/pivot_keywords.txt? This is so I can update it in real time. I will create the config file there.
   - [x] change document(hayabusa-rulesレポジトリの方にconfigが移動になったので、こっちのリポジトリに追従しなくなりました。なので、デフォルト設定ファイルの中身をベタ書きするのではなく、そちらのページを参照できるように変更しました。)

## Evidence

Please describe the functionality gained by merging this pull-request and the evidence that the bug has been fixed.

### CODE REVIEW

**Review by fukusuket — CHANGES_REQUESTED** [review]
I have confirmed that the new feature almost works :)
It seems that **the first pivot keyword** is output **in the header** as follows. (Alice,  CYBERCAT\pc1-user...) My test environment is `macOS` with `iTerm2`.
```
fukusuke@fukusukenoAMacBook-Air hayabusa-2.4.0-all-platforms % ./hayabusa pivot-keywords-list -d ../hayabusa-sample-evtx/YamatoSecurity/ -q

14 / 14 [===========================================================================================================================] 100.00 %

The following pivot keywords were found:

Source Computers: ( %WorkstationName%

Subject Users: ( %SubjectUserName%
No keywords found


Target Users: ( %TargetUserName% Alice

Users: ( %User% CYBERCAT\pc1-user
NT AUTHORITY\SYSTEM
DESKTOP-VQBONAV\user

Subject Logon IDs: ( %SubjectLogonId% 0x0

Target Logon IDs: ( %TargetLogonId% 0x27d676

Logon IDs: ( %LogonId% 0x678fe
0x6addb
0x1623e

IP Addresses: ( %IpAddress% 192.168.1.200
...
```
I would appreciate it if you could fix this🙏

**Comment by kazuminn** [comment]
@fukusuket Thank you for your review.
I fixed it.

**Comment by YamatoSecurity** [comment]
@kazuminn Thanks so much!
Just one small thing. Can you output the results in the default color? (in my case white)
Now the headers and the results are both green, but I just want the headers to be green.
Screen Shot 2023-05-05 at 6 29 10 AM

In this case, I want the following text to be white.
```
C:\Windows\system32\rundll32.exe
C:\Windows\system32\ApplicationFrameHost.exe
12516
5420
7048
11800
2A3BD16A-8368-630C-040B-010000000200
2A3BD16A-4A41-62A6-0201-000000000200
2A3BD16A-8475-630C-1F0B-010000000200
2A3BD16A-847D-630C-200B-010000000200
```

**Review by hitenkoku — APPROVED** [review]
LGTM

**Comment by kazuminn** [comment]
@YamatoSecurity 
Sorry. I missid what you said.
I fix it.
Could you review it again?

image

**Review by YamatoSecurity — APPROVED** [review]
@kazuminn Thanks so much! Looks perfect now.

**Pull request merged**
