### PR TITLE
fixed `update-rules` output updated rule

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Fixed updated rules output logic

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you so much for fix!
I tried `update-rules` on a fresh installation of 2.12.0, but it didn't seem to update(https://github.com/Yamato-Security/hayabusa-rules/pull/561/files)🤔
Could you please confirm?🙏 
```
hayabusa-2.12.0-all-platforms % ./hayabusa update-rules

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2024/01/10 23:38

 - Suspicious Redirection to Local Admin Share (Modified: 2023/12/28 | Path: rules/sigma/builtin/process_creation/proc_creation_win_susp_redirect_local_admin_share.yml)
 - Suspicious Redirection to Local Admin Share (Modified: 2023/12/28 | Path: rules/sigma/sysmon/process_creation/proc_creation_win_susp_redirect_local_admin_share.yml)
 - Remote PowerShell Session (PS Classic) (Modified: 2024/01/03 | Path: rules/sigma/builtin/powershell/powershell_classic/posh_pc_remote_powershell_session.yml)

Updated Sigma rules: 3
Rules updated successfully.
```
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your review.
I modified updated rule check logic from prev logic to  check logic file contents base.

**Review by fukusuket — APPROVED** [review]
Thank you so much for fix! 
I have confirmed that it has been updated as shown below. LGTM!!🚀
```
hayabusa-2.12.0-all-platforms % ./hayabusa update-rules

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2024/01/11 08:26

 - Service Started/Stopped Via Wmic.EXE (Modified: 2023/02/14 | Path: rules/sigma/sysmon/process_creation/proc_creation_win_wmic_service_manipulation.yml)
...
 - Procdump Execution (Modified: 2023/02/28 | Path: rules/sigma/sysmon/process_creation/proc_creation_win_sysinternals_procdump.yml)
 - PUA - Nimgrab Execution (Modified: 2023/02/13 | Path: rules/sigma/builtin/process_creation/proc_creation_win_pua_nimgrab.yml)

Updated Sigma rules: 356
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thank you!

**Pull request merged**
