### PR TITLE
reorder `search` result fields

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Reordered `search` result fields to look similar to the `csv-timeline` command results.

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! The reordering looks good.
Sorry one more thing I noticed. At the end, the results look like this:
```
2023-04-14 17:25:12.223 +09:00 · - · WIN · MS-Win-WinINet-Config/ProxyConfigChanged · 5600 · 14 · fAutoDetect: false ¦ pwszAutoConfigUrl: http://hacker-bypass.com/ ¦ pwszProxy: http://hacker-proxy.lan:123 ¦ pwszProxyBypass: http://internal.lan;<local> · ../hayabusa-sample-evtx/EVTX-to-MITRE-Attack/TA0011-Command and Control/T1572-Protocol tunneling/ID5600-proxy configuration changed.evtx



Total findings: 47476


Elapsed time: 00:00:26.1103

```
Can you make it look like:
```
2023-04-14 17:25:12.223 +09:00 · - · WIN · MS-Win-WinINet-Config/ProxyConfigChanged · 5600 · 14 · fAutoDetect: false ¦ pwszAutoConfigUrl: http://hacker-bypass.com/ ¦ pwszProxy: http://hacker-proxy.lan:123 ¦ pwszProxyBypass: http://internal.lan;<local> · ../hayabusa-sample-evtx/EVTX-to-MITRE-Attack/TA0011-Command and Control/T1572-Protocol tunneling/ID5600-proxy configuration changed.evtx

Total findings: 47,476
Elapsed time: 00:00:26.1103

```

With only a single space on above and below the summary and display `Total findings` with commas.

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀

**Comment by hitenkoku** [comment]
@YamatoSecurity  Sorry for my late replying.
I fixed your pointed out in https://github.com/Yamato-Security/hayabusa/pull/1300/commits/369e35d1bdf9c18fc52c7013b142d0179c872627.
Would you check it?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thank you so much!

**Pull request merged**
