### PR TITLE
Fixed bug info alert shows up twice in results summary

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Fixed bug info alert shows up twice in results summary

## Evidence

- main
```
 >./main.exe csv-timeline -d ../hayabusa-sample-evtx -r rules/hayabusa/builtin/BitsClient_Op/BitsCli_59_Info_BitsJobCreated.yml
...
Events with hits / Total events: 168 / 47,459 (Data reduction: 47,291 events (99.65%))

Total | Unique detections: 168 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 168 (100.00%) | 1 (100.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: 2020-11-12 (20)

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: IEWIN7 (1), MSEDGEWIN10 (1), sv-dc.hinokabegakure-no-sato.local (1), FS03.offsec.lan (1), jump01.offsec.lan (1)

╭────────────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts:       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Bits Job Created (168)      Bits Job Created (168) │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
│ n/a                         n/a                    │
╰───────────────────────────╌────────────────────────╯

Elapsed time: 00:00:04.592
```

```
 >./main.exe csv-timeline -d ../hayabusa-sample-evtx
...
Events with hits / Total events: 19,616 / 47,459 (Data reduction: 27,843 events (58.67%))

Total | Unique detections: 32,044 | 612
Total | Unique critical detections: 55 (0.17%) | 21 (3.43%)
Total | Unique high detections: 6,031 (18.82%) | 275 (44.93%)
Total | Unique medium detections: 1,830 (5.71%) | 195 (31.86%)
Total | Unique low detections: 5,998 (18.72%) | 68 (11.11%)
Total | Unique informational detections: 18,130 (56.58%) | 53 (8.66%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,650), medium: 2019-05-19 (247), low: 2016-09-20 (3,708), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (7), IEWIN7 (3), FS03.offsec.lan (2), IE10Win7 (2), rootdc1.offsec.lan (2)
high: MSEDGEWIN10 (120), IEWIN7 (70), FS03.offsec.lan (30), fs03vuln.offsec.lan (29), IE10Win7 (23)
medium: MSEDGEWIN10 (72), IEWIN7 (46), fs03vuln.offsec.lan (19), FS03.offsec.lan (19), srvdefender01.offsec.lan (16)
low: MSEDGEWIN10 (31), FS03.offsec.lan (17), IEWIN7 (15), fs03vuln.offsec.lan (14), fs01.offsec.lan (11)
informational: IEWIN7 (18), MSEDGEWIN10 (18), fs01.offsec.lan (15), PC01.example.corp (14), IE10Win7 (13)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                                       Top high alerts:                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage - Registry (8)                              Metasploit SMB Authentication (3,562)            │
│ CobaltStrike Service Installations - System (6)                            Malicious Svc Possibly Installed (271)           │
│ Active Directory Replication from Non Machine Account (6)                  Susp Svc Installed (257)                         │
│ Meterpreter or Cobalt Strike Getsystem Service Installation - System (6)   Suspicious Service Installation Script (250)     │
│ WannaCry Ransomware Activity (4)                                           PowerShell Scripts Installed as Services (250)   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                                         Top low alerts:                                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (235)                                           Logon Failure (Wrong Password) (3,564)           │
│ Proc Injection (104)                                                       Susp CmdLine (Possible LOLBIN) (1,418)           │
│ Reg Key Value Set (Sysmon Alert) (103)                                     Non Interactive PowerShell Process Spawned (325) │
│ Suspicious Remote Thread Target (93)                                       Proc Access (156)                                │
│ Remote Thread Creation Via PowerShell (93)                                 DLL Loaded (Sysmon Alert) (108)                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Proc Exec (11,173)                                                         Proc Exec (11,173)                               │
│ NetShare File Access (2,564)                                               NetShare File Access (2,564)                     │
│ PwSh Scriptblock (789)                                                     PwSh Scriptblock (789)                           │
│ PwSh Pipeline Exec (680)                                                   PwSh Pipeline Exec (680)                         │
│ NetShare Access (433)                                                      NetShare Access (433)                            │
╰──────────────────────────────────────────────────────────────────────────╌──────────────────────────────────────────────────╯
```

- This PR

```
 >./1031.exe csv-timeline -d ../hayabusa-sample-evtx -r rules/hayabusa/builtin/BitsClient_Op/BitsCli_59_Info_BitsJobCreated.yml
...
Events with hits / Total events: 168 / 47,459 (Data reduction: 47,291 events (99.65%))

Total | Unique detections: 168 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 168 (100.00%) | 1 (100.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: 2020-11-12 (20)

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: IEWIN7 (1), MSEDGEWIN10 (1), sv-dc.hinokabegakure-no-sato.local (1), FS03.offsec.lan (1), jump01.offsec.lan (1)

╭──────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts: │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Bits Job Created (168)      n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
╰───────────────────────────╌──────────────────╯

Saved file: 1031-test.csv (40.0 KB)
Elapsed time: 00:00:04.834
```

```
 >./1031.exe csv-timeline -d ../hayabusa-sample-evtx
...
Events with hits / Total events: 19,616 / 47,459 (Data reduction: 27,843 events (58.67%))

Total | Unique detections: 32,044 | 612
Total | Unique critical detections: 55 (0.17%) | 21 (3.43%)
Total | Unique high detections: 6,031 (18.82%) | 275 (44.93%)
Total | Unique medium detections: 1,830 (5.71%) | 195 (31.86%)
Total | Unique low detections: 5,998 (18.72%) | 68 (11.11%)
Total | Unique informational detections: 18,130 (56.58%) | 53 (8.66%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,650), medium: 2019-05-19 (247), low: 2016-09-20 (3,708), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (7), IEWIN7 (3), FS03.offsec.lan (2), IE10Win7 (2), rootdc1.offsec.lan (2)
high: MSEDGEWIN10 (120), IEWIN7 (70), FS03.offsec.lan (30), fs03vuln.offsec.lan (29), IE10Win7 (23)
medium: MSEDGEWIN10 (72), IEWIN7 (46), fs03vuln.offsec.lan (19), FS03.offsec.lan (19), srvdefender01.offsec.lan (16)
low: MSEDGEWIN10 (31), FS03.offsec.lan (17), IEWIN7 (15), fs03vuln.offsec.lan (14), fs01.offsec.lan (11)
informational: IEWIN7 (18), MSEDGEWIN10 (18), fs01.offsec.lan (15), PC01.example.corp (14), IE10Win7 (13)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                                       Top high alerts:                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage - Registry (8)                              Metasploit SMB Authentication (3,562)            │
│ CobaltStrike Service Installations - System (6)                            Malicious Svc Possibly Installed (271)           │
│ Active Directory Replication from Non Machine Account (6)                  Susp Svc Installed (257)                         │
│ Meterpreter or Cobalt Strike Getsystem Service Installation - System (6)   Suspicious Service Installation Script (250)     │
│ WannaCry Ransomware Activity (4)                                           PowerShell Scripts Installed as Services (250)   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                                         Top low alerts:                                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (235)                                           Logon Failure (Wrong Password) (3,564)           │
│ Proc Injection (104)                                                       Susp CmdLine (Possible LOLBIN) (1,418)           │
│ Reg Key Value Set (Sysmon Alert) (103)                                     Non Interactive PowerShell Process Spawned (325) │
│ Suspicious Remote Thread Target (93)                                       Proc Access (156)                                │
│ Remote Thread Creation Via PowerShell (93)                                 DLL Loaded (Sysmon Alert) (108)                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Proc Exec (11,173)                                                         NetShare File Access (2,564)                     │
│ PwSh Scriptblock (789)                                                     PwSh Pipeline Exec (680)                         │
│ NetShare Access (433)                                                      Explicit Logon (342)                             │
│ Svc Installed (331)                                                        New Non-USB PnP Device (268)                     │
│ Logon (Network) (228)                                                      File Created (210)                               │
╰──────────────────────────────────────────────────────────────────────────╌──────────────────────────────────────────────────╯

Saved file: 1031.csv (16.8 MB)
Elapsed time: 00:00:35.052
```

I would appreciate it if you could review.

### CODE REVIEW

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
Thanks for the quick fix!
Up to version 2.3.2, it would show in this order:
```
1 | 6
2 | 7
3 | 8
4 | 9
5 | 10
```
but in this PR it shows in this order
```
1 | 2
3 | 4
5 | 6
7 | 8
9 | 10
```
I think the way we did it before it easier to see, so could you sort as in the first example?

**Comment by hitenkoku** [comment]
@YamatoSecurity Thanks for your comment.

In https://github.com/Yamato-Security/hayabusa/pull/1032/commits/2e7e107d545e77283b9227311c210d8810e816f1 , The order of display has been restored and the name of the variable related to the order of display was not appropriate, so it has been corrected.

```
>./1031.exe csv-timeline -d ../hayabusa-sample-evtx  -o 1031-test2.csv
...
Events with hits / Total events: 19,616 / 47,459 (Data reduction: 27,843 events (58.67%))

Total | Unique detections: 32,044 | 612
Total | Unique critical detections: 55 (0.17%) | 21 (3.43%)
Total | Unique high detections: 6,031 (18.82%) | 275 (44.93%)
Total | Unique medium detections: 1,830 (5.71%) | 195 (31.86%)
Total | Unique low detections: 5,998 (18.72%) | 68 (11.11%)
Total | Unique informational detections: 18,130 (56.58%) | 53 (8.66%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,650), medium: 2019-05-19 (247), low: 2016-09-20 (3,708), informational: 2016-08-19 (2,105)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (7), IEWIN7 (3), FS03.offsec.lan (2), IE10Win7 (2), rootdc1.offsec.lan (2)
high: MSEDGEWIN10 (120), IEWIN7 (70), FS03.offsec.lan (30), fs03vuln.offsec.lan (29), IE10Win7 (23)
medium: MSEDGEWIN10 (72), IEWIN7 (46), fs03vuln.offsec.lan (19), FS03.offsec.lan (19), srvdefender01.offsec.lan (16)
low: MSEDGEWIN10 (31), FS03.offsec.lan (17), IEWIN7 (15), fs03vuln.offsec.lan (14), fs01.offsec.lan (11)
informational: IEWIN7 (18), MSEDGEWIN10 (18), fs01.offsec.lan (15), PC01.example.corp (14), IE10Win7 (13)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                                       Top high alerts:                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage - Registry (8)                              Metasploit SMB Authentication (3,562)            │
│ CobaltStrike Service Installations - System (6)                            Malicious Svc Possibly Installed (271)           │
│ Active Directory Replication from Non Machine Account (6)                  Susp Svc Installed (257)                         │
│ Meterpreter or Cobalt Strike Getsystem Service Installation - System (6)   Suspicious Service Installation Script (250)     │
│ WannaCry Ransomware Activity (4)                                           PowerShell Scripts Installed as Services (250)   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                                         Top low alerts:                                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (235)                                           Logon Failure (Wrong Password) (3,564)           │
│ Proc Injection (104)                                                       Susp CmdLine (Possible LOLBIN) (1,418)           │
│ Reg Key Value Set (Sysmon Alert) (103)                                     Non Interactive PowerShell Process Spawned (325) │
│ Suspicious Remote Thread Target (93)                                       Proc Access (156)                                │
│ Remote Thread Creation Via PowerShell (93)                                 DLL Loaded (Sysmon Alert) (108)                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Proc Exec (11,173)                                                         Explicit Logon (342)                             │
│ NetShare File Access (2,564)                                               Svc Installed (331)                              │
│ PwSh Scriptblock (789)                                                     New Non-USB PnP Device (268)                     │
│ PwSh Pipeline Exec (680)                                                   Logon (Network) (228)                            │
│ NetShare Access (433)                                                      File Created (210)                               │
╰──────────────────────────────────────────────────────────────────────────╌──────────────────────────────────────────────────╯

Saved file: 1031-test2.csv (16.8 MB)
Elapsed time: 00:00:25.113

```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM!
Thank you so much!

**Comment by hitenkoku** [comment]
thanks for checking.
I merge it.

**Pull request merged**
