### PR TITLE
Bugfix error when target env not installed vc redistribute package

### LINKED ISSUE #635: [bug] Error when target environment is not installed vc redistribute package(Reopen #404)
**Describe the bug**
Error when target environment is not installed vcc redistribute package(Reopen #404).

**Step to Reproduce**
1. Download [hayabusa-1.4.2-windows-64-bit.zip](https://github.com/Yamato-Security/hayabusa/releases/download/v1.4.2/hayabusa-1.4.2-windows-64-bit.zip) from release page and unzip.
2. Open command prompt(Run as Administrator).
3. Execute help command.
   ` hayabusa-1.4.2-win-x64.exe -h`
4. See error as follows.
   ```
   The program can't start because vcruntime140.dll is missing from your computer. Try reinstalling it to fix this problem?
   ```

**Expected behavior**
vcruntime140.dll not found error does not occur.

**Screenshots**
Error screenshots is as follows.
error

**Environment**
 - OS: Microsoft Windows 11 Home(version: 10.0.22000 N/A build 22000)
 - Hayabusa version: 1.4.2 ~ 1.3.0

**Additional context**
- After installing [vc-redist](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), this error does not occur.
- Hayabusa version 1.2.2 ~ 1.1.0 did not occur this error because of Fix:#408.
- But, [this commint (crate static_vcruntime version up(1.5.0 to 2.0))](https://github.com/Yamato-Security/hayabusa/commit/6811acae6a3e394d779858369b563304a2b7d7f3) seems to have caused this regression.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Fix #635.
- Changed the declaration of static_vcruntime version 2.0 according to the following README diff(v1.5.0 -> v.2.0). 
    - https://github.com/ChrisDenton/static_vcruntime/commit/da091c4b9d65101ca0dfd68340c5ff5be0a7bbb0

## Evidence
**Environment**
- OS: Microsoft Windows 11 Home(version: 10.0.22000 N/A build 22000)
- and [vc-redist](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) not installed.

**Screenshots**
- vcruntime140.dll not found error does not occur as follows.
success

### CODE REVIEW

**Review by YamatoSecurity — APPROVED** [review]
Looks good to me. Thank you so much for the fix!

**Comment by YamatoSecurity** [comment]
@hitenkoku すみません、ビルド失敗の確認をお願いできますか？

**Comment by fukusuket** [comment]
Thanks for the review! I'm sorry, cargo fmt was not applied, so I applied it.

**Comment by hitenkoku** [comment]
@YamatoSecurity 現在確認してみたらcargo fmtで対応してもらっているため、特には追加対応は不要かと思われます。問題ないと思います。

**Review by hitenkoku — APPROVED** [review]
thanks for your pull request. LGTM.

**Pull request merged**
