### PR TITLE
feat: Field data mapping (code -> message)

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- #177 
  - added field data mapping according to https://github.com/Yamato-Security/hayabusa-rules/pull/424 yaml files
    - added `field_data_map.rs` for field data mapping process
  - added command line option `-F --no-field-data-mapping` for user wants to process as fast as possible

I would appreciate it if you could review🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
## Environment
- OS: macOS montery version 13.1
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8

## Test1 (mapping works)
EID `4624`'s diff(`ElevatedToken`, `ImpersonationLevel`, `LogonType`, `VirtualAccount`)
```
< "2022-05-01 13:42:00.800 +09:00","wind10.winlab.local","Sec",4624,"info","Logon (Network)","Zach Mathis","2023/12/16","stable",21373,"Type: 3 ¦ TgtUser: Administrator ¦ SrcComp: - ¦ SrcIP: 192.168.1.219 ¦ LID: 0x82215a","AuthenticationPackageName: Kerberos ¦ ElevatedToken: %%1842 ¦ ImpersonationLevel: %%1833 ¦ IpPort: 63652 ¦ KeyLength: 0 ¦ LogonGuid: 59CEFB69-4F9D-7486-C449-471E00B814E3 ¦ LogonProcessName: Kerberos ¦ ProcessId: 0x0 ¦ SubjectLogonId: 0x0 ¦ SubjectUserSid: S-1-0-0 ¦ TargetDomainName: WINLAB.LOCAL ¦ TargetLinkedLogonId: 0x0 ¦ TargetUserSid: S-1-5-21-81107902-1099128984-1836738286-500 ¦ VirtualAccount: %%1843","","","","Sec","2020/11/08","Sec_4624_Info_Logon-Type-3-Network.yml","../hayabusa-sample-evtx/EVTX-ATTACK-SAMPLES/Privilege Escalation/NTLM2SelfRelay-med0x2e-security_4624_4688.evtx"
---
> "2022-05-01 13:42:00.800 +09:00","wind10.winlab.local","Sec",4624,"info","Logon (Network)","Zach Mathis","2023/12/16","stable",21373,"Type: 3 - NETWORK ¦ TgtUser: Administrator ¦ SrcComp: - ¦ SrcIP: 192.168.1.219 ¦ LID: 0x82215a","AuthenticationPackageName: Kerberos ¦ ElevatedToken: YES ¦ ImpersonationLevel: IMPERSONATION ¦ IpPort: 63652 ¦ KeyLength: 0 ¦ LogonGuid: 59CEFB69-4F9D-7486-C449-471E00B814E3 ¦ LogonProcessName: Kerberos ¦ ProcessId: 0x0 ¦ SubjectLogonId: 0x0 ¦ SubjectUserSid: S-1-0-0 ¦ TargetDomainName: WINLAB.LOCAL ¦ TargetLinkedLogonId: 0x0 ¦ TargetUserSid: S-1-5-21-81107902-1099128984-1836738286-500 ¦ VirtualAccount: NO","","","","Sec","2020/11/08","Sec_4624_Info_Logon-Type-3-Network.yml","../hayabusa-sample-evtx/EVTX-ATTACK-SAMPLES/Privilege Escalation/NTLM2SelfRelay-med0x2e-security_4624_4688.evtx"
```

EID `4625`'s diff(`LogonType`, `FailureReason`, `Status`, `SubStatus`)
```
< "2016-09-20 01:50:06.477 +09:00","DESKTOP-M5SN04R","Sec",4625,"low","Logon Failure (User Does Not Exist)","Zach Mathis","2022/12/16","stable",2455,"Type: 3 ¦ TgtUser: JcDfcZTc ¦ SrcComp: 6hgtmVlrrFuWtO65 ¦ SrcIP: 192.168.198.149 ¦ AuthPkg: NTLM ¦ Proc: -","FailureReason: %%2313 ¦ IpPort: 50249 ¦ KeyLength: 0 ¦ LogonProcessName: NtLmSsp ¦ ProcessId: 0x0 ¦ Status: 0xc000006d ¦ SubStatus: 0xc0000064 ¦ SubjectLogonId: 0x0 ¦ SubjectUserSid: S-1-0-0 ¦ TargetDomainName: . ¦ TargetUserSid: S-1-0-0","","","","Sec","2020/11/08","Sec_4625_Low_LogonFail_NonExistantUser.yml","../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx"
---
> "2016-09-20 01:50:06.477 +09:00","DESKTOP-M5SN04R","Sec",4625,"low","Logon Failure (User Does Not Exist)","Zach Mathis","2022/12/16","stable",2455,"Type: 3 - NETWORK ¦ TgtUser: JcDfcZTc ¦ SrcComp: 6hgtmVlrrFuWtO65 ¦ SrcIP: 192.168.198.149 ¦ AuthPkg: NTLM ¦ Proc: -","FailureReason: BAD USER OR PW ¦ IpPort: 50249 ¦ KeyLength: 0 ¦ LogonProcessName: NtLmSsp ¦ ProcessId: 0x0 ¦ Status: BAD USER OR PW ¦ SubStatus: UNKNOWN USER ¦ SubjectLogonId: 0x0 ¦ SubjectUserSid: S-1-0-0 ¦ TargetDomainName: . ¦ TargetUserSid: S-1-0-0","","","","Sec","2020/11/08","Sec_4625_Low_LogonFail_NonExistantUser.yml","../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx"
```

EID `4678`'s diff (`AccessMask`)
```
< "2020-09-14 23:44:14.393 +09:00","Sec504Student","Sec",4674,"med","Possible Hidden Service Created","Joshua Wright, Zach Mathis (rule creation)","2022/12/16","stable",39396,"Svc: nginx ¦ User: Sec504 ¦ AccessMask: %%1539 ¦ LID: 0x99e3d","HandleId: 0xffff820cb1b23928 ¦ ObjectServer: SC Manager ¦ ObjectType: SERVICE OBJECT ¦ PrivilegeList: SeSecurityPrivilege ¦ ProcessId: 0x21c ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: SEC504STUDENT ¦ SubjectUserSid: S-1-5-21-2977773840-2930198165-1551093962-1000","Persis","T1543.003","","Sec","2022/02/05","Sec_4674_Med_OpAttemptOnPrivObj_PossibleHiddenSvcCreationAttempt.yml","../hayabusa-sample-evtx/DeepBlueCLI/eventlog-dac.evtx"
---
> "2020-09-14 23:44:14.393 +09:00","Sec504Student","Sec",4674,"med","Possible Hidden Service Created","Joshua Wright, Zach Mathis (rule creation)","2022/12/16","stable",39396,"Svc: nginx ¦ User: Sec504 ¦ AccessMask: WRITE_DAC ¦ LID: 0x99e3d","HandleId: 0xffff820cb1b23928 ¦ ObjectServer: SC Manager ¦ ObjectType: SERVICE OBJECT ¦ PrivilegeList: SeSecurityPrivilege ¦ ProcessId: 0x21c ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: SEC504STUDENT ¦ SubjectUserSid: S-1-5-21-2977773840-2930198165-1551093962-1000","Persis","T1543.003","","Sec","2022/02/05","Sec_4674_Med_OpAttemptOnPrivObj_PossibleHiddenSvcCreationAttempt.yml","../hayabusa-sample-evtx/DeepBlueCLI/eventlog-dac.evtx"
```

**Comment by fukusuket** [comment]
## Test2 (No difference between This PR and main)
I confirmed that the result of `-F --no-field-data-mapping`(This PR) has no difference from main.
I checked following two profiles.
- super-verbose
- standard
```
hayabusa-2.6.0-all-platforms % diff new-super-verbose-F.csv old-super-verbose.csv
hayabusa-2.6.0-all-platforms % diff new-super-verbose-F.json old-super-verbose.json
hayabusa-2.6.0-all-platforms % diff new-F.csv old.csv
hayabusa-2.6.0-all-platforms % diff new-F.json old.json
hayabusa-2.6.0-all-platforms %
```

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much!
I will check and take some benchmarks.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking!
It looks like we can do more data mapping in the event log of `4674`, is data mapping possible?
(I don't think it's possible to implement all data mappings, but it would be nice to be able to add known mappings to yaml.)
```
< "2021-04-21 18:40:32.364 +09:00","srvdefender01.offsec.lan","Sec",4674,"med",349344,"Possible Hidden Service Created","Svc: PSEXESVC ¦ User: admmig ¦ AccessMask: %%1537 %%1538 %%1539 %%7184 %%7185 %%7186 %%7187 %%7188 %%7189 %%7190 %%7191 %%7192 ¦ LID: 0x1376020","AccessMask: %%1537 %%1538 %%1539 %%7184 %%7185 %%7186 %%7187 %%7188 %%7189 %%7190 %%7191 %%7192 ¦ HandleId: 0xffff8000ef4fe9f8 ¦ ObjectServer: SC Manager ¦ ObjectType: SERVICE OBJECT ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x238 ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
---
> "2021-04-21 18:40:32.364 +09:00","srvdefender01.offsec.lan","Sec",4674,"med",349344,"Possible Hidden Service Created","Svc: PSEXESVC ¦ User: admmig ¦ AccessMask: %%1537 READ_CONTROL WRITE_DAC %%7184 %%7185 %%7186 %%7187 %%7188 %%7189 %%7190 %%7191 %%7192 ¦ LID: 0x1376020","AccessMask: %%1537 READ_CONTROL WRITE_DAC %%7184 %%7185 %%7186 %%7187 %%7188 %%7189 %%7190 %%7191 %%7192 ¦ HandleId: 0xffff8000ef4fe9f8 ¦ ObjectServer: SC Manager ¦ ObjectType: SERVICE OBJECT ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x238 ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
```

```
< "2021-04-21 18:40:32.362 +09:00","srvdefender01.offsec.lan","Sec",4674,"med",349342,"SCM Database Privileged Operation","Svc: ServicesActive ¦ User: admmig ¦ AccessMask: %%1537 %%1538 %%1539 %%7168 %%7169 %%7170 %%7171 %%7172 %%7173 ¦ LID: 0x1376020","AccessMask: %%1537 %%1538 %%1539 %%7168 %%7169 %%7170 %%7171 %%7172 %%7173 ¦ HandleId: 0xffff8000ef4fe9f8 ¦ ObjectServer: SC Manager ¦ ObjectType: SC_MANAGER OBJECT ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x238 ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
---
> "2021-04-21 18:40:32.362 +09:00","srvdefender01.offsec.lan","Sec",4674,"med",349342,"SCM Database Privileged Operation","Svc: ServicesActive ¦ User: admmig ¦ AccessMask: %%1537 READ_CONTROL WRITE_DAC %%7168 %%7169 %%7170 %%7171 %%7172 %%7173 ¦ LID: 0x1376020","AccessMask: %%1537 READ_CONTROL WRITE_DAC %%7168 %%7169 %%7170 %%7171 %%7172 %%7173 ¦ HandleId: 0xffff8000ef4fe9f8 ¦ ObjectServer: SC Manager ¦ ObjectType: SC_MANAGER OBJECT ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x238 ¦ ProcessName: C:\Windows\System32\services.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
```

```
< "2021-10-27 19:34:50.024 +09:00","FS03.offsec.lan","Sec",4674,"high",127533,"Mimikatz Use","Svc: \REGISTRY\USER\S-1-5-21-4230534742-2542757381-3142984815-1111\Printers\Connections\,,fs03vuln,Kiwi Legit Printer ¦ User: admmig ¦ AccessMask: %%1537 %%1538 %%1539 %%1540 %%4432 %%4433 %%4434 %%4435 %%4436 %%4437 ¦ LID: 0x123550","AccessMask: %%1537 %%1538 %%1539 %%1540 %%4432 %%4433 %%4434 %%4435 %%4436 %%4437 ¦ HandleId: 0x6a4 ¦ ObjectServer: Security ¦ ObjectType: Key ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x418 ¦ ProcessName: C:\Windows\System32\spoolsv.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
---
> "2021-10-27 19:34:50.024 +09:00","FS03.offsec.lan","Sec",4674,"high",127533,"Mimikatz Use","Svc: \REGISTRY\USER\S-1-5-21-4230534742-2542757381-3142984815-1111\Printers\Connections\,,fs03vuln,Kiwi Legit Printer ¦ User: admmig ¦ AccessMask: %%1537 READ_CONTROL WRITE_DAC WRITE_OWNER QUERY_KEY_VALUE %%4433 %%4434 ENUMERATE_SUBKEYS %%4436 %%4437 ¦ LID: 0x123550","AccessMask: %%1537 READ_CONTROL WRITE_DAC WRITE_OWNER QUERY_KEY_VALUE %%4433 %%4434 ENUMERATE_SUBKEYS %%4436 %%4437 ¦ HandleId: 0x6a4 ¦ ObjectServer: Security ¦ ObjectType: Key ¦ PrivilegeList: SeTakeOwnershipPrivilege ¦ ProcessId: 0x418 ¦ ProcessName: C:\Windows\System32\spoolsv.exe ¦ SubjectDomainName: OFFSEC ¦ SubjectUserSid: S-1-5-21-4230534742-2542757381-3142984815-1111"
```

**Review by hitenkoku — APPROVED** [review]
Thanks for your pull request.
LGTM

**Comment by YamatoSecurity** [comment]
> @YamatoSecurity Thank you so much for checking! It looks like we can do more data mapping in the event log of `4674`, is data mapping possible? (I don't think it's possible to implement all data mappings, but it would be nice to be able to add known mappings to yaml.)

Thanks for letting me know! Yes, I will try to update this in the hayabusa-rules repository soon.

**Comment by YamatoSecurity** [comment]
@fukusuket 
I don't think this is related to this PR, but could you do the following:

Screenshot 2023-07-19 at 11 17 50 AM
1. Could you put a space between "Results Summary" and "Events with hits" ?

Screenshot 2023-07-19 at 11 18 04 AM
2. Could you put a space after the progress bar and before "Scanning finished...." and make sure there is only 1 space between "Scanning finished..." and "Rule Authors"? (Now there is 2 for some reason)

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM!
I did a benchmark on 130GB of data.
With new default data mapping
Processing time: `4:49:49`
Memory: `113 GB`

`-F` option:
Processing time: `4:52:11`
Memory: `113 GB`

It seems to have a very small impact on performance at the moment.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for benchmarking!  It's good to hear that this is small performance impact...😌
I fixed https://github.com/Yamato-Security/hayabusa/pull/1132#issuecomment-1641286186 . Could you please check it?

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you! Everything LGTM!

**Pull request merged**
