### PR TITLE
fixed duplicate fields are outputted in extrafieldinfo

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- fixed duplicate fields are outputted in extrafieldinfo
- fixed cargo clippy error

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
I confirmed that there is no diffs in the following commands before and after the fix!
`% ./hayabusa json-timeline -d ../hayabusa-sample-evtx  --include-eid 4624 -o eid-4624.json`
`% ./hayabusa json-timeline -d ../hayabusa-sample-evtx  --include-eid 4625 -o eid-4625.json`


However, the following command seems to output duplicate `ParentCmdline` ?
Could you please confirm?(Sorry if I misunderstood the specifications!)
`% ./hayabusa json-timeline -d ../hayabusa-sample-evtx  --include-eid 1 -o eid-1.json`
```
{
    "Timestamp": "2019-02-16 19:02:21.934 +09:00",
    "Computer": "PC01.example.corp",
    "Channel": "Sysmon",
    "EventID": 1,
    "Level": "info",
    "RecordID": 1940899,
    "RuleTitle": "Proc Exec",
    "Details": {
        "Cmdline": "plink.exe 10.0.2.18 -P 80 -C -R 127.0.0.3:4444:127.0.0.2:3389 -l test -pw test",
        "Company": "Simon Tatham",
        "Description": "Command-line SSH, Telnet, and Rlogin client",
        "Hashes": "SHA1=7806AD24F669CD8BB9EBE16F87E90173047F8EE4",
        "LGUID": "365ABB72-D6AB-5C67-0000-002056660200",
        "LID": "0x26656",
        "PGUID": "365ABB72-DFAD-5C67-0000-0010E0811500",
        "PID": 2312,
        "ParentCmdline": "\"C:\\Windows\\system32\\cmd.exe\" \"",
        "ParentPGUID": "365ABB72-D92A-5C67-0000-0010CB580900",
        "ParentPID": 3904,
        "Proc": "C:\\Users\\IEUser\\Desktop\\plink.exe",
        "Product": "PuTTY suite",
        "User": "PC01\\IEUser"
    },
    "ExtraFieldInfo": {
        "CurrentDirectory": "C:\\Users\\IEUser\\Desktop\\",
        "FileVersion": "Release 0.70",
        "IntegrityLevel": "High",
        "ParentCommandLine": "\"C:\\Windows\\system32\\cmd.exe\"",
        "ParentImage": "C:\\Windows\\System32\\cmd.exe",
        "RuleName": "",
        "TerminalSessionId": 1,
        "UtcTime": "2019-02-16 10:02:21.934"
    }
}
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your comment.

I checked space in `ParentCmdline`. I trimed space in Details values

fixed in https://github.com/Yamato-Security/hayabusa/pull/1187/commits/c158988b568f6d8bcb5ab54c156a24c47d95733e

Could you check it?

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you for fix :) I confirmed https://github.com/Yamato-Security/hayabusa/pull/1187#pullrequestreview-1669428226 !

Sorry for not noticing it in advance...
It seems that the issue also occurs in the following PowerShell log, could you please check it?
`% ./hayabusa json-timeline -d ../hayabusa-sample-evtx  --include-eid 4103 -o eid-4103.json -C`
`% ./hayabusa json-timeline -d ../hayabusa-sample-evtx  --include-eid 4104 -o eid-4104.json -C`

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you so much for fix! I confirmed `EID: 4103`!
Just one point, There were two `ScriptBlockText` remaining in the `EID:4104`, could you please check them?
```
% cat eid-4104.json | grep ScriptBlockText | wc -l
       2
```

**Comment by YamatoSecurity** [comment]
> "Details": {
>         "Payload": "CommandInvocation(Out-Default): \"Out-Default\"\\r\\n"
>     },
>     "ExtraFieldInfo": {
>         "ContextInfo": "Severity = Informational Host Name = ConsoleHost Host Version = 4.0 Host ID = 7f6359d5-da68-4ff5-8b7e-f3393366b020 Host Application = C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe Engine Version = 4.0 Runspace ID = c8166557-78a4-43a8-843d-dffbe24fa1ab Pipeline ID = 56 Command Name = Command Type = Script Script Name = Command Path = Sequence Number = 392 User = OFFSEC\\admmig Shell ID = Microsoft.PowerShell",
>         "UserData": ""
>     },
>     "AllFieldInfo": {
>         "ContextInfo": "Severity = Informational Host Name = ConsoleHost Host Version = 4.0 Host ID = 7f6359d5-da68-4ff5-8b7e-f3393366b020 Host Application = C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe Engine Version = 4.0 Runspace ID = c8166557-78a4-43a8-843d-dffbe24fa1ab Pipeline ID = 56 Command Name = Command Type = Script Script Name = Command Path = Sequence Number = 392 User = OFFSEC\\admmig Shell ID = Microsoft.PowerShell",
>         "Payload": "CommandInvocation(Out-Default): \"Out-Default\"",
>         "UserData": ""
>     }

@hitenkoku 
It looks like the `Payload` in `Details` keeps the return characters `\\r\\n` but they get stripped in `AllFieldInfo`. For JSON output, I want to keep tabs, spaces, return characters, etc.. as they are in the original log. Is this possible to keep the same for `Details`, `ExtraFieldInfo` and `AllFieldInfo`? (The value of the field should not change.)

**Comment by hitenkoku** [comment]
@YamatoSecurity Perhaps the removal of \r\n was done to accommodate the issue of reducing the file size.

I think it is possible to implement this, but if it is done in this pull-request, the changelog will be complicated, so let's make it a policy to do it in other issues.

I will create the issue.

> > "Details": {
> > "Payload": "CommandInvocation(Out-Default): "Out-Default"\r\n"
> > },
> > "ExtraFieldInfo": {
> > "ContextInfo": "Severity = Informational Host Name = ConsoleHost Host Version = 4.0 Host ID = 7f6359d5-da68-4ff5-8b7e-f3393366b020 Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Engine Version = 4.0 Runspace ID = c8166557-78a4-43a8-843d-dffbe24fa1ab Pipeline ID = 56 Command Name = Command Type = Script Script Name = Command Path = Sequence Number = 392 User = OFFSEC\admmig Shell ID = Microsoft.PowerShell",
> > "UserData": ""
> > },
> > "AllFieldInfo": {
> > "ContextInfo": "Severity = Informational Host Name = ConsoleHost Host Version = 4.0 Host ID = 7f6359d5-da68-4ff5-8b7e-f3393366b020 Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Engine Version = 4.0 Runspace ID = c8166557-78a4-43a8-843d-dffbe24fa1ab Pipeline ID = 56 Command Name = Command Type = Script Script Name = Command Path = Sequence Number = 392 User = OFFSEC\admmig Shell ID = Microsoft.PowerShell",
> > "Payload": "CommandInvocation(Out-Default): "Out-Default"",
> > "UserData": ""
> > }
> 
> @hitenkoku It looks like the `Payload` in `Details` keeps the return characters `\\r\\n` but they get stripped in `AllFieldInfo`. For JSON output, I want to keep tabs, spaces, return characters, etc.. as they are in the original log. Is this possible to keep the same for `Details`, `ExtraFieldInfo` and `AllFieldInfo`? (The value of the field should not change.)

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your check many times.

I fixed duplicate field of ExtraFieldInfo in ScriptBlockText in https://github.com/Yamato-Security/hayabusa/pull/1187/commits/9c6d321b357556b624326b8c4d12627d5a1840cf

Could you check it ?

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you so much for fix !
It looks like there's only one `ScriptBlockText` left, Could you please check?
```
% cat 4104.json | grep ScriptBlockText | wc -l
       1
```

```
{
    "Timestamp": "2021-04-22 19:19:38.081 +09:00",
    "Computer": "win10-02.offsec.lan",
    "Channel": "PwSh",
    "EventID": 4104,
    "Level": "med",
    "RecordID": 211,
    "RuleTitle": "Potentially Malicious PwSh",
    "Details": {
        "ScriptBlock": "ne=$true)]\\r\\n [PSTypeName('Microsoft.Management.Infrastructure.CimInstance#root/standardcimv2/MSFT_NetIKEP2AuthSet')]
    ...
    "ExtraFieldInfo": {
        "MessageNumber": 4,
        "MessageTotal": 17,
        "Path": "",
        "ScriptBlockId": "65128610-e603-4667-b94f-f7077889aaad",
        "ScriptBlockText": "ne=$true)] [PSTypeName('Microsoft.Management.Infrastructure.CimInstance#root/standardcimv2/MSFT_NetIKEP2AuthSet')] 
...

....
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your review.

I fixed in https://github.com/Yamato-Security/hayabusa/pull/1187/commits/f6e1c3b6fa48c673d974c0dcac99735e98ee4aef . Could you check it?

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for quick fix ! I confirmed `EID:4104`. LGTM!!🚀

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your review!

**Comment by YamatoSecurity** [comment]
I did some benchmarks and it seems that this PR uses about 20% more memory.
Perhaps it is due to the extra clone usage:
```
sp_removed_details_in_record.push(remove_sp_char(v.clone(), true));
sp_removed_details_in_record_trim_newline.push(remove_sp_char(v.clone(), false));
```
Is it possible to get rid of 1 or both of the clone uses?

main branch:
Elapsed time: 3 hours 14 minutes
Memory usage: 68.7 GB

this PR:
Elapsed time: 3 hours 19 minutes
Memory usage: 83.2 GB

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your review.

removed followwing clone processing in https://github.com/Yamato-Security/hayabusa/pull/1190 . 

Could you check #1190 ?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! Unfortunately the memory usage is still high. Any other ideas of how we could decrease memory usage?  (cc: @fukusuket )

**Comment by hitenkoku** [comment]
<details>

<summary>main (5b99068) </summary>

```
Saved file: main-all-evtx.json (3.4 GB)

Elapsed time: 00:06:14.095
Rule Parse Processing Time: 00:00:02.607
Analysis Processing Time: 00:04:25.519
Output Processing Time: 00:01:45.966

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:    10.0 GiB    10.0 GiB     0          10.0 GiB
 committed:     8.3 GiB    48.5 GiB    40.4 GiB     8.0 GiB
     reset:     0
    purged:    16.3 GiB
   touched:   128.5 KiB    14.6 MiB    74.4 GiB   -74.4 GiB                          ok
  segments:    13         234         226           8                                not all freed!
-abandoned:     1           1           0           1                                not all freed!
   -cached:     0           0           0           0                                ok
     pages:     0           0         870.4 Ki   -870.4 Ki                           ok
-abandoned:     3           3           0           3                                not all freed!
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   317.1 Ki
    resets:     0
    purges:    26.8 Ki
   threads:    33          33           1          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:   374.117 s
   process: user: 230.390 s, system: 3.234 s, faults: 8018101, rss: 8.1 GiB, commit: 8.3 GiB
```

</details>

**Comment by hitenkoku** [comment]
@YamatoSecurity  I rechecked and fixed code.

improved memory usage from 49.4GB to 48.5 GB in https://github.com/Yamato-Security/hayabusa/pull/1187/commits/1e1f5c500f47af753847b458b932a55b9e6c1352 .

Could you check it?

<details>

<summary> improved (1e1f5c500f47af753847b458b932a55b9e6c1352) </summary>

```
Saved file: 1186-all-evtx-2.json (3.4 GB)

Elapsed time: 00:05:53.281
Rule Parse Processing Time: 00:00:02.616
Analysis Processing Time: 00:04:28.646
Output Processing Time: 00:01:22.017

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:    10.0 GiB    10.0 GiB     0          10.0 GiB
 committed:     8.4 GiB    48.5 GiB    40.2 GiB     8.2 GiB
     reset:     0
    purged:    16.4 GiB
   touched:   128.5 KiB    17.5 MiB    74.4 GiB   -74.4 GiB                          ok
  segments:    13         281         273           8                                not all freed!
-abandoned:     1           1           0           1                                not all freed!
   -cached:     0           0           0           0                                ok
     pages:     0           0         872.0 Ki   -872.0 Ki                           ok
-abandoned:     3           3           0           3                                not all freed!
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   321.9 Ki
    resets:     0
    purges:    26.9 Ki
   threads:    33          33           1          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:   353.297 s
   process: user: 230.109 s, system: 2.984 s, faults: 7958604, rss: 8.3 GiB, commit: 8.4 GiB
```

</details>

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! I will do some benchmarks and let you know.

**Comment by YamatoSecurity** [comment]
@hitenkoku Elapsed time is now the same as the main branch of 3:17 and the memory usage has dropped to 61 GB which is better than the main branch!

Unfortunately, the number of detections and unique detections is different from the main branch.
In the data set that I checked with, the main branch detects `Potential Access Token Abuse` but this PR does not, although it should.
The rule is looking for `%%1833` but it gets converted to `IMPERSONATION`, so maybe that is the problem?
I compared the field values for this record with the main branch and this PR but the output is exactly the same. So something seems to have changed in the detecting process.

Also, the count for `Susp CmdLine (Possible LOLBIN)` and `Pass the Hash Activity 2` alerts have also decreased in this PR.

**Pull request merged**
