### PR TITLE
fix(afterfact): modified output format from "-" str to empty Dict in …

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- fixed JSONL Output contain a JSON object in the Details key

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
I executed the following command and it seems that there are still cases where “-” is output (not an aggregation rule). I would appreciate it if you could confirm this 🙏
```
% ./hayabusa json-timeline -d ../hayabusa-sample-evtx -o timeline.json -C -w
```
```json
{
    "Timestamp": "2016-09-20 22:07:23.000 +09:00",
    "RuleTitle": "Event Log Svc Stopped",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6006,
    "RecordID": 8245,
    "Details": "-",
    "ExtraFieldInfo": {
        "Binary": "010000002EA20000"
    }
}
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your point out. I fixed following point out in https://github.com/Yamato-Security/hayabusa/pull/1390/commits/7b72934396b3efa8d30f44822efb9431f8a94643.

Would you recheck it?


> @hitenkoku I executed the following command and it seems that there are still cases where “-” is output (not an aggregation rule). I would appreciate it if you could confirm this 🙏
> 
> ```
> % ./hayabusa json-timeline -d ../hayabusa-sample-evtx -o timeline.json -C -w
> ```
> 
> ```json
> {
>     "Timestamp": "2016-09-20 22:07:23.000 +09:00",
>     "RuleTitle": "Event Log Svc Stopped",
>     "Level": "info",
>     "Computer": "IE10Win7",
>     "Channel": "Sys",
>     "EventID": 6006,
>     "RecordID": 8245,
>     "Details": "-",
>     "ExtraFieldInfo": {
>         "Binary": "010000002EA20000"
>     }
> }
> ```

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you so much for fix!  It appears that case https://github.com/Yamato-Security/hayabusa/pull/1390#pullrequestreview-2199635015 is still occurring? Could you  confirm?🙏
>./hayabusa json-timeline -d ../hayabusa-sample-evtx -o timeline.json -C -w --include-eid 6006

```json
{
    "Timestamp": "2016-09-20 22:07:23.000 +09:00",
    "RuleTitle": "Event Log Svc Stopped",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6006,
    "RecordID": 8245,
    "Details": "-",
    "ExtraFieldInfo": {
        "Binary": "010000002EA20000"
    }
}
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your check. I fixed in https://github.com/Yamato-Security/hayabusa/pull/1390/commits/499c3aec4cc129d65436a9eb4b5fcd7900dd6f82.

Sorry to bother you again. Would you recheck it?

``` json
{
    "Timestamp": "2013-10-24 01:16:27.000 +09:00",
    "RuleTitle": "Event Log Svc Started",
    "Level": "info",
    "Computer": "37L4247D28-05",
    "Channel": "Sys",
    "EventID": 6005,
    "RecordID": 4,
    "Details": {}
}
```

> @hitenkoku Thank you so much for fix! It appears that case [#1390 (review)](https://github.com/Yamato-Security/hayabusa/pull/1390#pullrequestreview-2199635015) is still occurring? Could you confirm?🙏
> 
> > ./hayabusa json-timeline -d ../hayabusa-sample-evtx -o timeline.json -C -w --include-eid 6006
> 
> ```json
> {
>     "Timestamp": "2016-09-20 22:07:23.000 +09:00",
>     "RuleTitle": "Event Log Svc Stopped",
>     "Level": "info",
>     "Computer": "IE10Win7",
>     "Channel": "Sys",
>     "EventID": 6006,
>     "RecordID": 8245,
>     "Details": "-",
>     "ExtraFieldInfo": {
>         "Binary": "010000002EA20000"
>     }
> }
> ```

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for quick fix! I confirmed above case! LGTM!!🚀
```json
{
    "Timestamp": "2013-10-24 01:18:11.000 +09:00",
    "RuleTitle": "Event Log Svc Stopped",
    "Level": "info",
    "Computer": "37L4247D28-05",
    "Channel": "Sys",
    "EventID": 6006,
    "RecordID": 268,
    "Details": {},
    "ExtraFieldInfo": {
        "Binary": 100000000000000
    }
}
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Thanks so much! LGTM!

**Pull request merged**
