### PR TITLE
Refactorer JSON output processing

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- refactored JSON output processing

### refs

https://github.com/Yamato-Security/hayabusa/pull/1146

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Review by fukusuket — CHANGES_REQUESTED** [review]
@hitenkoku 
When I run Integration Test, it seems to panic due to index out of bounds 🤔 
Could you please confirm?
https://github.com/Yamato-Security/hayabusa/actions/runs/6057171234/job/16438022232

**Comment by hitenkoku** [comment]
@fukusuket  I apologize for any inconvenience caused by the incompleteness of the review request. I will fix.

> @hitenkoku When I run Integration Test, it seems to panic due to index out of bounds 🤔 Could you please confirm? https://github.com/Yamato-Security/hayabusa/actions/runs/6057171234/job/16438022232

**Comment by hitenkoku** [comment]
@fukusuket  I fixed error in https://github.com/Yamato-Security/hayabusa/pull/1173/commits/7b0684cdf1ff10d1bc0708cbc864764bfea0eff6 .
Could you please confirm?

**Comment by fukusuket** [comment]
@hitenkoku 
Thank you for quick fix :) I confirmed that panic does not occur in Integration Test!
The following error occurs with the `jq` command, so it seems necessary to escape the control characters? 🤔
```
% ./hayabusa json-timeline -d ../hayabusa-sample-evtx -o results.json -C
% cat results.json | jq
...
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 442509, column 2
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your check.
I fixed special character  in https://github.com/Yamato-Security/hayabusa/pull/1173/commits/02664897f5847269f074112c1034d4f5ec523aec .

Would you please check it?

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you for quick fix! I confirmed that the jq parse error no longer occurs!

Since it seems that line breaks are simply removed, is it better to output it like `\r\n`?[(FYI: AnalysisWithJQ)](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AnalysisWithJQ-Japanese.md#9-powershell%E3%83%AD%E3%82%B0%E3%81%AE%E6%8A%BD%E5%87%BA)
Is [this commit](https://github.com/Yamato-Security/hayabusa/pull/1082/commits/1b5243884def09611d528bb626c396c46016d89c) related to the control character conversion specifications?🤔

(I'm sorry if I misunderstood the current behavior!)

**Comment by hitenkoku** [comment]
@fukusuket Thanks for your comment.
I'm sorry. I forget to fix details newline character processing.

I fixed in https://github.com/Yamato-Security/hayabusa/pull/1173/commits/4d208b0da2396f41443e138f03191a60ceff8699

I confirmed newline control character is outputted.

Would you check it?

```
{
    "Timestamp": "2017-08-30 16:32:13.803 +00:00",
    "Computer": "SEC511",
    "Channel": "PwSh",
    "EventID": 4104,
    "Level": "info",
    "RecordID": 572453,
    "RuleTitle": "PwSh Scriptblock",
    "Details": {
        "ScriptBlock": "function Check-Command($commandline,$minlength,$regexes,$whitelist,$servicecmd){\\r\\n $text=\"\"\\r\\n $base64=\"\"\\r\\n # Check to see if command is whitelisted\\r\\n foreach ($entry in $whitelist) {\\r\\n if ($commandline -Match $entry.regex) {\\r\\n # Command is whitelisted, return nothing\\r\\n return\\r\\n }\\r\\n }\\r\\n #$cmdlength=$commandline.length\\r\\n #if ($cmdlength -gt $minlength){\\r\\n if ($commandline.length -gt $minlength){\\r\\n $text += \" - Long Command Line: greater than $minlength bytes`n\"\\r\\n }\\r\\n $text += (Check-Obfu $commandline)\\r\\n $text += (Check-Regex $commandline $regexes 0)\\r\\n # Check for base64 encoded function, decode and print if found\\r\\n # This section is highly use case specific, other methods of base64 encoding and/or compressing may evade these checks\\r\\n if ($commandline -Match \"\\-enc.*[A-Za-z0-9/+=]{100}\"){\\r\\n $base64= $commandline -Replace \"^.* \\-Enc(odedCommand)? \",\"\"\\r\\n }\\r\\n ElseIf ($commandline -Match \":FromBase64String\\(\"){\\r\\n $base64 = $commandline -Replace \"^.*:FromBase64String\\(\\'*\",\"\"\\r\\n $base64 = $base64 -Replace \"\\'.*$\",\"\"\\r\\n }\\r\\n if ($base64){\\r\\n if ($commandline -Match \"Compression.GzipStream.*Decompress\"){\\r\\n # Metasploit-style compressed and base64-encoded function. Uncompress it.\\r\\n $decoded=New-Object IO.MemoryStream(,[Convert]::FromBase64String($base64))\\r\\n $uncompressed=(New-Object IO.StreamReader(((New-Object IO.Compression.GzipStream($decoded,[IO.Compression.CompressionMode]::Decompress))),[Text.Encoding]::ASCII)).ReadToEnd()\\r\\n $text += \" Decoded/decompressed Base64:\" + $uncompressed \\r\\n $text += \" - Base64-encoded and compressed function`n\"\\r\\n }\\r\\n else{\\r\\n $decoded = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($base64))\\r\\n $text += \" Decoded Base64:\" + $decoded + \"`n\"\\r\\n $text += \" - Base64-encoded function`n\"\\r\\n $text += (Check-Obfu $decoded)\\r\\n $text += (Check-Regex $decoded $regexes 0)\\r\\n #foreach ($regex in $regexes){\\r\\n # if ($regex.Type -eq 0) { # Image Path match\\r\\n # if ($decoded -Match $regex.regex) {\\r\\n # $text += \" - \" + $regex.String + \"`n\"\\r\\n # }\\r\\n # }\\r\\n #}\\r\\n }\\r\\n }\\r\\n if ($text){\\r\\n if ($servicecmd){\\r\\n return \" Service File Name: $commandline`n\" + $text\\r\\n }\\r\\n Else{\\r\\n return \" Command Line: $commandline`n\" + $text\\r\\n }\\r\\n }\\r\\n return \"\"\\r\\n}"
    },
    "ExtraFieldInfo": {
        "MessageNumber": 1,
        "MessageTotal": 1,
        "Path": "C:\\Users\\student\\Desktop\\DeepBlueCLI-master\\DeepBlue-0.2.ps1",
        "ScriptBlockId": "8f18030c-7203-4231-bcc9-48e15b755ba1",
        "ScriptBlockText": "function Check-Command($commandline,$minlength,$regexes,$whitelist,$servicecmd){      $text=\"\"      $base64=\"\"      # Check to see if command is whitelisted      foreach ($entry in $whitelist) {          if ($commandline -Match $entry.regex) {              # Command is whitelisted, return nothing              return          }      }      #$cmdlength=$commandline.length      #if ($cmdlength -gt $minlength){      if ($commandline.length -gt $minlength){          $text += \"   - Long Command Line: greater than $minlength bytes`n\"      }      $text += (Check-Obfu $commandline)      $text += (Check-Regex $commandline $regexes 0)      # Check for base64 encoded function, decode and print if found      # This section is highly use case specific, other methods of base64 encoding and/or compressing may evade these checks      if ($commandline -Match \"\\-enc.*[A-Za-z0-9/+=]{100}\"){          $base64= $commandline -Replace \"^.* \\-Enc(odedCommand)? \",\"\"      }      ElseIf ($commandline -Match \":FromBase64String\\(\"){          $base64 = $commandline -Replace \"^.*:FromBase64String\\(\\'*\",\"\"          $base64 = $base64 -Replace \"\\'.*$\",\"\"      }      if ($base64){          if ($commandline -Match \"Compression.GzipStream.*Decompress\"){              # Metasploit-style compressed and base64-encoded function. Uncompress it.              $decoded=New-Object IO.MemoryStream(,[Convert]::FromBase64String($base64))              $uncompressed=(New-Object IO.StreamReader(((New-Object IO.Compression.GzipStream($decoded,[IO.Compression.CompressionMode]::Decompress))),[Text.Encoding]::ASCII)).ReadToEnd()              $text += \"  Decoded/decompressed Base64:\" + $uncompressed               $text += \"   - Base64-encoded and compressed function`n\"          }          else{              $decoded = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($base64))              $text += \"  Decoded Base64:\" + $decoded + \"`n\"              $text += \"   - Base64-encoded function`n\"              $text += (Check-Obfu $decoded)              $text += (Check-Regex $decoded $regexes 0)              #foreach ($regex in $regexes){              #    if ($regex.Type -eq 0) { # Image Path match              #        if ($decoded -Match $regex.regex) {              #            $text += \"   - \" + $regex.String + \"`n\"              #        }              #    }              #}          }      }      if ($text){          if ($servicecmd){              return \"  Service File Name: $commandline`n\" + $text          }          Else{              return \"  Command Line: $commandline`n\" + $text          }      }      return \"\"  }"
    }
}
```

> @hitenkoku Thank you for quick fix! I confirmed that the jq parse error no longer occurs!
> 
> Since it seems that line breaks are simply removed, is it better to output it like `\r\n`?[(FYI: AnalysisWithJQ)](https://github.com/Yamato-Security/hayabusa/blob/main/doc/AnalysisWithJQ-Japanese.md#9-powershell%E3%83%AD%E3%82%B0%E3%81%AE%E6%8A%BD%E5%87%BA) Is [this commit](https://github.com/Yamato-Security/hayabusa/pull/1082/commits/1b5243884def09611d528bb626c396c46016d89c) related to the control character conversion specifications?🤔
> 
> (I'm sorry if I misunderstood the current behavior!)

**Comment by fukusuket** [comment]
@hitenkoku 
Thank you for quick fix! This is  a difficult refactoring...😵‍💫
I confirmed following command works!

- `cat out.json | jq`
- `cat out.json | jq 'select ((.Details != "-") and (.EventID == 4104))' | jq .Details | jq keys | sort | uniq -c | sort -nr
`
- `cat out.json | jq 'select ( .EventID == 4104 and .Details.ScriptBlock? != "n/a"  and .Computer != "COMPUTER-A.domain.local" ) | .Details.ScriptBlock , "\r\n"' -j | awk '{ gsub(/\\r\\n/,"\r\n"); print; }' | awk '{ gsub(/\\t/, "\t"); print; }' | awk '{ gsub(/\\n/, "\r\n"); print; }' > 4104-PowerShell-Logs.txt`

However, it seems that some of the Details fields get moved compared to `2.8.0`.  Could you please confirm?🙏
[This PR](https://github.com/Yamato-Security/hayabusa/pull/1173/commits/4d208b0da2396f41443e138f03191a60ceff8699)
```
{
    "Timestamp": "2013-10-24 01:16:13.843 +09:00",
    "Computer": "37L4247D28-05",
    "Channel": "Sec",
    "EventID": 4624,
    "Level": "info",
    "RecordID": 2,
    "RuleTitle": "Logon (System) - Bootup",
    "Details": {
        "Type": "SYSTEM",
        "TgtUser": "0 - SYSTEM",
        "SrcComp": "-",
        "SrcIP": "0x3e7",
        "LID": "-"
    },
    "ExtraFieldInfo": {
        "KeyLength": 0,
        "LogonGuid": "00000000-0000-0000-0000-000000000000",
        "ProcessId": 4,
        "ProcessName": "",
        "SubjectLogonId": "0x0",
        "SubjectUserSid": "S-1-0-0",
        "TargetDomainName": "NT AUTHORITY",
        "TargetUserSid": "S-1-5-18"
    }
}
```

2.8.0
```
{
    "Timestamp": "2013-10-24 01:16:13.843 +09:00",
    "Computer": "37L4247D28-05",
    "Channel": "Sec",
    "EventID": 4624,
    "Level": "info",
    "RecordID": 2,
    "RuleTitle": "Logon (System) - Bootup",
    "Details": {
        "Type": "0 - SYSTEM",
        "TgtUser": "SYSTEM",
        "SrcComp": "-",
        "SrcIP": "-",
        "LID": "0x3e7"
    },
    "ExtraFieldInfo": {
        "KeyLength": 0,
        "LogonGuid": "00000000-0000-0000-0000-000000000000",
        "ProcessId": 4,
        "ProcessName": "",
        "SubjectLogonId": "0x0",
        "SubjectUserSid": "S-1-0-0",
        "TargetDomainName": "NT AUTHORITY",
        "TargetUserSid": "S-1-5-18"
    }
}
```

**Comment by hitenkoku** [comment]
@fukusuket  Thank you for your comment.
I was mistaken about the order in which they were extracted by Regex.

I have corrected it at https://github.com/Yamato-Security/hayabusa/pull/1173/commits/274a733711022aff744ae6e9d742286f3e74e3e6. I have confirmed that it looks fine.

I apologize for repeatedly asking you to confirm this.

Please could you confirm this?

```
{
    "Timestamp": "2013-10-24 01:16:13.843 +09:00",
    "Computer": "37L4247D28-05",
    "Channel": "Sec",
    "EventID": 4624,
    "Level": "info",
    "RecordID": 2,
    "RuleTitle": "Logon (System) - Bootup",
    "Details": {
        "TgtUser": "SYSTEM",
        "Type": "0 - SYSTEM",
        "SrcIP": "-",
        "LID": "0x3e7",
        "SrcComp": "-"
    },
    "ExtraFieldInfo": {
        "KeyLength": 0,
        "LogonGuid": "00000000-0000-0000-0000-000000000000",
        "ProcessId": "0x4",
        "ProcessName": "",
        "SubjectLogonId": "0x0",
        "SubjectUserSid": "S-1-0-0",
        "TargetDomainName": "NT AUTHORITY",
        "TargetUserSid": "S-1-5-18"
    }
}
```


> @hitenkoku Thank you for quick fix! This is a difficult refactoring...😵‍💫 I confirmed following command works! (also, the output results were as expected )
> 
> * `cat out.json | jq`
> * `cat out.json | jq 'select ((.Details != "-") and (.EventID == 4104))' | jq .Details | jq keys | sort | uniq -c | sort -nr `
> * `cat out.json | jq 'select ( .EventID == 4104 and .Details.ScriptBlock? != "n/a"  and .Computer != "COMPUTER-A.domain.local" ) | .Details.ScriptBlock , "\r\n"' -j | awk '{ gsub(/\\r\\n/,"\r\n"); print; }' | awk '{ gsub(/\\t/, "\t"); print; }' | awk '{ gsub(/\\n/, "\r\n"); print; }' > 4104-PowerShell-Logs.txt`
> 
> However, it seems that some of the Details fields get moved compared to `2.8.0`. Could you please confirm?🙏 [This PR](https://github.com/Yamato-Security/hayabusa/pull/1173/commits/4d208b0da2396f41443e138f03191a60ceff8699)
> 
> ```
> {
>     "Timestamp": "2013-10-24 01:16:13.843 +09:00",
>     "Computer": "37L4247D28-05",
>     "Channel": "Sec",
>     "EventID": 4624,
>     "Level": "info",
>     "RecordID": 2,
>     "RuleTitle": "Logon (System) - Bootup",
>     "Details": {
>         "Type": "SYSTEM",
>         "TgtUser": "0 - SYSTEM",
>         "SrcComp": "-",
>         "SrcIP": "0x3e7",
>         "LID": "-"
>     },
>     "ExtraFieldInfo": {
>         "KeyLength": 0,
>         "LogonGuid": "00000000-0000-0000-0000-000000000000",
>         "ProcessId": 4,
>         "ProcessName": "",
>         "SubjectLogonId": "0x0",
>         "SubjectUserSid": "S-1-0-0",
>         "TargetDomainName": "NT AUTHORITY",
>         "TargetUserSid": "S-1-5-18"
>     }
> }
> ```
> 
> 2.8.0
> 
> ```
> {
>     "Timestamp": "2013-10-24 01:16:13.843 +09:00",
>     "Computer": "37L4247D28-05",
>     "Channel": "Sec",
>     "EventID": 4624,
>     "Level": "info",
>     "RecordID": 2,
>     "RuleTitle": "Logon (System) - Bootup",
>     "Details": {
>         "Type": "0 - SYSTEM",
>         "TgtUser": "SYSTEM",
>         "SrcComp": "-",
>         "SrcIP": "-",
>         "LID": "0x3e7"
>     },
>     "ExtraFieldInfo": {
>         "KeyLength": 0,
>         "LogonGuid": "00000000-0000-0000-0000-000000000000",
>         "ProcessId": 4,
>         "ProcessName": "",
>         "SubjectLogonId": "0x0",
>         "SubjectUserSid": "S-1-0-0",
>         "TargetDomainName": "NT AUTHORITY",
>         "TargetUserSid": "S-1-5-18"
>     }
> }
> ```

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for fix! All https://github.com/Yamato-Security/hayabusa/pull/1173#issuecomment-1704045529 commands works :) LGTM!!🚀

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks for the PR! When I tested it, after "Scanning finished", i got the error:
`thread 'main' panicked at 'called 'Option::unwrap() on a 'None' value', src¥afterfact.rs:1551:26`

Could you check this?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I will check again.

**Comment by YamatoSecurity** [comment]
@hitenkoku @fukusuket Sorry for the long time to test. I found a rare condition when the `Details` field does not get outputted for some reason. Could you check this? I will DM you logs over slack to test.

2.6.0:
```
./hayabusa-2.6.0-mac-intel json-timeline -L -d ~/Desktop/test -u -D --debug -o json-test-2.6.0.jsonl

...

Saved file: json-test-2.6.0.jsonl (346.0 MB)

Elapsed time: 00:02:13.702
Rule Parse Processing Time: 00:00:02.208
Analysis Processing Time: 00:01:41.901
Output Processing Time: 00:00:29.592

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     4.0 GiB     4.0 GiB     0           4.0 GiB
 committed:     3.9 GiB     4.0 GiB   111.0 GiB  -107.0 GiB                          ok
...
   process: user: 1284.822 s, system: 16.905 s, faults: 0, rss: 1.9 GiB, commit: 3.9 GiB
```

```
cat ../hayabusa/json-test-2.6.0.jsonl | jq 'select (.Timestamp == "2022-10-22 17:26:39.465 +09:00")'

...
{
  "Timestamp": "2022-10-22 17:26:39.465 +09:00",
  "Computer": "-",
  "Channel": "-",
  "EventID": "-",
  "Level": "med",
  "RecordID": "",
  "RuleTitle": "Failed NTLM Logins with Different Accounts from Single Source System",
  "Details": {
    "Workstation": "[condition] count(TargetUserName) by Workstation > 3 in timeframe [result] count:4 TargetUserName:Mekhi.Betts/svc_sql1/adminr/Administrator | timeframe:24h"
  },
  "ExtraFieldInfo": "-"
}
```

2.7.0:

```
Elapsed time: 00:02:15.504
Rule Parse Processing Time: 00:00:03.943
Analysis Processing Time: 00:01:41.070
Output Processing Time: 00:00:30.490

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     3.0 GiB     3.0 GiB     0           3.0 GiB
 committed:     1.8 GiB     3.0 GiB    98.6 GiB   -95.6 GiB                          ok
...
   process: user: 1319.930 s, system: 14.863 s, faults: 0, rss: 1.8 GiB, commit: 1.8 GiB
```


```
cat ../hayabusa/json-test-2.7.0.jsonl | jq 'select (.Timestamp == "2022-10-22 17:26:39.465 +09:00")'
...
{
  "Timestamp": "2022-10-22 17:26:39.465 +09:00",
  "Computer": "-",
  "Channel": "-",
  "EventID": "-",
  "Level": "med",
  "RecordID": "",
  "RuleTitle": "Failed NTLM Logins with Different Accounts from Single Source System",
  "Details": {
    "Workstation": "[condition] count(TargetUserName) by Workstation > 3 in timeframe [result] count:4 TargetUserName:Mekhi.Betts/svc_sql1/adminr/Administrator | timeframe:24h"
  },
  "ExtraFieldInfo": "-"
}
```


2.8.0:

```
Saved file: json-test-2.8.0.jsonl (350.7 MB)

Elapsed time: 00:02:21.188
Rule Parse Processing Time: 00:00:04.086
Analysis Processing Time: 00:01:48.188
Output Processing Time: 00:00:28.913

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     3.0 GiB     3.0 GiB     0           3.0 GiB
 committed:     1.8 GiB     3.0 GiB   112.6 GiB  -109.6 GiB                          ok
...
   process: user: 1334.224 s, system: 17.150 s, faults: 0, rss: 1.8 GiB, commit: 1.8 GiB
```

```
cat ../hayabusa/json-test-2.8.0.jsonl | jq 'select (.Timestamp == "2022-10-22 17:26:39.465 +09:00")'

...
{
  "Timestamp": "2022-10-22 17:26:39.465 +09:00",
  "Computer": "-",
  "Channel": "-",
  "EventID": "-",
  "Level": "med",
  "RecordID": "",
  "RuleTitle": "Failed NTLM Logins with Different Accounts from Single Source System",
  "Details": {
    "Workstation": "[condition] count(TargetUserName) by Workstation > 3 in timeframe [result] count:4 TargetUserName:Mekhi.Betts/svc_sql1/adminr/Administrator | timeframe:24h"
  },
  "ExtraFieldInfo": "-"
}
```


2.9.0 main branch:

```
Saved file: json-test-2.9.0-main.jsonl (350.7 MB)

Elapsed time: 00:02:15.285
Rule Parse Processing Time: 00:00:03.893
Analysis Processing Time: 00:01:41.958
Output Processing Time: 00:00:29.433

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     3.0 GiB     3.0 GiB     0           3.0 GiB
 committed:     1.8 GiB     3.0 GiB   177.9 GiB  -174.9 GiB                          ok
...
   process: user: 1333.188 s, system: 15.701 s, faults: 0, rss: 1.8 GiB, commit: 1.8 GiB
```

```
cat ../hayabusa/json-test-2.9.0-main.jsonl | jq 'select (.Timestamp == "2022-10-22 17:26:39.465 +09:00")'

...
{
  "Timestamp": "2022-10-22 17:26:39.465 +09:00",
  "Computer": "-",
  "Channel": "-",
  "EventID": "-",
  "Level": "med",
  "RecordID": "",
  "RuleTitle": "Failed NTLM Logins with Different Accounts from Single Source System",
  "Details": {
    "Workstation": "[condition] count(TargetUserName) by Workstation > 3 in timeframe [result] count:4 TargetUserName:Mekhi.Betts/svc_sql1/adminr/Administrator | timeframe:24h"
  },
  "ExtraFieldInfo": "-"
}
```

2.9.0 refactored branch:
```
Saved file: json-test-2.9.0-refactor.jsonl (355.4 MB)

Elapsed time: 00:02:14.044
Rule Parse Processing Time: 00:00:03.891
Analysis Processing Time: 00:01:45.533
Output Processing Time: 00:00:24.619

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     3.0 GiB     3.0 GiB     0           3.0 GiB
 committed:     1.7 GiB     3.0 GiB   101.0 GiB   -98.0 GiB                          ok
...
   process: user: 1361.376 s, system: 14.704 s, faults: 0, rss: 2.1 GiB, commit: 1.7 GiB
```

```
cat ../hayabusa/json-test-2.9.0-refactor.jsonl  | jq 'select (.Timestamp == "2022-10-22 17:26:39.465 +09:00")'

...
{
  "Timestamp": "2022-10-22 17:26:39.465 +09:00",
  "Computer": "-",
  "Channel": "-",
  "EventID": "-",
  "Level": "med",
  "RecordID": "",
  "RuleTitle": "Failed NTLM Logins with Different Accounts from Single Source System",
  "ExtraFieldInfo": {}
}

```

As you can see, just in the last refactored branch, there is no `Details` field.

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.

I fixed following problem in https://github.com/Yamato-Security/hayabusa/pull/1173/commits/313ae243c0112552b534865acae8ed160a65de6e .

Could you check it ?

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thank you for your check.
I fixed in following problem.

Could you check it?

```
{
    "Timestamp": "2022-06-17 16:02:48.403 +09:00",
    "Computer": "-",
    "Channel": "-",
    "EventID": "-",
    "Level": "low",
    "RecordID": "",
    "RuleTitle": "Quick Execution of a Series of Suspicious Commands",
    "Details": "[condition] count() by MachineName > 5 in timeframe [result] count:12 MachineName:null timeframe:5m",
    "ExtraFieldInfo": "-",
    "EvtxFile": "-"
}
```

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! I will test it.

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku I checked this and I could not find any parsing errors. LGTM!
It is a little bit slower than CSV output but no much so no problem. Also, memory usage increases compared to the current main branch but does not use more memory than CSV output so LGTM! 
Thank you for this!

**Pull request merged**
