### PR TITLE
modified output csv timeline standard output in color

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Modified csv-timeline stdout color rule 

## Evidence

` ./1271.exe csv-timeline -d ..\hayabusa-sample-evtx\DeepBlueCLI -q -w`

image

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku 
Thanks so much! It looks much better now. Sorry, just one more thing, could you also make the color of the `RuleTitle` the same color as the timestamp and alert level?

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.
I fixed your point out in https://github.com/Yamato-Security/hayabusa/pull/1272/commits/52000b464cbd717c3fc25b1e38743702191c185f.

Colud  you check it?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! The colors are looking better now.
Sorry one more thing, I think it will be easier to read if 1) There is one return(`¥n`) between alerts and 2) There is a return after the field information (%Details%, %ExtraFieldInfo% and %AllFieldInfo%).

For example:
```
2019-06-21 16:35:50.259 +09:00 · alice.insecurebank.local · Sysmon · 11 · crit · 238380 · HackTool - Dumpert Process Dumper Default File
Details:
Proc: C:\Windows\system32\rundll32.exe
PID: 1568
PGUID: ECAD0485-88D6-5D0C-0000-001007AA1D00
ExtraFieldInfo:
CreationUtcTime: 2019-06-21 06:53:03.227
RuleName:
UtcTime: 2019-06-21 07:35:50.727
file_event_win_hktl_dumpert.yml · ../hayabusa-sample-evtx/EVTX-ATTACK-SAMPLES/Credential Access/sysmon_10_11_outlfank_dumpert_and_andrewspecial_memdump.evtx
```

```
2019-06-21 16:35:50.259 +09:00 · alice.insecurebank.local · Sysmon · 11 · crit · 238380 · HackTool - Dumpert Process Dumper Default File
AllFieldInfo:
CreationUtcTime: 2019-06-21 06:53:03.227
Image: C:\Windows\system32\rundll32.exe
ProcessGuid: ECAD0485-88D6-5D0C-0000-001007AA1D00
ProcessId: 1568
RuleName:
TargetFilename: C:\Windows\Temp\dumpert.dmp
UtcTime: 2019-06-21 07:35:50.258
file_event_win_hktl_dumpert.yml · ../hayabusa-sample-evtx/EVTX-ATTACK-SAMPLES/Credential Access/sysmon_10_11_outlfank_dumpert_and_andrewspecial_memdump.evtx
```
where the strings `Details:`, `ExtraFieldInfo` and `AllFieldInfo` are outputted without color.

**Comment by YamatoSecurity** [comment]
@hitenkoku Please ignore my previous comment about displaying the fields on separate lines. I think that will take some time so we can think about that in a future issue.
I change the level colors to green-yellow-orange-red (https://www.color-hex.com/color-palette/93552) as we display field data with blue now so I wanted to use a different color.
I added a space between events.
Just a few things:
+ Events seem to be outputted twice:
Example: 
```
2021-10-20 18:18:07.101 +09:00 · Mimikatz Kirbi File Creation · crit · FS03.offsec.lan · Sysmon · 11 · 69810 · Path: C:\Windows\System32\mimilsa.log ¦  Proc: C:\Windows\system32\lsass.exe ¦  PID: 512 ¦  PGUID: 7CF65FC7-6649-6165-0B00-000000001200· CreationUtcTime: 2021-10-20 09:18:07.101 ¦  RuleName: T1003 ¦  UtcTime: 2021-10-20 09:18:07.101

2021-10-20 18:18:07.101 +09:00 · Mimikatz Kirbi File Creation · crit · FS03.offsec.lan · Sysmon · 11 · 69810 · Path: C:\Windows\System32\mimilsa.log ¦  Proc: C:\Windows\system32\lsass.exe ¦  PID: 512 ¦  PGUID: 7CF65FC7-6649-6165-0B00-000000001200· CreationUtcTime: 2021-10-20 09:18:07.101 ¦  RuleName: T1003 ¦  UtcTime: 2021-10-20 09:18:07.101
```
(Tested with `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -m critical`)

+ ` ¦  ` has two spaces on the right but only one space on the left. Can you make it ` ¦ ` with only one space on the right?

+ There is no space between the `Details` and `ExtraFieldInfo` fields:
```
2021-04-26 18:16:14.119 +09:00 · Sticky Key Like Backdoor Usage - Registry · crit · srvdefender01.offsec.lan · Sysmon · 13 · 32 · EventType: SetValue ¦  TgtObj: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe\Debugger ¦  C: \windows\system32\cmd.exe ¦  Proc: C:\Windows\system32\reg.exe ¦  PID: 4932 ¦  PGUID: 5D63072B-84DE-6086-7B49-000000000C00· RuleName: technique_id=T1183,technique_name=Image File Execution Options Injection ¦  UtcTime: 2021-04-26 09:16:14.116
```
There should be a space between `5D63072B-84DE-6086-7B49-000000000C00` and `·`

**Comment by hitenkoku** [comment]
@YamatoSecurity  Sorry for replying.
I fixed in https://github.com/Yamato-Security/hayabusa/pull/1272/commits/d890afa8dbb3d3f1d29b0fd7cc81d5db2f256c4a to your pointed out problem.

Could you check it?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Thanks so much! LGTM!

**Pull request merged**
