### PR TITLE
fixed non transportable html output

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Embedded image and CSS in html report. 

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much for the quick PR!
When compiling, I get this warning:
Screen Shot 2023-06-03 at 9 42 05 AM

I investigated and it seems that `image-base64` is using `rustc-serialize` which is deprecated and will cause hayabusa to not compile in the future. Can you do this without this crate?

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your confirmation. The target crate is not doing that much processing, so we will see if we can't add the conversion process to base64 in Hayabusa. I would like to avoid modifying the Hayabusa source code as much as possible when sfavicon.png or logo.png changes.

**Comment by hitenkoku** [comment]
@YamatoSecurity Fixes have been completed. I removed image-base64 and prepared a function in htmlreport.rs to do the same.

I have confirmed that the styles and images are output by moving the html file to the desktop.

Would you check it?

**Comment by YamatoSecurity** [comment]
@hitenkoku ありがとうございます！移動しても、無事にCSSとロゴが表示されますが、左右の麻の葉模様の画像が表示されません。
Screen Shot 2023-06-03 at 11 07 35 AM

**Comment by hitenkoku** [comment]
背景の対応を忘れてました……対応します

**Comment by hitenkoku** [comment]
@YamatoSecurity https://github.com/Yamato-Security/hayabusa/pull/1079/commits/e1fca026e3456ed1ae9083f3e955a43812112b58 で背景についてもbase64での埋め込みにするように修正しました。お時間があるときにご確認の程よろしくお願いいたします。

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Thanks so much! LGTM!

**Comment by hitenkoku** [comment]
thank you for your review!
I merge it.

**Pull request merged**
