### PR TITLE
feat: add support for Sigma Correlation Value count

### LINKED ISSUE #1338: Sigma correlations support: Value Count
@fukusuket This one is similar to Event Count by also looks for when fields are different so you probably should do this issue after Event Count.

Value Count sample:
```
title: Many failed logons to different users
id: 0e95725d-7320-415d-80f7-004da920fc12
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d # Logon Failure (User Does Not Exist)
  group-by:
    - Computer
  timespan: 1h
  condition:
    field: TargetUserName
    gte: 10
```

This rule would alert if there are 10 or more **different** target user names within 1 hour for the same `Computer`

It would be similar to `condition: selection | count(TargetUserName) by Computer >= 10`

Here is an example of multiple `group-by`s
```
title: Many failed logons to different users
id: 0e95725d-7320-415d-80f7-004da920fc12
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d # Logon Failure (User Does Not Exist)
  group-by:
    - Computer
    - IpAddress
  timespan: 1h
  condition:
    field: TargetUserName
    gte: 10
```

It would be similar to `condition: selection | count(TargetUserName) by Computer,IpAddress >= 10` , however, it is not possible to specify multiple fields in `by` with `count`. 

This rule would alert if there are 10 or more target user names with the **same** `Computer` and `IpAddress` fields.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #1338 
- Limitations of current implementation is same as https://github.com/Yamato-Security/hayabusa/pull/1357

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Correlation(Valid rule)
#### Correlation rule
#### Agg rule

**Comment by fukusuket** [comment]
### Correlation(Invalid rule)

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
I confirmed that there are no differences in the result files as follows.
#### csv-timeline
```
% ./hayabusa-old csv-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o old.csv
% ./hayabusa-new csv-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o new.csv
% diff new.csv old.csv
%
```

#### json-timeline
```
% ./hayabusa-old json-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o old.json
% ./hayabusa-new json-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o new.json
% diff new.json old.json
%
```
#### Integration-Test
https://github.com/Yamato-Security/hayabusa/actions/runs/9392837467

**Review by hitenkoku — APPROVED** [review]

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
