### PR TITLE
added `computer-metrics` command

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- added `computer-metrics` command.

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
I confirmed that the number of count matches with the following command 💪
```
% ./hayabusa search -r ".*" -d ../hayabusa-sample-evtx -q -o search.csv
...
Total findings: 48262

% ./hayabusa computer-metrics -d ../hayabusa-sample-evtx -q -o metrics.csv
% awk -F"," '{a+=$2} END{print a;}' metrics.csv
48262
```

@hitenkoku @YamatoSecurity 
I have a question! :)
Like the metrics(EID) command, I think it's better to output in descending order of the number of events. What do you think?🤔

**Comment by hitenkoku** [comment]
@fukusuket Thanks for your comment. I agree following suggestion.
I will implement it.

> Like the metrics(EID) command, I think it's better to output in descending order of the number of events. What do you think?🤔

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much for implementing this!
Can you print the help menu when someone types the command without any arguments?

Now:
Screenshot 2023-07-10 at 6 42 00 PM

**Comment by YamatoSecurity** [comment]
@hitenkoku 
Sorry for two small issues:
1) Can you have it not display the following:
```
Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.49%) (Disabled)
Experimental rules: 1973 (53.67%)
Stable rules: 233 (6.34%)
Test rules: 1470 (39.99%)
Unsupported rules: 45 (1.22%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3517
Total enabled detection rules: 3676

Output profile: standard
```
This is because this command does not use any rules so may be confusing.

2) Can you delete the extra white space in the following when printing to standard out.
Before:
```
(省略)
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ IE10Win7                           ┆ 14133  │
╰────────────────────────────────────┴────────╯


Total findings: 65



Elapsed time: 00:00:04.363

user@computer hayabusa %
```
After:
```
(省略)
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ IE10Win7                           ┆ 14133  │
╰────────────────────────────────────┴────────╯

Total findings: 65

Elapsed time: 00:00:04.363

user@computer hayabusa %
```
So just on space between the table and `Total findings` and `Elapsed Time` and the user's prompt.

**Comment by YamatoSecurity** [comment]
@hitenkoku Sorry one more thing. Can you change `Total findings: xxx` to `Total computers: xxx`?

**Comment by YamatoSecurity** [comment]
@hitenkoku 度々ごめんなさい。。
Can you add commas to the numbers when outputting to standard out?
For example, for large files i get `27200598` events but that is hard to read, so it would be better as `27,200,598`
However, for CSV, Excel, etc.. will do number formatting so should be the raw number `27200598` for CSV.
What do you think?

**Comment by hitenkoku** [comment]
@fukusuket  @YamatoSecurity 

Sorry for the late response.
I have corrected all the items you pointed out. Would you please check them?

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
Thank you so much for fix :) I think it's OK, except for following one thing!
https://github.com/Yamato-Security/hayabusa/pull/1127#issuecomment-1628922867 (add commas to the numbers when standard out)

I would appreciate it if you could confirm it🙇

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your comment.

I apologize that forgot following suggestion. I implemented in https://github.com/Yamato-Security/hayabusa/pull/1127/commits/75eee7159e9894ba13bb9f6526e09b804e278bc7

I am sorry for repeating myself. Would you check it?

**Review by fukusuket — APPROVED** [review]
It’s no problem at all! Thank you so much:) LGTM!!🚀

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much for checking!
@hitenkoku Thank you so much for the updates! I just noticed that in the help menu, it says:
```
Filtering:
      --exclude-computer <COMPUTER>  Do not scan these computer names (ex: ComputerA) (ex: ComputerA,ComputerB)
      --include-computer <COMPUTER>  Scan only these computer names (ex: ComputerA) (ex: ComputerA,ComputerB)
```
but can you hide this? 
I tested to see if it works with `./target/release/hayabusa computer-metrics -d ../hayabusa-sample-evtx --include-computer YamatoSecurity` but it still displays all results.
I don't think we need to filter on computers for this command as the user first needs to run the command to know what computer names there are, so it is probably ok not to implement the computer filtering. What do you think?

**Comment by hitenkoku** [comment]
@YamatoSecurity I am very sorry for any inconvenience this may have caused.
The computer-metrics option has been corrected.
Would you please check back with me when you have a moment.

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku No inconvenience! Thank you!
Everything looks great now. Let's merge it.

**Pull request merged**
