### PR TITLE
Waiting for release: 2.6.0 readme update

### PR DESCRIPTION
**Pull request by YamatoSecurity**
Added info about ExtraFieldInfo and am currently updating benchmarks.

### CODE REVIEW

**Comment by kazuminn** [comment]
Probably We need to write about |contains|all in rules readme.
https://github.com/Yamato-Security/hayabusa/issues/1038#issuecomment-1564608614

**Comment by hitenkoku** [comment]
`|contains|all` is rule-related descriptions, which mixes rule and application descriptions in one document.
Therefore, I am against writing it in the hayabusa repository.

I think it is better to put it in https://github.com/Yamato-Security/hayabusa-rules.

**Comment by YamatoSecurity** [comment]
@kazuminn Thanks for letting me know!
I forgot to put it in the hayabusa-rules readme. I will add about `|contains|all` and the new `'all':` that you implemented after we release the next version.

@hitenkoku Thank you for the comment. Yes, let's put it in the rules documentation.

**Review by hitenkoku — APPROVED** [review]
@YamatoSecurity ありがとうございます！確認させていただきました。
問題ないと思います。

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀

**Pull request merged**
