### PR TITLE
Deleted return characters in output of csv timeline command

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- deleted return characters in output in csv-timeline command

- removed multiple blanks in `csv-timeline` command output

## Evidence

- main

```
> ./main.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o main.csv -p super-verbose
> cat main.csv
...
"2020-03-07 22:17:38.534 +09:00","MSEDGEWIN10","Sec","Sec",4698,"info","","","",282588,"Task Created","Zach Mathis","2022/04/08","2022/12/16","stable","Name: \FullPowersTask ¦ Content: <?xml version=""1.0"" encoding=""UTF-16""?>  <Task version=""1.3"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task"">   <RegistrationInfo>   <URI>\FullPowersTask</URI>   </RegistrationInfo>   <Triggers />   <Principals>   <Principal id=""Author"">   <UserId>S-1-5-19</UserId>   <RunLevel>LeastPrivilege</RunLevel>   <RequiredPrivileges>   <Privilege>SeAssignPrimaryTokenPrivilege</Privilege>   <Privilege>SeAuditPrivilege</Privilege>   <Privilege>SeChangeNotifyPrivilege</Privilege>   <Privilege>SeCreateGlobalPrivilege</Privilege>   <Privilege>SeImpersonatePrivilege</Privilege>   <Privilege>SeIncreaseQuotaPrivilege</Privilege>   <Privilege>SeIncreaseWorkingSetPrivilege</Privilege>   </RequiredPrivileges>   </Principal>   </Principals>   <Settings>   <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>   <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>   <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>   <AllowHardTerminate>true</AllowHardTerminate>   <StartWhenAvailable>false</StartWhenAvailable>   <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>   <IdleSettings>   <Duration>PT10M</Duration>   <WaitTimeout>PT1H</WaitTimeout>   <StopOnIdleEnd>true</StopOnIdleEnd>   <RestartOnIdle>false</RestartOnIdle>   </IdleSettings>   <AllowStartOnDemand>true</AllowStartOnDemand>   <Enabled>true</Enabled>   <Hidden>false</Hidden>   <RunOnlyIfIdle>false</RunOnlyIfIdle>   <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>   <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine>   <WakeToRun>false</WakeToRun>   <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>   <Priority>7</Priority>   </Settings>   <Actions Context=""Author"">   <Exec>   <Command>C:\Users\Public\Tools\TokenManip\FullPowers.exe</Command>   <Arguments>-t 4932</Arguments>   </Exec>   </Actions>  </Task> ¦ User: LOCAL SERVICE ¦ LID: 0x3e5","Sec_4698_Info_TaskCreated.yml","..\hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Privilege Escalation\PrivEsc_SeImpersonatePriv_enabled_back_for_upnp_localsvc_4698.evtx","SubjectDomainName: NT AUTHORITY ¦ SubjectLogonId: 0x3e5 ¦ SubjectUserName: LOCAL SERVICE ¦ SubjectUserSid: S-1-5-19 ¦ TaskContent: <?xml version=""1.0"" encoding=""UTF-16""?>  <Task version=""1.3"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task"">    <RegistrationInfo>      <URI>\FullPowersTask</URI>    </RegistrationInfo>    <Triggers />    <Principals>      <Principal id=""Author"">        <UserId>S-1-5-19</UserId>        <RunLevel>LeastPrivilege</RunLevel>        <RequiredPrivileges>          <Privilege>SeAssignPrimaryTokenPrivilege</Privilege>          <Privilege>SeAuditPrivilege</Privilege>          <Privilege>SeChangeNotifyPrivilege</Privilege>          <Privilege>SeCreateGlobalPrivilege</Privilege>          <Privilege>SeImpersonatePrivilege</Privilege>          <Privilege>SeIncreaseQuotaPrivilege</Privilege>          <Privilege>SeIncreaseWorkingSetPrivilege</Privilege>        </RequiredPrivileges>      </Principal>    </Principals>    <Settings>      <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>      <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>      <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>      <AllowHardTerminate>true</AllowHardTerminate>      <StartWhenAvailable>false</StartWhenAvailable>      <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>      <IdleSettings>        <Duration>PT10M</Duration>        <WaitTimeout>PT1H</WaitTimeout>        <StopOnIdleEnd>true</StopOnIdleEnd>        <RestartOnIdle>false</RestartOnIdle>      </IdleSettings>      <AllowStartOnDemand>true</AllowStartOnDemand>      <Enabled>true</Enabled>      <Hidden>false</Hidden>      <RunOnlyIfIdle>false</RunOnlyIfIdle>      <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>      <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine>      <WakeToRun>false</WakeToRun>      <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>      <Priority>7</Priority>    </Settings>    <Actions Context=""Author"">      <Exec>        <Command>C:\Users\Public\Tools\TokenManip\FullPowers.exe</Command>        <Arguments>-t 4932</Arguments>      </Exec>    </Actions>  </Task> ¦ TaskName: \FullPowersTask"
...
```

- this PR
```
> ./1019.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1019.csv -p super-verbose
> cat 1019.csv
...
"2020-03-07 22:17:38.534 +09:00","MSEDGEWIN10","Sec","Sec",4698,"info","","","",282588,"Task Created","Zach Mathis","2022/04/08","2022/12/16","stable","Name: \FullPowersTask ¦ Content: <?xml version=""1.0"" encoding=""UTF-16""?> <Task version=""1.3"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <URI>\FullPowersTask</URI> </RegistrationInfo> <Triggers /> <Principals> <Principal id=""Author""> <UserId>S-1-5-19</UserId> <RunLevel>LeastPrivilege</RunLevel> <RequiredPrivileges> <Privilege>SeAssignPrimaryTokenPrivilege</Privilege> <Privilege>SeAuditPrivilege</Privilege> <Privilege>SeChangeNotifyPrivilege</Privilege> <Privilege>SeCreateGlobalPrivilege</Privilege> <Privilege>SeImpersonatePrivilege</Privilege> <Privilege>SeIncreaseQuotaPrivilege</Privilege> <Privilege>SeIncreaseWorkingSetPrivilege</Privilege> </RequiredPrivileges> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession> <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>PT72H</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>C:\Users\Public\Tools\TokenManip\FullPowers.exe</Command> <Arguments>-t 4932</Arguments> </Exec> </Actions> </Task> ¦ User: LOCAL SERVICE ¦ LID: 0x3e5","Sec_4698_Info_TaskCreated.yml","..\hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Privilege Escalation\PrivEsc_SeImpersonatePriv_enabled_back_for_upnp_localsvc_4698.evtx","SubjectDomainName: NT AUTHORITY ¦ SubjectLogonId: 0x3e5 ¦ SubjectUserName: LOCAL SERVICE ¦ SubjectUserSid: S-1-5-19 ¦ TaskContent: <?xml version=""1.0"" encoding=""UTF-16""?> <Task version=""1.3"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <URI>\FullPowersTask</URI> </RegistrationInfo> <Triggers /> <Principals> <Principal id=""Author""> <UserId>S-1-5-19</UserId> <RunLevel>LeastPrivilege</RunLevel> <RequiredPrivileges> <Privilege>SeAssignPrimaryTokenPrivilege</Privilege> <Privilege>SeAuditPrivilege</Privilege> <Privilege>SeChangeNotifyPrivilege</Privilege> <Privilege>SeCreateGlobalPrivilege</Privilege> <Privilege>SeImpersonatePrivilege</Privilege> <Privilege>SeIncreaseQuotaPrivilege</Privilege> <Privilege>SeIncreaseWorkingSetPrivilege</Privilege> </RequiredPrivileges> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession> <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>PT72H</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>C:\Users\Public\Tools\TokenManip\FullPowers.exe</Command> <Arguments>-t 4932</Arguments> </Exec> </Actions> </Task> ¦ TaskName: \FullPowersTask"

```

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I checked the CSV output and it looks much better now without all of the long spaces.
However, now there are no spaces in between the data in `AccessMask` in standard output:
Screen Shot 2023-05-02 at 7 40 28 AM
Can you check this? It would be better to separate these with spaces.

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thank you for your comment.
I tried typing the following command here and it seems to be displayed separated by spaces, may I know the command you used?

I used the following command to check.

```
 > .\1019.exe csv-timeline -f "..\hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Lateral Movement\LM_5145_Remote_FileCopy.evtx" -p super-verbose -m MEDIUM
```
image

**Comment by YamatoSecurity** [comment]
@hitenkoku Sorry for the late reply.
`./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -p super-verbose`
then search for `937767`.
The spaces are fine when it prints all fields but no spaces when `details` used.

**Comment by hitenkoku** [comment]
Sorry for the late reply.

I have checked and the display of Details you pointed out was outside the scope of this modification.

We are currently checking the issue, so please wait a little longer.

**Comment by YamatoSecurity** [comment]
@hitenkoku I see, if this is caused by a different issue then maybe we can merge this and add spaces in another issue/PR?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thank you!

**Pull request merged**
