### PR TITLE
Add: limit ignore option to regex searches + refact

### PR DESCRIPTION
**Pull request by itiB**
## What Changed

- Reafact search.rs
  - Use create_filter_rule(), extract_search_event_info()
- fix extract_search_event_info()'s channel info's response
- Add: limit ignore option to regex searches

## Evidence

```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx -r ".*mimikatz.*" --ignore-case
error: the following required arguments were not provided:
  --keywords <KEYWORDS>

Usage: hayabusa search --keywords <KEYWORDS> --directory <DIR> --regex <REGEX> --ignore-case
```

Please describe the functionality gained by merging this pull-request and the evidence that the bug has been fixed.

### CODE REVIEW

**Review by hitenkoku — COMMENTED** [review]
@itiB Thank you for pull request.
Am I correct in assuming that if regex is case-insensitive, then the output will be the same?

I checked follow command. 

```
>./1007.exe search -d ..\hayabusa-sample-evtx\ -r ".*mimikatz."
...
Total event log files: 584
Total file size: 137.1 MB

...
Total findings: 35


Elapsed time: 00:00:02.801
```

```
>./1007.exe search -d ..\hayabusa-sample-evtx\ -r ".*mimikatz."
...
Total event log files: 584
Total file size: 137.1 MB

584 / 584 [=================================================================================================] 100.00 % Timestamp ‖ Hostname ‖ Channel ‖ Event ID ‖ Record ID ‖ EventTitle ‖ AllFieldInfo ‖ EvtxFile
...

Total findings: 43


Elapsed time: 00:00:02.855
```

**Comment by itiB** [comment]
@hitenkoku 
Thank you for your feedback! I agree that using `.*[Mm]imikatz.*` would be a better search method if we want to ignore the case of the letters. I also understand that it's expected to have different output counts between `.*Mimikatz.` and `.*mimikatz.*` and it seems appropriate to modify the Regex to `.*[Mm]imikatz.*`

**Comment by hitenkoku** [comment]
@itiB Thank you for your comment!

Since it is a regular expression, it is indeed in the form you described.
I apologize for my lack of understanding.

**Comment by hitenkoku** [comment]
By modifying with clap, the display changes as follows.

Would you please check to make sure everything is OK?

- before(https://github.com/Yamato-Security/hayabusa/pull/1007/commits/7638c3b3c5d4815d00e28a8561b16406c8a495a4)

```
>./1007.exe search -d ..\hayabusa-sample-evtx\ -r ".*Mimikatz." -k "test"

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
  -v, --verbose   Output verbose information

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Filtering:
  -F, --filter <FILTER>      Filter by specific field(s)
  -i, --ignore-case          case-insensitive Search(require kewords option)
  -k, --keywords <KEYWORDS>  Search by keyword(s)
  -r, --regex <REGEX>        Search by regular expression

Output:
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)

General Options:
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
```

- after (https://github.com/Yamato-Security/hayabusa/pull/1007/commits/1f80192262a7e8aad4458b8a9be43dd5e3e198d9)
```
PS >./1007-2.exe search -d ..\hayabusa-sample-evtx\ -r ".*Mimikatz." -k "test"
error: the argument '--regex <regex>' cannot be used with '--keywords <keywords>'

Usage: 1007-2.exe search --directory <DIR> --regex <regex>
```

**Comment by itiB** [comment]
@hitenkoku 
Can you make some PR when you change code?
when we using Github, PR Assinee can't revire to own PR (#1007) ... 

So i commit here directory.
1f80192262a7e8aad4458b8a9be43dd5e3e198d9 looks good.
additionaly we need to fix at  other changes in 4b8e1c4529b8dd26ce335c4c42a06d16430d673d .
I resolved bug that search allowed execution without -r or -k options.

before
```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security
...
```

after
```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx
error: the following required arguments were not provided:
  <--keywords <keywords>|--regex <regex>>

Usage: hayabusa search --directory <DIR> <--keywords <keywords>|--regex <regex>>
```

**Comment by hitenkoku** [comment]
@itiB 

My apologies.
Shall I revert the commits once I have corrected them and create them in another PR?

**Comment by itiB** [comment]
Thank you for you PR @hitenkoku .

@YamatoSecurity @hitenkoku 
Now we have completed all the requested changes, so could you take another look at this pull request and let me know if it's ready to be merged to Main?

**Review by hitenkoku — APPROVED** [review]
LGTM

**Comment by YamatoSecurity** [comment]
@hitenkoku @itiB
Thank you both!
I changed the wording of "Search all events by keyword(s) or regular expressions" to "Search all events by keyword(s) or regular expression" because multiple regex is not allowed.

When i type `./target/release/hayabusa search` before it would show the help menu but now it shows:

```
error: the following required arguments were not provided:
  <--keywords <keywords>|--regex <regex>>
```
Can you have it show the help menu like before?

I now know why KEYWORDS and REGEX was in upper case. I changed it back. Sorry for the trouble.

**Comment by YamatoSecurity** [comment]
@hitenkoku 
One small thing. Could you output the "No matches found." message in red?

**Comment by hitenkoku** [comment]
@YamatoSecurity 
The following requests have been addressed in https://github.com/Yamato-Security/hayabusa/pull/1011 . Would you please check? 

> Can you have it show the help menu like before?
>  One small thing. Could you output the "No matches found." message in red?

**Comment by YamatoSecurity** [comment]
LGTM. Thank you!

**Comment by hitenkoku** [comment]
Changed to draft to prevent merge in wrong order

**Pull request merged**
