### PR TITLE
fix: `|re` matching is not done correctly, so use `is_match` instead of `find_iter`

### LINKED ISSUE #1211: [bug] `|re` modifier rule does not detect logs correctly
**Describe the bug**
`|re` modifier rule not detected correctly.

**Step to Reproduce**
1. Save the following rule as `test.yml`.
```yml
author: Zach Mathis, Fukusuke Takahashi
date: 2023/11/07
modified: 2023/11/07

title: 'PwSh Engine Started'
description: 'Engine state is changed from None to Available.'

id: ac2ae63b-83e6-4d06-aeaf-07409bda92c9
level: informational
status: test
logsource:
    product: windows
    service: powershell
detection:
    selection:
        Channel: 'Windows PowerShell'
        EventID: 400
    filter:
        Data|re: 'NewEngineState'
    condition: selection and filter
falsepositives:
tags:
references:
ruletype: Hayabusa
```
2. `./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r test.yml -D -n -u -w -C`

**Actual behavior**
Number of detections is `0`.

**Expected behavior**
Number of detections is `6`.

**Environment**

- OS: macOS sonoma 14.0
- hayabusa version 2.10.0(I haven't confirmed it, but it's probably an issue that has existed since the first version)

**Additional context**
When I changed the code below to use the [is_match](https://docs.rs/regex/latest/regex/struct.Regex.html#method.is_match) function, it worked correctly, so the code below seems to be the cause🤔
https://github.com/Yamato-Security/hayabusa/blob/91ed9a2da70078c4b4b34dfaca753d48dca6a8f2/src/detections/rule/matchers.rs#L221-L228

also,  If I change the modifier to `|contains` as in the rule below, it will be detected correctly.
```yml
detection:
    selection:
        Channel: 'Windows PowerShell'
        EventID: 400
    filter:
        Data|contains: 'NewEngineState.
    condition: selection and filter
falsepositives:
tags:
references:
ruletype: Hayabusa
```

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Fixed #1211 
   - Changed to use  [is_match](https://docs.rs/regex/latest/regex/struct.Regex.html#method.is_match) instead of [find_iter](https://docs.rs/regex/latest/regex/struct.Regex.html#method.find_iter).

### Enviroment
- OS: macOS Sonoma version 14.0

### Test
I run the steps to reproduce https://github.com/Yamato-Security/hayabusa/issues/1211  and confirmed that 6 cases were detected as follows.
```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r test.yml -w -o out.csv -C -q
...
Results Summary:

Events with hits / Total events: 6 / 47,465 (Data reduction: 47,459 events (99.99%))

Total | Unique detections: 6 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 6 (100.00%) | 1 (100.00%)
```
I would appreciate it if you could review when you have time🙏

### CODE REVIEW

**Review by hitenkoku — APPROVED** [review]
LGTM

**Comment by fukusuket** [comment]
@hitenkoku  Thank you so much for review :) Sorry... There was a regression case, so I'll draft it once...

**Comment by fukusuket** [comment]
The detection result diff of hayabusa-sample-evtx was as follows.
It seems that there is a regression in case [Renamed Exe File](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/hayabusa/sysmon/Sysmon_1_Low_ExeFileRenamed.yml#L5) , so I will check... 
|Rule title|level|main|This PR|
|---|---|---|---|
|[Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/sigma/builtin/powershell/powershell_script/posh_ps_invoke_obfuscation_obfuscated_iex.yml)|high|0|9|
|[Invoke-Obfuscation Via Use Clip - Powershell](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/sigma/builtin/powershell/powershell_script/posh_ps_invoke_obfuscation_via_use_clip.yml#L4)|high|0|1|
|[Potential AD User Enumeration From Non-Machine Account](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/sigma/builtin/security/win_security_ad_user_enumeration.yml#L4)|med|5|17|
|[Powershell Token Obfuscation - Powershell](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/sigma/builtin/powershell/powershell_script/posh_ps_token_obfuscation.yml#L4)|high|0|10|
|[Renamed Exe File](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/hayabusa/sysmon/Sysmon_1_Low_ExeFileRenamed.yml#L5)|low|6|0|

**Comment by fukusuket** [comment]
@hitenkoku  @YamatoSecurity 
The diff in the[Renamed Exe File](https://github.com/Yamato-Security/hayabusa-rules/blob/f779b3415991bd54d53998d3462b37c4b1a6626c/hayabusa/sysmon/Sysmon_1_Low_ExeFileRenamed.yml#L5)  case was not caused by a regression, but by the issue below. 
https://github.com/Yamato-Security/hayabusa-rules/issues/526

Therefore, the difference in the number of detections above does not seem to be a problem :)

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Sorry it took some time. I took some benchmarks and this PR is slightly faster, uses about the same memory and detects more! So LGTM!

**Pull request merged**
