### PR TITLE
enabled recover record option in hayabusa-evtx crate #952

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- enabled recover record option in hayabusa-evtx crate 

## Evidence

https://github.com/Yamato-Security/hayabusa/issues/952#issuecomment-1656720389

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks!
When running on a directory of files I get the following error:
```
thread 'hayabusa-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/detections/rule/selectionnodes.rs:453:36
thread 'hayabusa-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/detections/rule/selectionnodes.rsthread ':hayabusa-thread' panicked at 'called `Option::unwrap()` on a `None` value453', :src/detections/rule/selectionnodes.rs36:
453:36
thread 'hayabusa-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/detections/rule/selectionnodes.rsthread 'thread 'hayabusa-thread:' panicked at '453hayabusa-thread:called `Option::unwrap()` on a `None` value' panicked at '36', called `Option::unwrap()` on a `None` value
src/detections/rule/selectionnodes.rs:453', src/detections/rule/selectionnodes.rs::45336:
36
```

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.

I fixed error in https://github.com/Yamato-Security/hayabusa/pull/1147/commits/95af61baa82b2bdbbf4f84b42aa32327a8f4ed21.

Would you check it?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks! I updated the haybusa-evtx crate and added a short option `-x`.
The previous error we had was fixed but now I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializationError(InvalidEvtxRecordHeaderMagic { magic: [0, 0, 0, 0] })', src/main.rs:1165:43
```
Could you check this?

**Comment by YamatoSecurity** [comment]
By the way, I am not using the `--recover-records` option when this error happens...

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Things are working well for me now. Thank you!
@fukusuket Just in case, could you check this as well?

**Review by fukusuket — APPROVED** [review]
I have verified that there is no difference in the results(hayabusa-sample-evtx) below! LGTM!!🚀
- 2.7.0 : csv-timeline(json-timeline) -p super-verbose
- This PR: csv-timeline(json-timeline) -p super-verbose 
- This PR: csv-timeline(json-timeline) -x -p super-verbose

**Pull request merged**
