### PR TITLE
chg: display `Data` field index string

### LINKED ISSUE #1371: Display `Data` fields in indexed string
@fukusuket Sorry I think this is going to be a difficult issue, but I think you will like it. 😉 Please let me know if you are interested in implementing it.

Right now, all of the unnamed `Data` fields get outputted as the same `Data` so first it is hard to tell which position they are in without looking up the original XML data in Event Viewer, etc... Second, using arrays will cause problems when importing into Elastic and maybe other SIEMs. Third, the position will change depending on whether fields are defined in `Details` or not, making extraction difficult as the index number may change suddenly.

To fix these problems, I want to output the `Data` fields like they are used for when extracting data.

For example: `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r rules/hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml`

This rule uses `details: 'MajorVer: %Data[1]% ¦ BuildNum: %Data[2]%'` so only will get data from the first and second fields.
However, there is more data:
```
        <EventData>
            <Data>10.00.</Data>
            <Data>19044</Data>
            <Data />
            <Data>Multiprocessor Free</Data>
            <Data>0</Data>
        </EventData>
```

Right now, the output looks like this:
```
2016-09-20 22:07:41.000 +09:00 · Computer Startup · info · IE10Win7 · Sys · 6009 · 8273 · MajorVer: 6.01. ¦ BuildNum: 7601 · Data: 17514 ¦ Data: Multiprocessor Free ¦ Data: Service Pack 1
```
But I want to change it to:
```
2016-09-20 22:07:41.000 +09:00 · Computer Startup · info · IE10Win7 · Sys · 6009 · 8273 · MajorVer: 6.01. ¦ BuildNum: 7601 · Data[3]: 17514 ¦ Data[4]: Multiprocessor Free ¦ Data[5]: Service Pack 1
```

For JSON timelines (Example: `./target/release/hayabusa json-timeline -d ../hayabusa-sample-evtx -w -r rules/hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml`)

Before:
```
{
    "Timestamp": "2016-09-20 22:07:41.000 +09:00",
    "RuleTitle": "Computer Startup",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6009,
    "RecordID": 8273,
    "Details": {
        "MajorVer": "6.01.",
        "BuildNum": 7601
    },
    "ExtraFieldInfo": {
        "Data": ["17514", "Multiprocessor Free", "Service Pack 1"]
    }
}
```

After:
```
{
    "Timestamp": "2016-09-20 22:07:41.000 +09:00",
    "RuleTitle": "Computer Startup",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6009,
    "RecordID": 8273,
    "Details": {
        "MajorVer": "6.01.",
        "BuildNum": 7601
    },
    "ExtraFieldInfo": {
        "Data[3]": "17514", 
        "Data[4]": "Multiprocessor Free", 
        "Data[5]": "Service Pack 1"
    }
}
```

What do you think?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1371 

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### csv-timeline

**Comment by fukusuket** [comment]
### json-timeline

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
No differences were found in records other than the `Data` field.
```
% ./hayabusa-old json-timeline -d ../hayabusa-sample-evtx -o old.jsonl -D -n -u -w -q -L
% ./hayabusa-new json-timeline -d ../hayabusa-sample-evtx -o new.jsonl -D -n -u -w -q -L
% diff new.jsonl old.jsonl | grep -v Data  | sort | uniq
---
20742,20746c20742,20746
20757,20766c20757,20766
21637,21638c21637,21638
21961,21962c21961,21962
22870,22872c22870,22872
24,29c24,29
30762,30765c30762,30765
30772c30772
32324,32325c32324,32325
34279,34282c34279,34282
517,520c517,520
540,546c540,546
568,573c568,573
586,590c586,590
799,803c799,803
8231,8286c8231,8286
842,846c842,846
863,864c863,864
904,906c904,906
925c925
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Review by hitenkoku — APPROVED** [review]

**Pull request merged**
