### PR TITLE
Fixed `-h, --help` option is being displayed multiple times

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Fixed `-h, --help` option is being displayed multiple times

### CODE REVIEW

**Review by fukusuket — APPROVED** [review]
I confirmed all command help and integration-test passed! LGTM!!🚀
https://github.com/Yamato-Security/hayabusa/actions/runs/8312617598

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! I confirmed only one `-h` now but it seems that options under `General Options` are out of alphabetical order. Can you change to the following for `csv-timeline` and `json-timeline`:

```
General Options:
  -C, --clobber                        Overwrite files when saving
  -h, --help                           Show the help menu
  -s, --low-memory-mode                Scan with the minimal amount of memory by not sorting events
  -J, --JSON-input                     Scan JSON formatted logs instead of .evtx (.json or .jsonl)
  -w, --no-wizard                      Do not ask questions. Scan for all events and alerts
  -Q, --quiet-errors                   Quiet errors mode: do not save error logs
  -r, --rules <DIR/FILE>               Specify a custom rule directory or file (default: ./rules)
  -x, --recover-records                Carve evtx records from slack space (default: disabled)
  -c, --rules-config <DIR>             Specify custom rule config directory (default: ./rules/config)
```
to
```
General Options:
  -C, --clobber                        Overwrite files when saving
  -h, --help                           Show the help menu
  -J, --JSON-input                     Scan JSON formatted logs instead of .evtx (.json or .jsonl)
  -s, --low-memory-mode                Scan with the minimal amount of memory by not sorting events
  -w, --no-wizard                      Do not ask questions. Scan for all events and alerts
  -Q, --quiet-errors                   Quiet errors mode: do not save error logs
  -x, --recover-records                Carve evtx records from slack space (default: disabled)
  -r, --rules <DIR/FILE>               Specify a custom rule directory or file (default: ./rules)
  -c, --rules-config <DIR>             Specify custom rule config directory (default: ./rules/config)
```

**Comment by hitenkoku** [comment]
@YamatoSecurity I fixed following problems in https://github.com/Yamato-Security/hayabusa/pull/1316/commits/c7f96d5f71a54301f8ed38a8328d8d7aac5e35f6.
Would you recheck it?

>  Thanks so much! I confirmed only one `-h` now but it seems that options under `General Options` are out of alphabetical order. Can you change to the following for `csv-timeline` and `json-timeline`:
> 
> ```
> General Options:
>   -C, --clobber                        Overwrite files when saving
>   -h, --help                           Show the help menu
>   -s, --low-memory-mode                Scan with the minimal amount of memory by not sorting events
>   -J, --JSON-input                     Scan JSON formatted logs instead of .evtx (.json or .jsonl)
>   -w, --no-wizard                      Do not ask questions. Scan for all events and alerts
>   -Q, --quiet-errors                   Quiet errors mode: do not save error logs
>   -r, --rules <DIR/FILE>               Specify a custom rule directory or file (default: ./rules)
>   -x, --recover-records                Carve evtx records from slack space (default: disabled)
>   -c, --rules-config <DIR>             Specify custom rule config directory (default: ./rules/config)
> ```
> 
> to
> 
> ```
> General Options:
>   -C, --clobber                        Overwrite files when saving
>   -h, --help                           Show the help menu
>   -J, --JSON-input                     Scan JSON formatted logs instead of .evtx (.json or .jsonl)
>   -s, --low-memory-mode                Scan with the minimal amount of memory by not sorting events
>   -w, --no-wizard                      Do not ask questions. Scan for all events and alerts
>   -Q, --quiet-errors                   Quiet errors mode: do not save error logs
>   -x, --recover-records                Carve evtx records from slack space (default: disabled)
>   -r, --rules <DIR/FILE>               Specify a custom rule directory or file (default: ./rules)
>   -c, --rules-config <DIR>             Specify custom rule config directory (default: ./rules/config)
> ```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Perfect! Thanks so much!

**Pull request merged**
