### PR TITLE
perf: Reduced memory usage by removing unnecessary regex compilation

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
Reduced memory usage by removing unneeded unnecessary compilations.
Fixed not to compile regex for string matching of the following `value-modifiers` as they do not currently require regex.
- `|contains`
- `|contains|all`

### Additional informarion
Current [hayabusa_rule/converter.py](https://github.com/Yamato-Security/hayabusa-rules/blob/main/tools/sigmac/README-Japanese.md), the `value-modifier` below is internally converted to a `wildcard pattern` as follows.
- `key|contains: hoge` -> `key: *hoge*`

In case above conversion pattern, Hayabusa will not compile the regex due to #894(So it uses less memory)

However, in the [logsource_mapping.py currently under development](https://github.com/Yamato-Security/hayabusa-rules/pull/396), `value-modifier` is not converted and is output as is.
Therefore it uses more memory because Hayabusa compile regex.

This PR removes unnecessary regex compilation and reduces memory usage when rules are converted by a new conversion script (`logsource_mapping.py`).

I would appreciate it if you could review when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
## Evidence
### Environment 
- OS: macOS montery version 13.1
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8

## Test prerequisite
Use the converted rules in the `logssource_mapping.py` of the branch below.
- https://github.com/Yamato-Security/hayabusa-rules/pull/396

Because this PR does not improve the speed of `wildcard patterns without value-modifiers`

## Test1(hayabusa-sample-evtx)
main
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.5.0-all-platforms % ./hayabusa-2.5.0-mac-arm csv-timeline -d ../hayabusa-sample-evtx --debug -D -u -n -o 3.csv -r ./converted_rules
...
Excluded rules: 30

Deprecated rules: 162 (4.46%)
Experimental rules: 1861 (51.22%)
Stable rules: 103 (2.84%)
Test rules: 1464 (40.30%)
Unsupported rules: 43 (1.18%)

Sigma rules: 3633
Total enabled detection rules: 3633
...
Events with hits / Total events: 5,714 / 47,465 (Data reduction: 41,751 events (87.96%))

Total | Unique detections: 8,054 | 564
Total | Unique critical detections: 53 (0.66%) | 21 (3.72%)
Total | Unique high detections: 5,472 (67.94%) | 280 (49.65%)
Total | Unique medium detections: 1,262 (15.67%) | 183 (32.45%)
Total | Unique low detections: 1,237 (15.36%) | 75 (13.30%)
Total | Unique informational detections: 30 (0.37%) | 5 (0.89%)
...
Elapsed time: 00:00:08.336
Rule Parse Processing Time: 00:00:01.429
Analysis Processing Time: 00:00:06.774
Output Processing Time: 00:00:00.131

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:     1.9 GiB     2.0 GiB     5.8 GiB    -3.8 GiB                          ok
```

This PR
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.5.0-all-platforms % ./hayabusa csv-timeline -d ../hayabusa-sample-evtx --debug -D -u -n -o 5.csv -r ./converted_rules
...
Excluded rules: 30

Deprecated rules: 162 (4.46%)
Experimental rules: 1861 (51.22%)
Stable rules: 103 (2.84%)
Test rules: 1464 (40.30%)
Unsupported rules: 43 (1.18%)

Sigma rules: 3633
Total enabled detection rules: 3633
...
Events with hits / Total events: 5,714 / 47,465 (Data reduction: 41,751 events (87.96%))

Total | Unique detections: 8,054 | 564
Total | Unique critical detections: 53 (0.66%) | 21 (3.72%)
Total | Unique high detections: 5,472 (67.94%) | 280 (49.65%)
Total | Unique medium detections: 1,262 (15.67%) | 183 (32.45%)
Total | Unique low detections: 1,237 (15.36%) | 75 (13.30%)
Total | Unique informational detections: 30 (0.37%) | 5 (0.89%)
...
Elapsed time: 00:00:07.700
Rule Parse Processing Time: 00:00:00.942
Analysis Processing Time: 00:00:06.658
Output Processing Time: 00:00:00.099

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     1.0 GiB     1.0 GiB     0           1.0 GiB
 committed:     1.0 GiB     1.0 GiB     5.2 GiB    -4.2 GiB                          ok
```

## Test2(all-evtx.tgz(6.1GB))
main
```
fukusuke@fukusukenoAir hayabusa-2.5.0-all-platforms % ./hayabusa-2.5.0-mac-arm csv-timeline -d ../all-evtx --debug -D -u -n -o 1.csv -r ./converted_rules
...
Excluded rules: 30

Deprecated rules: 162 (4.46%)
Experimental rules: 1861 (51.22%)
Stable rules: 103 (2.84%)
Test rules: 1464 (40.30%)
Unsupported rules: 43 (1.18%)

Sigma rules: 3633
Total enabled detection rules: 3633
...
Events with hits / Total events: 21,229 / 4,817,181 (Data reduction: 4,795,952 events (99.56%))

Total | Unique detections: 22,810 | 98
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 11,665 (51.14%) | 15 (15.31%)
Total | Unique medium detections: 4,641 (20.35%) | 33 (33.67%)
Total | Unique low detections: 5,253 (23.03%) | 41 (41.84%)
Total | Unique informational detections: 1,251 (5.48%) | 9 (9.18%)
...
Elapsed time: 00:06:23.844
Rule Parse Processing Time: 00:00:01.438
Analysis Processing Time: 00:06:22.069
Output Processing Time: 00:00:00.336

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:     1.9 GiB     2.0 GiB   207.7 GiB  -205.7 GiB                          ok
```

This PR
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.5.0-all-platforms % ./hayabusa csv-timeline -d ../all-evtx --debug -D -u -n -o new.csv -r ./converted_rules
...
Excluded rules: 30

Deprecated rules: 162 (4.46%)
Experimental rules: 1861 (51.22%)
Stable rules: 103 (2.84%)
Test rules: 1464 (40.30%)
Unsupported rules: 43 (1.18%)

Sigma rules: 3633
Total enabled detection rules: 3633
...
Events with hits / Total events: 21,229 / 4,817,181 (Data reduction: 4,795,952 events (99.56%))

Total | Unique detections: 22,810 | 98
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 11,665 (51.14%) | 15 (15.31%)
Total | Unique medium detections: 4,641 (20.35%) | 33 (33.67%)
Total | Unique low detections: 5,253 (23.03%) | 41 (41.84%)
Total | Unique informational detections: 1,251 (5.48%) | 9 (9.18%)
...
Elapsed time: 00:06:17.504
Rule Parse Processing Time: 00:00:01.089
Analysis Processing Time: 00:06:16.212
Output Processing Time: 00:00:00.202

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     1.0 GiB     1.0 GiB     0           1.0 GiB
 committed:     1.0 GiB     1.0 GiB   210.2 GiB  -209.2 GiB                          ok
```

**Review by hitenkoku — APPROVED** [review]
Thanks for pull request.
I confirmed code.
LGTM.

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!
I think this should be good to merge but let me test on another machine just in case. I don't think the machine I am using now is good for benchmarks..

2.5.0 and current rules:
`./hayabusa-2.5.0-mac-intel  csv-timeline -d ../hayabusa-sample-evtx -n -D -u --debug -o xx.csv`
1.9
2.9
4.9
2.9
1.9

(Sorry I only testing memory usage at first)

This branch and current rules:
`./target/release/hayabusa  csv-timeline -d ../hayabusa-sample-evtx -n -D -u --debug -o xx.csv`
5.9
1.9
3.9
1.9
1.9

For some reason, the memory usage varies wildly with the current rules.

2.5.0 and new rules:
`./hayabusa-2.5.0-mac-intel  csv-timeline -d ../hayabusa-sample-evtx -n -D -u --debug -r ../hayabusa-rules/tools/sigmac/converted_rules -o xx.csv`
1.9GB 15.8s
1.9GB 15.4s
1.9GB 15.3s
1.9GB 15.2s
1.9GB 15.3s

this branch and new rules:
`./target/release/hayabusa  csv-timeline -d ../hayabusa-sample-evtx -n -D -u --debug -r ../hayabusa-rules/tools/sigmac/converted_rules -o xx.csv`
3.9GB 13.5s
4.9GB 13.6s
3.9GB 13.5s
4.9GB 13.7s
1.9GB 13.5s

This is also strange. 2.5.0 is stable and always returns the same memory usage.
This branch is faster but seems to use more memory on average on my intel mac. (?.?) 
I will do more testing on an intel windows machine later.
This is also not a great benchmark as I'm only testing against the sample evtx files.

**Comment by fukusuket** [comment]
@hitenkoku @YamatoSecurity Thank you so much for review and benchmarking 🙇

This branch implementation simply removed the unnecessary regex compilation process, so it's strange that there is a pattern of memory usage going up(I think it does not change depending on the CPU architecture🤔)  I'll check on another Windows machine as well💪

**Comment by fukusuket** [comment]
I tried to get the benchmark in the following environment :)

## Benchmark
### Environment
|OS | Memory | CPU core| CPU arch | Hard info|
|-- | ---- | ---- | ---- | -- |
|Windows10|16GB|8|Intel(R) Core(TM) i7| mouse LAPTOP|
|macOS Ventura|8GB|8|Apple M1| MacBook Air |

### Data
[all-evtx.tgz(6.1GB)](https://github.com/NextronSystems/evtx-baseline/releases/tag/v0.7)

### Windows10
|Ver |Rule| Elasped Time| Memory(peak/reserved) | Total/ Unique detections | Result file size|
|-- | ---- | -- | ---- | ---- |---- |
|2.5.0 | new | 00:10:47.420 | 2.0 GiB | 22,810 / 98 | 10643851 |
|2.5.0 | old | 00:11:21.300 | 1.0 GiB | 22,810 / 98 | 10643851 |
|This PR| new | 00:10:48.114 | 1.0 GiB | 22,810 / 98 | 10643851 |
|This PR| old | 00:11:23.649 | 1.0 GiB | 22,810 / 98 | 10643851 |


### macOS Ventura
|Ver |Rule| Elasped Time| Memory(peak/reserved) | Total/ Unique detections | Result file size|
|-- | ---- | -- | ---- | ---- |---- |
|2.5.0 | new | 00:06:15.362 | 2.0 GiB | 22,810 / 98 | 10643851 |
|2.5.0 | old | 00:06:50.852 | 1.0 GiB | 22,810 / 98 | 10643851 |
|This PR| new | 00:06:25.420 | 1.0 GiB | 22,810 / 98 | 10643851 |
|This PR| old | 00:06:52.355 | 1.0 GiB | 22,810 / 98 | 10643851 |

Sorry for the lack of explanation🙇 This PR can reduce memory usage, but I don't think it will improve speed.
The speed improvement is due to new rules which was converted by `logsource_mapping.py`.

**Comment by fukusuket** [comment]
I also got the benchmark below. :) Attached is the benchmark result.
[benchmark-result2.zip](https://github.com/Yamato-Security/hayabusa/files/11471185/benchmark-result2.zip)

## Benchmark2

### Data
[hayabusa-sample-evtx(130MB)](https://github.com/Yamato-Security/hayabusa-sample-evtx.git)

### Windows10
|Ver |Rule| Elasped Time| Memory(peak/reserved) | Total/ Unique detections | Result file size|
|-- | ---- | -- | ---- | ---- |---- |
|2.5.0 | new | 00:00:15.686 | 2.0 GiB | 8,054 / 564 | 4388796 |
|2.5.0 | old | 00:00:13.155 | 1.0 GiB | 8,035 / 559 | 4378169 |
|This PR| new | 00:00:14.399 | 1.0 GiB | 8,054 / 564 | 4388804 |
|This PR| old | 00:00:12.887 | 1.0 GiB | 8,035 / 559 | 4378177 |


### macOS Ventura
|Ver |Rule| Elasped Time| Memory(peak/reserved) | Total/ Unique detections | Result file size|
|-- | ---- | -- | ---- | ---- |---- |
|2.5.0 | new | 00:00:08.542 | 2.0 GiB | 8,054 / 564 | 4388796 |
|2.5.0 | old | 00:00:07.518 | 1.0 GiB | 8,035 / 559 | 4378169 |
|This PR| new | 00:00:07.894 | 1.0 GiB | 8,054 / 564 | 4388804 |
|This PR| old | 00:00:07.445 | 1.0 GiB | 8,035 / 559 | 4378177 |

**Review by YamatoSecurity — APPROVED** [review]
Ok, LGTM!
Let's merge it. I updated the changelogs.
Thanks so much!

**Pull request merged**
