### PR TITLE
added filter on tags

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Added `--tags` option to `csv-timeline` and `json-timeline` commands to allow scanning only for rules with the specified `tags` field.

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

- This PR(no tags)

```
> ./1108.exe csv-timeline -d ../hayabusa-sample-evtx -o no-tags.csv --debug -q -p verbose
...
Results Summary:
Events with hits / Total events: 19,604 / 47,472 (Data reduction: 27,868 events (58.70%))

Total | Unique detections: 32,062 | 629
Total | Unique critical detections: 56 (0.17%) | 22 (3.50%)
Total | Unique high detections: 6,042 (18.84%) | 279 (44.36%)
Total | Unique medium detections: 1,894 (5.91%) | 205 (32.59%)
Total | Unique low detections: 6,002 (18.72%) | 70 (11.13%)
Total | Unique informational detections: 18,068 (56.35%) | 53 (8.43%)

Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,652), medium: 2021-04-22 (199), low: 2016-09-20 (3,708), informational: 2016-08-19 (2,104)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (8), IEWIN7 (3), FS03.offsec.lan (2), IE10Win7 (2), rootdc1.offsec.lan (2)
high: MSEDGEWIN10 (118), IEWIN7 (70), FS03.offsec.lan (30), fs03vuln.offsec.lan (29), IE10Win7 (24)
medium: MSEDGEWIN10 (77), IEWIN7 (48), FS03.offsec.lan (21), fs03vuln.offsec.lan (19), srvdefender01.offsec.lan (16)
low: MSEDGEWIN10 (32), FS03.offsec.lan (17), IEWIN7 (15), fs03vuln.offsec.lan (15), fs01.offsec.lan (11)
informational: IEWIN7 (18), MSEDGEWIN10 (18), fs01.offsec.lan (15), PC01.example.corp (14), FS03.offsec.lan (13)

...
Saved file: 1108-no-tags.csv (36.8 MB)

Elapsed time: 00:00:09.959
Rule Parse Processing Time: 00:00:02.797
Analysis Processing Time: 00:00:06.688
Output Processing Time: 00:00:00.473

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:   820.7 MiB     1.3 GiB   916.7 MiB   493.6 MiB
     reset:     0
    purged:   444.7 MiB
   touched:    64.2 KiB     1.2 MiB     3.5 GiB    -3.5 GiB                          ok
  segments:    16          20           9          11                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0          32.7 Ki    -32.7 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     7.2 Ki
    resets:     0
    purges:   305
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     9.987 s
   process: user: 28.781 s, system: 1.437 s, faults: 254331, rss: 700.2 MiB, commit: 799.8 MiB
```


- this PR (with tags)

output csv: [1108-persistence-lm.csv](https://github.com/Yamato-Security/hayabusa/files/11882244/1108-persistence-lm.csv)


```
 .\1108.exe csv-timeline -d ..\hayabusa-sample-evtx\ --debug -o 1108-persistence-lm.csv -p verbose --tags attack.persistence,attack.lateral_movement
...
Results Summary:
Events with hits / Total events: 4,869 / 47,472 (Data reduction: 42,603 events (89.74%))

Total | Unique detections: 5,829 | 142
Total | Unique critical detections: 23 (0.39%) | 8 (5.63%)
Total | Unique high detections: 4,652 (79.81%) | 68 (47.89%)
Total | Unique medium detections: 252 (4.32%) | 45 (31.69%)
Total | Unique low detections: 71 (1.22%) | 13 (9.15%)
Total | Unique informational detections: 831 (14.26%) | 8 (5.63%)

Dates with most total detections:
critical: 2019-07-19 (11), high: 2016-09-20 (3,591), medium: 2021-12-12 (42), low: 2020-07-12 (17), informational: 2019-05-01 (294)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (2), srvdefender01.offsec.lan (2), IEWIN7 (1), Isaac (1), IE10Win7 (1)
high: MSEDGEWIN10 (21), IEWIN7 (15), rootdc1.offsec.lan (7), PC01.example.corp (7), fs03vuln.offsec.lan (6)
medium: MSEDGEWIN10 (16), PC01.example.corp (7), IEWIN7 (6), PC04.example.corp (4), fs01.offsec.lan (4)
low: FS03.offsec.lan (5), MSEDGEWIN10 (5), jump01.offsec.lan (4), fs01.offsec.lan (3), IEWIN7 (2)
informational: FS03.offsec.lan (4), fs01.offsec.lan (4), IEWIN7 (3), jump01.offsec.lan (3), rootdc1.offsec.lan (3)

...
Saved file: 1108-persistence-lm.csv (4.2 MB)

Elapsed time: 00:00:02.658
Rule Parse Processing Time: 00:00:00.590
Analysis Processing Time: 00:00:01.979
Output Processing Time: 00:00:00.087

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:   318.4 MiB   763.3 MiB   533.3 MiB   230.0 MiB
     reset:     0
    purged:   237.5 MiB
   touched:    64.2 KiB   449.7 KiB     1.1 GiB    -1.1 GiB                          ok
  segments:     5           7           3           4                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0          13.7 Ki    -13.7 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     5.0 Ki
    resets:     0
    purges:   164
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     2.661 s
   process: user: 2.078 s, system: 0.593 s, faults: 123943, rss: 230.2 MiB, commit: 322.4 MiB
```

**Review by YamatoSecurity — APPROVED** [review]
Thanks so much!
LGTM! I just shortened the description so to avoid word wrapping with small terminals

**Review by fukusuket — APPROVED** [review]
I confirmed that tag filter can be done with json-timeline/csv-timeline :) LGTM!!🚀

**Comment by hitenkoku** [comment]
Thanks for your quick review.
I will merge it.

**Pull request merged**
