### PR TITLE
added ExtraFieldInfo profile field

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Added ExtraFieldInfo profile field

## Additional Information

`%ExtraFieldInfo%` is a field from `%AllFieldInfo%` without the values already contained in `%Details%`.

e.g.

`%AllFieldInfoDetails%` -> `Channel: test ¦ Test: 123 ¦ Test2: 456`
`%Details%` -> `Channel: test ¦ Hoge: 123`

`%ExtraFieldInfo` -> `Test2: 456`  (123 is Hoge value in `%Details%`)

I would appreciate it if you could review when you have time

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Settings

`configs/profiles.yaml`

```
...
#Verbose profile plus all field information. (Warning: this will more than double the output file size!)
super-verbose:
    Timestamp: "%Timestamp%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    Provider: "%Provider%"
    EventID: "%EventID%"
    Level: "%Level%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    RuleTitle: "%RuleTitle%"
    RuleAuthor: "%RuleAuthor%"
    RuleCreationDate: "%RuleCreationDate%"
    RuleModifiedDate: "%RuleModifiedDate%"
    Status: "%Status%"
    Details: "%Details%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"
    AllFieldInfo: "%AllFieldInfo%"

#Verbose profile plus all field information. (Warning: this will more than double the output file size!)
super-verbose2:
    Timestamp: "%Timestamp%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    Provider: "%Provider%"
    EventID: "%EventID%"
    Level: "%Level%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    RuleTitle: "%RuleTitle%"
    RuleAuthor: "%RuleAuthor%"
    RuleCreationDate: "%RuleCreationDate%"
    RuleModifiedDate: "%RuleModifiedDate%"
    Status: "%Status%"
    Details: "%Details%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"
    ExtraFieldInfo: "%ExtraFieldInfo%"
...
```

## Test1

- AllFieldInfo field
```
 >./900.exe csv-timeline -d ..\hayabusa-sample-evtx\ --debug -p super-verbose -D -u -n -o superverbose-test1.csv
...
Events with hits / Total events: 20,364 / 47,472 (Data reduction: 27,108 events (57.10%))

Total | Unique detections: 33,707 | 671
Total | Unique critical detections: 57 (0.17%) | 22 (3.28%)
Total | Unique high detections: 6,182 (18.34%) | 294 (43.82%)
Total | Unique medium detections: 1,996 (5.92%) | 210 (31.30%)
Total | Unique low detections: 6,534 (19.38%) | 87 (12.97%)
Total | Unique informational detections: 18,938 (56.18%) | 58 (8.64%)
...
Saved file: superverbose-test1.csv (50.7 MB)
Elapsed time: 00:00:07.547
Rule Parse Processing Time: 00:00:01.071
Analysis Processing Time: 00:00:05.843
Output Processing Time: 00:00:00.631

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:   877.5 MiB     1.3 GiB   872.2 MiB   553.0 MiB
     reset:     0
    purged:   369.2 MiB
   touched:    64.2 KiB     1.1 MiB     3.5 GiB    -3.5 GiB                          ok
  segments:    16          18           8          10                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0          34.1 Ki    -34.1 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     7.3 Ki
    resets:     0
    purges:   330
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     7.551 s
   process: user: 27.593 s, system: 0.703 s, faults: 265034, rss: 726.0 MiB, commit: 846.4 MiB
```

- This PR(ExtraFieldInfo)
```
>./900.exe csv-timeline -d ..\hayabusa-sample-evtx\ --debug -p super-verbose2 -D -u -n -o superverbose2-test1.csv
...
Events with hits / Total events: 20,364 / 47,472 (Data reduction: 27,108 events (57.10%))

Total | Unique detections: 33,707 | 671
Total | Unique critical detections: 57 (0.17%) | 22 (3.28%)
Total | Unique high detections: 6,182 (18.34%) | 294 (43.82%)
Total | Unique medium detections: 1,996 (5.92%) | 210 (31.30%)
Total | Unique low detections: 6,534 (19.38%) | 87 (12.97%)
Total | Unique informational detections: 18,938 (56.18%) | 58 (8.64%)
...
Saved file: superverbose2-test1.csv (40.2 MB)
Elapsed time: 00:00:07.486
Rule Parse Processing Time: 00:00:01.034
Analysis Processing Time: 00:00:05.868
Output Processing Time: 00:00:00.582

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:   832.3 MiB     1.3 GiB   907.0 MiB   506.8 MiB
     reset:     0
    purged:   408.6 MiB
   touched:    64.2 KiB     1.1 MiB     3.5 GiB    -3.5 GiB                          ok
  segments:    16          18           8          10                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0          34.1 Ki    -34.1 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     7.1 Ki
    resets:     0
    purges:   342
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     7.490 s
   process: user: 28.468 s, system: 0.453 s, faults: 263557, rss: 719.9 MiB, commit: 832.4 MiB
```

## Test2(all-evtx(6.1GB))

- AllFieldInfo
```
 >./900.exe csv-timeline -d ..\all-evtx\ --debug -p super-verbose -D -u -n -o superverbose-test2.csv
...
Events with hits / Total events: 4,519,803 / 4,817,181 (Data reduction: 297,378 events (6.17%))

Total | Unique detections: 4,620,090 | 175
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 11,717 (0.25%) | 19 (10.86%)
Total | Unique medium detections: 14,280 (0.31%) | 44 (25.14%)
Total | Unique low detections: 1,057,564 (22.89%) | 54 (30.86%)
Total | Unique informational detections: 3,536,529 (76.55%) | 58 (33.14%)
...
Saved file: superverbose-test2.csv (5.4 GB)
Elapsed time: 00:06:56.932
Rule Parse Processing Time: 00:00:01.216
Analysis Processing Time: 00:04:19.995
Output Processing Time: 00:02:35.717

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:    22.0 GiB    22.0 GiB     0          22.0 GiB
 committed:    23.2 GiB    68.3 GiB    48.0 GiB    20.3 GiB
     reset:    82.9 MiB
    purged:    20.4 GiB
   touched:    64.2 KiB    15.1 MiB    54.4 GiB   -54.4 GiB                          ok
  segments:    16         242         232          10                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0         741.5 Ki   -741.5 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   481.7 Ki
    resets:     2
    purges:    12.0 Ki
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:   416.950 s
   process: user: 2450.453 s, system: 44.718 s, faults: 16392474, rss: 11.8 GiB, commit: 20.5 GiB
...
```

- ExtraFieldInfo
```
 >./900.exe csv-timeline -d ..\all-evtx\ --debug -p super-verbose2 -D -u -n -o superverbose-test2.csv
...
Events with hits / Total events: 4,519,803 / 4,817,181 (Data reduction: 297,378 events (6.17%))

Total | Unique detections: 4,620,090 | 175
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 11,717 (0.25%) | 19 (10.86%)
Total | Unique medium detections: 14,280 (0.31%) | 44 (25.14%)
Total | Unique low detections: 1,057,564 (22.89%) | 54 (30.86%)
Total | Unique informational detections: 3,536,529 (76.55%) | 58 (33.14%)
...
Saved file: superverbose2-test2.csv (4.0 GB)
Elapsed time: 00:06:25.559
Rule Parse Processing Time: 00:00:02.432
Analysis Processing Time: 00:04:21.907
Output Processing Time: 00:02:01.215

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:    20.0 GiB    20.0 GiB     0          20.0 GiB
 committed:    21.4 GiB    65.8 GiB    47.2 GiB    18.6 GiB
     reset:    82.9 MiB
    purged:    20.4 GiB
   touched:    64.2 KiB    15.1 MiB    54.4 GiB   -54.4 GiB                          ok
  segments:    16         242         232          10                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0         741.5 Ki   -741.5 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   470.2 Ki
    resets:     2
    purges:    11.8 Ki
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:   385.580 s
   process: user: 2463.906 s, system: 40.468 s, faults: 15233701, rss: 12.1 GiB, commit: 18.7 GiB
...
```

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much!
I think I must have broke something when changing the output profile config file.
Screen Shot 2023-05-16 at 8 16 20 AM
I added the `ExtraFieldInfo` to the default profile but it does not output the extra column:
Screen Shot 2023-05-16 at 8 15 55 AM

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your comment.

I apologize for the lack of confirmation. I will confirm it for you.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for comment. I checked the status of https://github.com/Yamato-Security/hayabusa/pull/1052/commits/941c686cccbfe842fd81391b840b7686a25e2190 and found that the following I confirmed that ExtraFieldInfo is output with the following command: 

`> ./900.exe csv-timeline -d ..\hayabusa-sample-evtx\ --debug -p standard -D -u -n -o standard2-2.csv`

image

**Review by fukusuket — APPROVED** [review]
I confirmed that the number of detections did not change before and after this PR, and that `ExtraFieldInfo` was output, LGTM!🚀

**Comment by YamatoSecurity** [comment]
@hitenkoku 
As I thought, it wasn't outputting due to my changes. Very sorry! I forgot that I needed to update the default profile yml file.

I did some benchmarks and unique detections is the same.

|                   | main - minimal profile (no extra) | main - standard profile (no Extra) | This PR - minimal (No extra) | This PR - standard (with Extra) |
|-------------------|-----------------------------------|------------------------------------|------------------------------|---------------------------------|
| Elasped Time      | 30:32                             | 29:53                              | 30:37                        | 30:49                           |
| Peak Memory Usage | 12.7 GB                           | 16.4 GB                            | 12.7 GB                      | 18.9 GB                         |
| File Size         | 2.8 GB                            | 3 GB                               | 2.8 GB                       | 4.6 GB                          |

Also, speed and memory usage is good!

Just one thing, when outputting to JSON, is it possible to parse the fields like `Details` and `AllFieldInfo`?
If this is hard, we can merge this PR and make a separate issue.
At the moment, the first field is not showing. (It starts with the first field's data):
Screen Shot 2023-05-17 at 11 17 45 AM

**Comment by hitenkoku** [comment]
@fukusuket @YamatoSecurity   Thanks for your quick review.

@YamatoSecurity I have fixed the areas you pointed out in https://github.com/Yamato-Security/hayabusa/pull/1052/commits/ade8122b0223675087f68e15c23d563d786189fa.

Could you check it?

**Review by YamatoSecurity — APPROVED** [review]
LGTM!
Thank you so much!

**Comment by hitenkoku** [comment]
@YamatoSecurity @fukusuket 

Thanks for your review!
I will merge it.

**Pull request merged**
