### PR TITLE
finalize 2.18.0

### PR DESCRIPTION
**Pull request by YamatoSecurity**
updated crates for the next release

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@fukusuket It looks like some of our tests are failing because we removed the sample files? Could you take a look at this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
With the Rust version upgrade, Clippy's checks seem to have become stricter. This will be fixed later!

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀 I fixed clippy error and test error!

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!

**Pull request merged**
