### PR TITLE
feat: Ignore referenced rules in correlation rules(when `generate: true` not set)

### LINKED ISSUE #1367: Ignore referenced rules in sigma correlation rules
If there is a rule like this:
```
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - rule-a
    - rule-b
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
---
title: Logon Failure (User Does Not Exist)
name: rule-a

logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
name: rule-b

logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```
we should ignore rules `rule-a` and `rule-b` as separate rules as we already have them in separate rules. This also lets us only display results for the correlation rule instead of having to also display/save the results for the referenced rules as well.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1367 

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -D -n -u -q -o new.csv
% ./hayabusa-main csv-timeline -d ../hayabusa-sample-evtx -w -D -n -u -q -o old.csv
% diff new.csv old.csv
%
```

**Comment by fukusuket** [comment]
### not specified `generate`
```yaml
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d 
    - e87bd730-df45-4ae9-85de-6c75369c5d29 
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
---
title: Logon Failure (User Does Not Exist)
description: Prints failed logons

id: 8afa97ce-a217-4f7c-aced-3e320a57756d
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
description: Prints logon information. 

id: e87bd730-df45-4ae9-85de-6c75369c5d29
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```

```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r test.yml -w -C -q -o out.csv 
% cat out.csv
"Timestamp","RuleTitle","Level","Computer","Channel","EventID","RecordID","Details","ExtraFieldInfo"
"2016-09-20 01:50:06.477 +09:00","Value Count TEST","info","-","-","-","-","Count:2 ¦ SubStatus:0xc000006a/0xc0000064 ¦ Computer:DESKTOP-M5SN04R","-"
"2021-05-20 21:49:53.378 +09:00","Value Count TEST","info","-","-","-","-","Count:2 ¦ SubStatus:0xc000006a/0xc0000064 ¦ Computer:fs01.offsec.lan","-"

```

**Comment by fukusuket** [comment]
### set `generate:true`
```yaml
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d
    - e87bd730-df45-4ae9-85de-6c75369c5d29
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
  generate: true
---
title: Logon Failure (User Does Not Exist)
description: Prints failed logons

id: 8afa97ce-a217-4f7c-aced-3e320a57756d
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
description: Prints logon information.

id: e87bd730-df45-4ae9-85de-6c75369c5d29
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```

```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r test.yml -w -C -q -o out.csv
% cat out.csv | tail -n 5
"2021-05-20 21:49:54.043 +09:00","Logon Failure (User Does Not Exist)","-","fs01.offsec.lan","Sec",4625,1861991,"Type: 8 - NETWORK CLEARTEXT ¦ TgtUser: NOUSER ¦ SrcComp: FS01 ¦ SrcIP: - ¦ AuthPkg: Negotiate ¦ Proc: C:\Program Files\OpenSSH-Win64\sshd.exe","FailureReason: BAD USER OR PW ¦ KeyLength: 0 ¦ LogonProcessName: Advapi ¦ ProcessId: 5848 ¦ Status: BAD USER OR PW ¦ SubStatus: UNKNOWN USER ¦ SubjectDomainName: OFFSEC ¦ SubjectLogonId: 0x3e7 ¦ SubjectUserName: FS01$ ¦ SubjectUserSid: S-1-5-18 ¦ TargetUserSid: S-1-0-0"
"2021-05-20 21:49:54.662 +09:00","Logon Failure (User Does Not Exist)","-","fs01.offsec.lan","Sec",4625,1861993,"Type: 8 - NETWORK CLEARTEXT ¦ TgtUser: NOUSER ¦ SrcComp: FS01 ¦ SrcIP: - ¦ AuthPkg: Negotiate ¦ Proc: C:\Program Files\OpenSSH-Win64\sshd.exe","FailureReason: BAD USER OR PW ¦ KeyLength: 0 ¦ LogonProcessName: Advapi ¦ ProcessId: 5848 ¦ Status: BAD USER OR PW ¦ SubStatus: UNKNOWN USER ¦ SubjectDomainName: OFFSEC ¦ SubjectLogonId: 0x3e7 ¦ SubjectUserName: FS01$ ¦ SubjectUserSid: S-1-5-18 ¦ TargetUserSid: S-1-0-0"
"2021-05-20 21:49:54.945 +09:00","Logon Failure (User Does Not Exist)","-","fs01.offsec.lan","Sec",4625,1861995,"Type: 8 - NETWORK CLEARTEXT ¦ TgtUser: NOUSER ¦ SrcComp: FS01 ¦ SrcIP: - ¦ AuthPkg: Negotiate ¦ Proc: C:\Program Files\OpenSSH-Win64\sshd.exe","FailureReason: BAD USER OR PW ¦ KeyLength: 0 ¦ LogonProcessName: Advapi ¦ ProcessId: 5848 ¦ Status: BAD USER OR PW ¦ SubStatus: UNKNOWN USER ¦ SubjectDomainName: OFFSEC ¦ SubjectLogonId: 0x3e7 ¦ SubjectUserName: FS01$ ¦ SubjectUserSid: S-1-5-18 ¦ TargetUserSid: S-1-0-0"
"2016-09-20 01:50:06.477 +09:00","Value Count TEST","info","-","-","-","-","Count:2 ¦ SubStatus:0xc000006a/0xc0000064 ¦ Computer:DESKTOP-M5SN04R","-"
"2021-05-20 21:49:53.378 +09:00","Value Count TEST","info","-","-","-","-","Count:2 ¦ SubStatus:0xc000006a/0xc0000064 ¦ Computer:fs01.offsec.lan","-"

```

**Review by hitenkoku — APPROVED** [review]

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
