### PR TITLE
Adjusted json input from json export from splunk

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Adjusted json input from json export from splunk

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku Will JSON input still work for the apt29 json files? If it is not possible to support both formats, then maybe we can add a different option for splunk json input? I would like to still support the apt29 json file format.

**Review by fukusuket — COMMENTED** [review]
I confirmed that both apt29/Splunk data works properly :)
I have one question! `Details` is blank when using `json-timeline`. Is it difficult to support `Details`...?🤔

**Comment by hitenkoku** [comment]
Thanks for your check. I will check to Details.

> I confirmed that both apt29/Splunk data works properly :) I have one question! `Details` is blank when using `json-timeline`. Is it difficult to support `Details`...?🤔

**Comment by hitenkoku** [comment]
@fukusuket Sorry for late replying. I fixed to following problem in https://github.com/Yamato-Security/hayabusa/pull/1286/commits/478db5e1b2f8e8e978687aa71e012fcb83633471 .

Could you recheck it?

> I confirmed that both apt29/Splunk data works properly :)
> I have one question! Details is blank when using json-timeline. Is it difficult to support Details...?🤔

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for fix! I confirmed that `Details` are output when executing json-timeline using Splunk's JSON data. LGTM :)🚀

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM!

**Pull request merged**
