### PR TITLE
feat: add support for Sigma v2 `|re` sub modifiers

### LINKED ISSUE #1396: Support sigma V2 `|re` sub-modifiers
https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-modifiers-appendix.md

I'd like to support the V2 `re` sub-modifiers before they start being used. Currently they are not in use but will probably be soon.
Example:
```
title: Potential Registry Reconnaissance Via PowerShell Script
id: 064060aa-09fb-4636-817f-020a32aa7e9e
detection:
    selection:
        # TODO: switch to |re|i: after sigma specification v2 is released
        ScriptBlockText|re: '(Get-Item|gci|Get-ChildItem).{1,64}-Path.{1,64}\\(currentcontrolset\\services|CurrentVersion\\Policies\\Explorer\\Run|CurrentVersion\\Run|CurrentVersion\\ShellServiceObjectDelayLoad|CurrentVersion\\Windows\winlogon)\\'
    condition: selection
```

`|re|i:` : (insensitive) to **disable** case-sensitive matching.  (Note: the documentation says to enable it, but I think is a typo)
`|re|m:` : (multi line) to match across multiple lines. ^ /$ match the start/end of line.
`|re|s:` : (single line) to enable that dot (.) matches all characters, including the newline character.

@fukusuket Since you are our regular expressions master, do you want to do this? It is ok if it is not complete before HITCON.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #1396 

### csv-timeline/json-timeline diff check (compared with main branch)
No difference in the result file compared to the main branch.
https://github.com/Yamato-Security/hayabusa/actions/runs/10411818917

### Integration-test
All commands work properly.
https://github.com/Yamato-Security/hayabusa/actions/runs/10411817930

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### test data
```
./hayabusa json-timeline -p super-verbose -f ../hayabusa-sample-evtx/YamatoSecurity/ImpairDefenses/T1562.010_DowngradeAttack_PowerShell.evtx -e informational -w
```
```json
{
    "Timestamp": "2021-01-28 19:40:54.884 +09:00",
    "RuleTitle": "Windash TEST",
    "Level": "info",
    "Computer": "DESKTOP-ST69BPO",
    "Channel": "PwShClassic",
    "EventID": 400,
    "RuleAuthor": "TEST",
    "RuleModifiedDate": "-",
    "Status": "test",
    "RecordID": 729,
    "Details": {},
    "ExtraFieldInfo": {
        "CommandLine": "",
        "CommandName": "",
        "CommandPath": "",
        "CommandType": "",
        "Data[1]": "Available",
        "Data[2]": "None",
        "Data[3]": "NewEngineState=Available\\n\\tPreviousEngineState=None\\n\\n\\tSequenceNumber=9\\n\\n\\tHostName=ConsoleHost\\n\\tHostVersion=2.0\\n\\tHostId=5cbb33bf-acf7-47cc-9242-141cd0ba9f0c\\n\\tEngineVersion=2.0\\n\\tRunspaceId=c6e94dca-0daf-418c-860a-f751a9f2cbe1\\n\\tPipelineId=\\n\\tCommandName=\\n\\tCommandType=\\n\\tScriptName=\\n\\tCommandPath=\\n\\tCommandLine=",
        "EngineVersion": "2.0",
        "HostId": "5cbb33bf-acf7-47cc-9242-141cd0ba9f0c",
        "HostName": "ConsoleHost",
        "HostVersion": "2.0",
        "NewEngineState": "Available",
        "PipelineId": "",
        "PreviousEngineState": "None",
        "RunspaceId": "c6e94dca-0daf-418c-860a-f751a9f2cbe1",
        "ScriptName": "",
        "SequenceNumber": 9
    },
    "Provider": "PwrShell",
    "RuleCreationDate": "-",
    "RuleFile": "test.yml",
    "EvtxFile": "../hayabusa-sample-evtx/YamatoSecurity/ImpairDefenses/T1562.010_DowngradeAttack_PowerShell.evtx"
}
```

**Comment by fukusuket** [comment]
### `re|i`
```yml
title: Windash TEST
id: 0550d910-7787-4892-9791-c1c6a26ec16a
status: test
author: TEST
logsource:
    product: windows
    category: powershell
detection:
    selection:
        EventID: 400
        Channel: 'Windows PowerShell'
        Data|re|i: "SEQUENCENUMBER=9.*"
    condition: selection
level: informational
```

**Comment by fukusuket** [comment]
### `re|m`
```yml
title: Windash TEST
id: 0550d910-7787-4892-9791-c1c6a26ec16a
status: test
author: TEST
logsource:
    product: windows
    category: powershell
detection:
    selection:
        EventID: 400
        Channel: 'Windows PowerShell'
        Data|re|i: "SEQUENCENUMBER=9.*"
    condition: selection
level: informational
```

**Comment by fukusuket** [comment]
### `re|m`
```yml
title: Windash TEST
id: 0550d910-7787-4892-9791-c1c6a26ec16a
status: test
author: TEST
logsource:
    product: windows
    category: powershell
detection:
    selection:
        EventID: 400
        Channel: 'Windows PowerShell'
        Data|re|i: "SEQUENCENUMBER=9.*"
    condition: selection
level: informational
```

**Review by hitenkoku — APPROVED** [review]

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much for the super quick PR!

**Pull request merged**
