### PR TITLE
chg: disable `Channel` filter when `-J, --JSON-input` option

### LINKED ISSUE #1343: [bug] Nothing is detected when using the `-J, --JSON-input`  option with the timeline command because of `Channel` filter
**Describe the bug**
Nothing is detected when using the `-J, --JSON-input`  option with the timeline command because of `Channel` filer  https://github.com/Yamato-Security/hayabusa/pull/1334 :(
This issue occurs only in `dev-2.16.0` version.

**Step to Reproduce**
1. Download [apt29_evals_day1_manual.zip](https://github.com/OTRF/Security-Datasets/blob/master/datasets/compound/apt29/day1/apt29_evals_day1_manual.zip) and unzip.
2. `hayabusa csv-timeline -f ../apt29/apt29_evals_day1_manual_2020-05-01225525.json -J -w`

**Actual behavior**
Nothing is detected.

**Expected behavior**
I expect the following behavior. It is necessary to consider which specifications to use.
- Detect as in version `2.15.0` (disable Channel filter when `-J, --JSON-input`)
- Indicate that `-A, --enable-all-rules` /`-a, --scan-all-evtx-files` option is required.
- Just like `evtx`, get the `Channel` of the first record and filter based on it
   -  Is it okay to assume that `JSON` has 1 channel in 1 file like `evtx`?

**Environment**
- OS: macOS Sonoma 14.4.1
- Hayabusa version 2.16.0-dev(Occurs only in the version currently under development)

**Additional context**
If you enable the `-A, --enable-all-rules` /`-a, --scan-all-evtx-files` option, it will be detected as in version 2.15.0.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1343 

## Evidence
I confirm that it is not filtered when the J option is specified.
```
% ./hayabusa csv-timeline -f ../apt29/apt29_evals_day1_manual_2020-05-01225525.json -J -w -q -o timeline.csv
Start time: 2024/05/09 20:25

Total event log files: 1
Total file size: 385.3 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12 (Disabled)

Deprecated rules: 208 (5.06%) (Disabled)
Experimental rules: 856 (20.83%)
Stable rules: 240 (5.84%)
Test rules: 3,014 (73.33%)
Unsupported rules: 45 (1.09%) (Disabled)

Hayabusa rules: 162
Sigma rules: 3,948
Total detection rules: 4,110

Output profile: standard

Scanning in progress. Please wait.

[00:00:16] 1 / 1   [========================================] 100%

Scanning finished. Please wait while the results are being saved.

Rule Authors:
....
```
I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -q -o timeline.csv -C
Start time: 2024/05/09 20:26

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12 (Disabled)

Deprecated rules: 208 (5.06%) (Disabled)
Experimental rules: 856 (20.83%)
Stable rules: 240 (5.84%)
Test rules: 3,014 (73.33%)
Unsupported rules: 45 (1.09%) (Disabled)

Hayabusa rules: 162
Sigma rules: 3,948
Total detection rules: 4,110

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 575
Detection rules enabled after channel filter: 4,041

Output profile: standard

Scanning in progress. Please wait.

[00:00:05] 575 / 575   [========================================] 100%
```

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! I think we should also add a message to the user if they try to specify `-J` with either `-A` and/or `-a`: `Error: It is not necessary to specify -A, --enable-all-rules or -a, --scan-all-evtx-files with -J, --JSON-input because the channel filter only works with EVTX files.`

What do you think?

**Comment by fukusuket** [comment]
It would be better to have a message that is easy for users to understand, so I will implement it!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I implement it! Could you confirm?🙏
```
% ./hayabusa csv-timeline -f ../apt29/apt29_evals_day1_manual_2020-05-01225525.json -J -w -q -o timeline.csv -A -C
Start time: 2024/05/09 22:04

[ERROR] It is not necessary to specify -A, --enable-all-rules or -a, --scan-all-evtx-files with -J, --JSON-input because the channel filter only works with EVTX files.
fukusuke@fukusukenoMacBook-Air hayabusa-2.15.0-mac-arm % ./hayabusa csv-timeline -f ../apt29/apt29_evals_day1_manual_2020-05-01225525.json -J -w -q -o timeline.csv -a -C
Start time: 2024/05/09 22:04

[ERROR] It is not necessary to specify -A, --enable-all-rules or -a, --scan-all-evtx-files with -J, --JSON-input because the channel filter only works with EVTX files.
fukusuke@fukusukenoMacBook-Air hayabusa-2.15.0-mac-arm % ./hayabusa csv-timeline -f ../apt29/apt29_evals_day1_manual_2020-05-01225525.json -J -w -q -o timeline.csv -C
Start time: 2024/05/09 22:05

Total event log files: 1
Total file size: 385.3 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12 (Disabled)

Deprecated rules: 208 (5.06%) (Disabled)
Experimental rules: 856 (20.83%)
Stable rules: 240 (5.84%)
Test rules: 3,014 (73.33%)
Unsupported rules: 45 (1.09%) (Disabled)

Hayabusa rules: 162
Sigma rules: 3,948
Total detection rules: 4,110

Output profile: standard

Scanning in progress. Please wait.
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! I just updated some messaging and the changelog

**Review by hitenkoku — APPROVED** [review]

**Pull request merged**
