### PR TITLE
Fixed bug powershell classic logs data field is output to multiple times resulting in incorrect json format

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Fixed bug powershell classic logs data field is output to multiple times resulting in incorrect json format

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

used rule

```
date: 2023/10/26

title: "TEST"
description: "TEST"

id: 048a461f-4177-475c-9ee7-b5d705621167
level: informational
status: test
logsource:
  product: windows
  service: powershell
detection:
  selection:
    Channel: "Windows PowerShell"
    EventID: 400
  condition: selection
falsepositives:
tags:
references:
ruletype: Hayabusa
```

- 2.11.0

```
{
    "Timestamp": "2021-01-28 18:58:44.538 +09:00",
    "Computer": "DESKTOP-ST69BPO",
    "Channel": "PwShClassic",
    "EventID": 400,
    "Level": "info",
    "RecordID": 711,
    "RuleTitle": "TEST",
    "Details": {
    },
    "ExtraFieldInfo": {
        "CommandLine": "",
        "CommandName": "",
        "CommandPath": "",
        "CommandType": "",
        "Data": "Available",
        "Data": "NewEngineState=Available\\r\\n\\tPreviousEngineState=None\\r\\n\\r\\n\\tSequenceNumber=13\\r\\n\\r\\n\\tHostName=ConsoleHost\\r\\n\\tHostVersion=5.1.18362.145\\r\\n\\tHostId=64821494-0737-4ce9-ad67-3ac0e50a81b8\\r\\n\\tHostApplication=powershell calc\\r\\n\\tEngineVersion=5.1.18362.145\\r\\n\\tRunspaceId=74ae21ca-7fa9-40cc-a265-7a41fdb168a6\\r\\n\\tPipelineId=\\r\\n\\tCommandName=\\r\\n\\tCommandType=\\r\\n\\tScriptName=\\r\\n\\tCommandPath=\\r\\n\\tCommandLine=",
        "Data": "None",
        "EngineVersion": "5.1.18362.145",
        "HostApplication": "powershell calc",
        "HostId": "64821494-0737-4ce9-ad67-3ac0e50a81b8",
        "HostName": "ConsoleHost",
        "HostVersion": "5.1.18362.145",
        "NewEngineState": "Available",
        "PipelineId": "",
        "PreviousEngineState": "None",
        "RunspaceId": "74ae21ca-7fa9-40cc-a265-7a41fdb168a6",
        "ScriptName": "",
        "SequenceNumber": 13
    }
}
```

- this PR

```
{
    "Timestamp": "2021-01-28 18:58:44.538 +09:00",
    "Computer": "DESKTOP-ST69BPO",
    "Channel": "PwShClassic",
    "EventID": 400,
    "Level": "info",
    "RecordID": 711,
    "RuleTitle": "TEST",
    "Details": {
    },
    "ExtraFieldInfo": {
        "CommandLine": "",
        "CommandName": "",
        "CommandPath": "",
        "CommandType": "",
        "Data": ["Available", "NewEngineState=Available\\r\\n\\tPreviousEngineState=None\\r\\n\\r\\n\\tSequenceNumber=13\\r\\n\\r\\n\\tHostName=ConsoleHost\\r\\n\\tHostVersion=5.1.18362.145\\r\\n\\tHostId=64821494-0737-4ce9-ad67-3ac0e50a81b8\\r\\n\\tHostApplication=powershell calc\\r\\n\\tEngineVersion=5.1.18362.145\\r\\n\\tRunspaceId=74ae21ca-7fa9-40cc-a265-7a41fdb168a6\\r\\n\\tPipelineId=\\r\\n\\tCommandName=\\r\\n\\tCommandType=\\r\\n\\tScriptName=\\r\\n\\tCommandPath=\\r\\n\\tCommandLine=", "None"],
        "EngineVersion": "5.1.18362.145",
        "HostApplication": "powershell calc",
        "HostId": "64821494-0737-4ce9-ad67-3ac0e50a81b8",
        "HostName": "ConsoleHost",
        "HostVersion": "5.1.18362.145",
        "NewEngineState": "Available",
        "PipelineId": "",
        "PreviousEngineState": "None",
        "RunspaceId": "74ae21ca-7fa9-40cc-a265-7a41fdb168a6",
        "ScriptName": "",
        "SequenceNumber": 13
    }
}
```

**Review by fukusuket — APPROVED** [review]
I have fixed the bug and confirmed that there is no difference in the csv-timeline results before and after the fix! LGTM!!🚀

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I tried checking with `./target/release/hayabusa json-timeline -L -d ../hayabusa-sample-evtx -o new-json.jsonl -w` but when I try to parse with `jq`: `cat new-json.jsonl | jq` it gives me the following parse error: `jq: parse error: Invalid numeric literal at line 35728, column 205`

2.11.0:
```
{ "Timestamp": "2017-08-31 04:13:52.552 +09:00","Computer": "SEC511","Channel": "PwSh","EventID": 4104,"Level": "info","RecordID": 636579,"RuleTitle": "PwSh Scriptblock","Details": {"ScriptBlock": "[sTRInG]::jOiN('' , (( 49 ,45 , 58,20,28 , '4e',65,77 , '2d' ,'4f' ,62 , '6a' , 65,63, 74 ,20 ,'4e', 65 ,74 ,'2e' ,57, 65 , 62,43 ,'6c',69, 65 , '6e' , 74 ,29 ,'2e',44,'6f' , 77 ,'6e','6c' , '6f' ,61, 64 ,53 , 74,72 ,69 ,'6e',67, 28, 27 , 68 ,74, 74,70 ,73, '3a', '2f','2f', 72, 61, 77 , '2e',67,69, 74 ,68 , 75,62, 75, 73,65 ,72,63, '6f','6e',74 ,65, '6e', 74 ,'2e',63 ,'6f', '6d','2f' , '6d', 61 ,74 ,74, 69,66 , 65, 73 ,74 ,61, 74 , 69 ,'6f' , '6e', '2f' ,50,'6f',77, 65,72,53 ,70, '6c' , '6f' ,69 ,74, '2f' , '6d' , 61 , 73 , 74,65,72 , '2f' ,45,78,66, 69, '6c', 74 , 72,61, 74,69,'6f' , '6e' , '2f' , 49,'6e' , 76, '6f','6b' ,65 , '2d' , '4d' ,69,'6d' , 69, '6b',61 , 74 , '7a' , '2e',70, 73 , 31 , 27, 29 ,'3b' ,20 ,49 ,'6e' , 76,'6f', '6b', 65, '2d', '4d',69, '6d' ,69,'6b' , 61 ,74, '7a' , 20 , '2d' ,44 , 75,'6d' , 70, 43, 72 ,65 ,64 , 73)|FoReaCh{ ([ChaR] ([Convert]::TOiNt16(($_.tOsTriNg()),16 )))}))|&( $enV:PuBlic[13]+$eNv:PUbliC[5]+'X')"},"ExtraFieldInfo": {"MessageNumber": 1,"MessageTotal": 1,"Path": "","ScriptBlockId": "a7052bb8-9adc-4e86-ad95-13378e481ee2"} }
```

2.12.0-dev:
```
{ "Timestamp": "2017-08-31 04:13:52.552 +09:00","Computer": "SEC511","Channel": "PwSh","EventID": 4104,"Level": "info","RecordID": 636579,"RuleTitle": "PwSh Scriptblock","Details": {"ScriptBlock": [sTRInG]::jOiN('' , (( 49 ,45 , 58,20,28 , '4e',65,77 , '2d' ,'4f' ,62 , '6a' , 65,63, 74 ,20 ,'4e', 65 ,74 ,'2e' ,57, 65 , 62,43 ,'6c',69, 65 , '6e' , 74 ,29 ,'2e',44,'6f' , 77 ,'6e','6c' , '6f' ,61, 64 ,53 , 74,72 ,69 ,'6e',67, 28, 27 , 68 ,74, 74,70 ,73, '3a', '2f','2f', 72, 61, 77 , '2e',67,69, 74 ,68 , 75,62, 75, 73,65 ,72,63, '6f','6e',74 ,65, '6e', 74 ,'2e',63 ,'6f', '6d','2f' , '6d', 61 ,74 ,74, 69,66 , 65, 73 ,74 ,61, 74 , 69 ,'6f' , '6e', '2f' ,50,'6f',77, 65,72,53 ,70, '6c' , '6f' ,69 ,74, '2f' , '6d' , 61 , 73 , 74,65,72 , '2f' ,45,78,66, 69, '6c', 74 , 72,61, 74,69,'6f' , '6e' , '2f' , 49,'6e' , 76, '6f','6b' ,65 , '2d' , '4d' ,69,'6d' , 69, '6b',61 , 74 , '7a' , '2e',70, 73 , 31 , 27, 29 ,'3b' ,20 ,49 ,'6e' , 76,'6f', '6b', 65, '2d', '4d',69, '6d' ,69,'6b' , 61 ,74, '7a' , 20 , '2d' ,44 , 75,'6d' , 70, 43, 72 ,65 ,64 , 73)|FoReaCh{ ([ChaR] ([Convert]::TOiNt16(($_.tOsTriNg()),16 )))}))|&( $enV:PuBlic[13]+$eNv:PUbliC[5]+'X')},"ExtraFieldInfo": {"MessageNumber": 1,"MessageTotal": 1,"Path": "","ScriptBlockId": "a7052bb8-9adc-4e86-ad95-13378e481ee2"} }
```

The value of `"ScriptBlock"` is not put in quotes. 

Before: `"ScriptBlock": "[sTRInG]::jOiN・・・` 

After: `"ScriptBlock": [sTRInG]::jOiN・・・`

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.
I fixed following problem in https://github.com/Yamato-Security/hayabusa/pull/1227/commits/98110c716dff623f2f382d49ae6b90c8d29bfbd9 

Would you check it?

- test command
```
> ./1202.exe  json-timeline  -d ../hayabusa-sample-evtx -o new-json.json -w -C  > 1202.log 
> cat new-json.json  |  jq .
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thank you!

**Pull request merged**
