### PR TITLE
feat: output field information in green and messages in orange

### LINKED ISSUE #1491: Output field information in green and messages in orange
For the following output when running:
```
Start time: 2024/11/13 08:03

Total event log files: 598
Total file size: 139.2 MB

Loading detection rules. Please wait.

Excluded rules: 26
Noisy rules: 12 (Disabled)

Deprecated rules: 216 (5.01%) (Disabled)
Experimental rules: 373 (8.65%)
Stable rules: 241 (5.59%)
Test rules: 3,700 (85.77%)
Unsupported rules: 42 (0.97%) (Disabled)

Correlation rules: 3 (0.07%)
Correlation referenced rules: 3 (0.07%)

Hayabusa rules: 175
Sigma rules: 4,139
Total detection rules: 4,314

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 585
Detection rules enabled after channel filter: 4,237

Output profile: standard
```

I would like to output the `hogehoge:` parts (Ex: `Start time:`, `Total event log files:`, etc...) in the same green as the HAYABUSA logo. (With the ability to disable colors with the `--no-color` option.)
Also `Scan wizard:` in green.
At the end:
```
Elapsed time: 00:00:07.1247

Please report any issues with Hayabusa rules to: https://github.com/Yamato-Security/hayabusa-rules/issues
Please report any false positives with Sigma rules to: https://github.com/SigmaHQ/sigma/issues
Please submit new Sigma rules with pull requests to: https://github.com/SigmaHQ/sigma/pulls
```
`Elapsed time:`, `Please report any issues with Hayabusa rules to:`, etc... also in green.

I want to output `Loading detection rules. Please wait.`, `Creating the channel filter. Please wait.`, `Scanning finished.` in the same orange color as `?` and `(y/n)` in the scan wizard settings.

I think this will make things easier to read and look better.

@fukusuket could I ask you to do this one?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1491 

### Integration-Test
https://github.com/Yamato-Security/hayabusa/actions/runs/11853318764

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! Looking great! One small part, I noticed `Scanning finished. Please wait while the results are being saved.` is still white. Is it possible to display in orange? If it is hard because it is part of the progress bar then we can leave it white or make everything (files being scanned) all orange if possible.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking!
Unfortunately I tried, but that message was output in the Progress Bar module and I could not change the color... :(

**Comment by fukusuket** [comment]
The color can be changed by erasing the progress bar itself at the end of the progress bar, but it is easier to understand if the progress bar is output at 100%.

**Comment by fukusuket** [comment]
Sorry, I noticed that commands other than timeline (metrics/pivot ... etc) still need to be colored, so I'm fixing it!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I fixed coloring except for timeline commands as follows! Could you please check it?🙏
https://github.com/Yamato-Security/hayabusa/actions/runs/11855691986

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! I figured out how to make the "Scanning finished...." message orange but it is still orange when `--no-color` option is enabled. Do you know how to disable the coloring when this is enabled?
Also, could you add a short-hand option for `--no-color`. Maybe `-k`? (anything that is not already used it ok)

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much! Great!!🚀 I updated https://github.com/Yamato-Security/hayabusa/pull/1498#issuecomment-2480107600 :)

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks!

Could you add a space here:
```
./target/release/hayabusa list-profiles

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Collecting the gold specks in the desert~

Start time: 2024/11/16 08:40
List of available profiles:
- minimal:                 %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %Details%
- standard:                %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %Details%, %ExtraFieldInfo%
- verbose:                 %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %ExtraFieldInfo%, %RuleFile%, %EvtxFile%
- all-field-info:          %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %AllFieldInfo%, %RuleFile%, %EvtxFile%
- all-field-info-verbose:  %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %AllFieldInfo%, %RuleFile%, %EvtxFile%
- super-verbose:           %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RuleAuthor%, %RuleModifiedDate%, %Status%, %RecordID%, %Details%, %ExtraFieldInfo%, %MitreTactics%, %MitreTags%, %OtherTags%, %Provider%, %RuleCreationDate%, %RuleFile%, %EvtxFile%
- timesketch-minimal:      %Timestamp%, hayabusa, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %RuleFile%, %EvtxFile%
- timesketch-verbose:      %Timestamp%, hayabusa, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %ExtraFieldInfo%, %RuleFile%, %EvtxFile%
日々是好日 - Nichinichi Kore Koujitsu - Everyday is a good day.
```
After:
```
./target/release/hayabusa list-profiles

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Collecting the gold specks in the desert~

Start time: 2024/11/16 08:40
List of available profiles:
- minimal:                 %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %Details%
- standard:                %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %Details%, %ExtraFieldInfo%
- verbose:                 %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %ExtraFieldInfo%, %RuleFile%, %EvtxFile%
- all-field-info:          %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RecordID%, %AllFieldInfo%, %RuleFile%, %EvtxFile%
- all-field-info-verbose:  %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %AllFieldInfo%, %RuleFile%, %EvtxFile%
- super-verbose:           %Timestamp%, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %RuleAuthor%, %RuleModifiedDate%, %Status%, %RecordID%, %Details%, %ExtraFieldInfo%, %MitreTactics%, %MitreTags%, %OtherTags%, %Provider%, %RuleCreationDate%, %RuleFile%, %EvtxFile%
- timesketch-minimal:      %Timestamp%, hayabusa, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %RuleFile%, %EvtxFile%
- timesketch-verbose:      %Timestamp%, hayabusa, %RuleTitle%, %Level%, %Computer%, %Channel%, %EventID%, %MitreTactics%, %MitreTags%, %OtherTags%, %RecordID%, %Details%, %ExtraFieldInfo%, %RuleFile%, %EvtxFile%

日々是好日 - Nichinichi Kore Koujitsu - Everyday is a good day.
```

**Comment by YamatoSecurity** [comment]
Sorry, it is unrelated to this PR but here:
```
./target/release/hayabusa list-contributors

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Giving you the Windows event logs you've always wanted~

Start time: 2024/11/16 08:42
Hayabusa was possible thanks to the following people (in alphabetical order):

Akira Nishikawa (@nishikawaakira): First lead developer (core hayabusa rule support, etc...)
Fukusuke Takahashi (fukusuket): Core developer (Too many bug fixes to count, hayabusa converter upgrades, new features, etc...)
Garigariganzy (@garigariganzy31): Developer (Event ID metrics implementation, etc...)
ItiB (@itiB_S144):  Core developer (sigmac hayabusa backend, search command, etc...)
James Takai / hachiyone(@hach1yon): Second lead developer (Tokio multi-threading, sigma aggregation logic, sigmac backend, rule creation, sigma count implementation etc…)
Kazuminn (@k47_um1n): Core Developer (Many features.)
Matthew Seyer: adding the ability to carve out records
Tsubokku (@ytsuboi0322): Translations
Yusuke Matsui (@apt773): AD hacking working group leader, rule testing, documentation, research, support, etc...
Zach Mathis (@yamatosecurity, Yamato Security Founder): Project leader, tool and concept design, rule creation and tuning, etc…

Also a big thanks to the following people for projects that make Hayabusa possible:

Omer BenAmram for creating the Rust evtx crate.
The maintainers and contributors of the Sigma project.
```

Can you remove the `Start time: 2024/11/16 08:42` ?

**Comment by YamatoSecurity** [comment]
Sorry, the `search` command has a `-k` option for keyword searching. How about we use `-K` instead?

**Comment by fukusuket** [comment]
Thank you for checking! I fixed above comments!

**Comment by YamatoSecurity** [comment]
thanks! Sorry, one more small thing:
```
./target/release/hayabusa update-rules

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Faster insights, deeper analysis, every time~

Start time: 2024/11/16 08:58
You currently have the latest rules.

柔よく剛を制す - Juu Yoku Gou O Seisu - Softness overcomes hardness.
```

can you add a space here ->
```
./target/release/hayabusa update-rules

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Faster insights, deeper analysis, every time~

Start time: 2024/11/16 08:58

You currently have the latest rules.

柔よく剛を制す - Juu Yoku Gou O Seisu - Softness overcomes hardness.
```

**Comment by YamatoSecurity** [comment]
sorry! here as well
```
./target/release/hayabusa set-default-profile -p super-verbose

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Elevating Windows DFIR to new heights~

Start time: 2024/11/16 09:00
Successfully updated the default profile.

不言実行 - Fugen Jikkou - Actions speak louder than words.
```
->
```
./target/release/hayabusa set-default-profile -p super-verbose

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Elevating Windows DFIR to new heights~

Start time: 2024/11/16 09:00

Successfully updated the default profile.

不言実行 - Fugen Jikkou - Actions speak louder than words.
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Perfect! Thanks so much!

**Pull request merged**
