### PR TITLE
feat: add script and actions for supported modifier markdown

### LINKED ISSUE #1406: Dynamically create a table of supported field modifiers
@fukusuket Could I ask you to do this one?
I would like a markdown table of all of the field modifiers used in Sigma rules ranked by usage and an indicator of whether Hayabusa supports it or not.

So in a daily github action, we download the upstream sigma rules and check the different field modifiers and output the following table to `/docs/SupportedSigmaFieldModifiers.md`

| Count | Field Modifier  | Hayabusa Support |
|-------|-----------------|------------------|
| 100   | \|contains      | Yes              |
| 50    | \|contains\|all | Yes              |
| 30    | \|all           | Yes              |
| 20    | \|re            | Yes              |
| 10    | \|newmodifier   | No               |

This will be useful to check if any new modifiers are being used that Hayabusa does not support and also when learning how to write Sigma rules it is good to know which modifiers are most common, etc...

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1406 

### Run locally
1. `git clone https://github.com/SigmaHQ/sigma`
2. `git clone https://github.com/Yamato-Security/hayabusa.git`
3. `cd hayabusa/doc/script`
4. `poetry install --no-root`
5. `poetry python supported-modifier.py ../sigma ../SupportedSigmaFieldModifiers.md`

### Run Actions
- Manual: https://github.com/fukusuket/hayabusa/actions/runs/10643011211/job/29506086051
- Schedule: `cron: '0 20 * * *'`

## Test
I checked Actions in my repository as follows.
- https://github.com/fukusuket/hayabusa/blob/main/doc/SupportedSigmaFieldModifiers.md
- https://github.com/fukusuket/hayabusa/pull/7
- https://github.com/fukusuket/hayabusa/actions/runs/10643011211/job/29506086051

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@fukusuket Thanks so much! Looking good! Just one small thing, can you put the scripts into a new directory: `hayabusa/scripts/supported_modifiers_check/` ?
I want to separate the scripts from the documents folder.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Yes! I moved script  https://github.com/Yamato-Security/hayabusa/pull/1407#pullrequestreview-2273793180 !💪

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!
Sorry, could I ask just a couple more things.

1. Can you change the `Count` column to `Sigma Count` and add a `Hayabusa Count` column next that shows how many times the modifiers are used for Hayabusa rules?
2. Can you make sure that all of the supported modifiers by Hayabusa are included in the table even if there are no rules that currently use them? (For example, `cased`, etc.. ) Also, can you include all of the modifiers defined in the specification even if there are no rules yet. (https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-modifiers-appendix.md) For example: `gte`, `fieldref`, `base64` sub-modifiers, etc...)
3. After the table, can you add a `Updated: 2024/09/01`. (Date modified.) just so that everyone knows that it is recent and to double check that it is being updated.
4. After the `Updated: xxxx/xx/xx` line, please add `Author: Fukusuke Takahashi`. 😉

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking! I updated https://github.com/Yamato-Security/hayabusa/pull/1407#issuecomment-2323214393 :)  What do you think?
- https://github.com/Yamato-Security/hayabusa/blob/1406-create-supported-field-modifiers/doc/SupportedSigmaFieldModifiers.md

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!

Sorry again for some change requests..
1. I think it will be easier to read if we separate the Hayabusa supported field modifiers and unsupported modifiers. 
Example:
```
# Hayabusa supported field modifiers
<TABLE>

# Hayabusa unsupported field modifiers
<TABLE>
```
What do you think?

2. I thought the table was sorted alphabetically, but it does not seem to be at the moment. How about we move the `Field Modifier` column to the 1st column and sort by alphabet, then `Sigma Rule Modifiers` column, then `Hayabusa Rule Modifiers` column.

3. It looks like the number of Hayabusa field modifiers includes the converted Sigma rules. I just want to include the Hayabusa built-in rules inside the `builtin` directory in the hayabusa-rules repository, not any rules inside the `sigma` directory.

4. There are two modifiers that Hayabusa supports that is outside the Sigma specification: `equalsfield` and `endswithfield` but is not included in the table. Can you check this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking! Yes, it would be easier to read if the paragraphs were separated:) I updated https://github.com/Yamato-Security/hayabusa/pull/1407#issuecomment-2323304708 !💪

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Perfect! Thanks so much!

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@fukusuket Ah, sorry, just 1 small thing. It says that there are 0 Hayabusa rules for `equalsfield` and `endswithfield` but `equalsfield` exists in the following rule:
```
title: Possible Token Impersonation
description: Tries to detect token impersonation by tools like Cobalt Strike.

id: 46614e82-7926-41f9-85aa-006b98c5c2a3
detection:
    selection_basic:
        Channel: Security
        EventID: 4624       # Logon Succesful
    selection_TokenImpersonationCharacteristics:
        LogonType: 9        # New Interactive
        ImpersonationLevel|contains: 1833 # It is actually %%1833 for Impersonation level of "Impersonation".
        SubjectUserName|equalsfield: TargetUserName
    condition: selection_basic and selection_TokenImpersonationCharacteristics
```

and `endswithfield` exists in 
```
title: 'Renamed Exe File'
description: 'This is to detect when an .exe file was renamed. Attackers will often rename malware and lolbas tools in order not to be detected. %OriginalFileName% is the original filename in the PE header when the .exe was compiled.'

id: cc1b2ee2-e737-47ac-8ef1-d6065b65292b
detection:
    SelectBasic:
        Channel: Microsoft-Windows-Sysmon/Operational
        EventID: 1
        OriginalFileName|endswith: '.exe'
    FileNameAndOriginalNameAreSame:
        Image|endswithfield: OriginalFileName
...

```
Could you check why they aren't finding these rules?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Sorry! The implementation was a bit incorrect. It has been corrected!
- https://github.com/Yamato-Security/hayabusa/blob/1406-create-supported-field-modifiers/doc/SupportedSigmaFieldModifiers.md

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
