### PR TITLE
embedded non configurable files into binary

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Embedded art files, contributors list, and html report style files

I would appreciate it if you could check it out when you have time

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
I confirmed that the html report and list-contributors work fine!!

When I mv the art folder and run it, the hayabusa logo did not appear, Could you please confirm? (Sorry if my confirmation procedure is wrong... 😅)

**Comment by hitenkoku** [comment]
Thank you for your comment.
I will check it.

**Comment by hitenkoku** [comment]
@fukusuket  I fixed following problem.  Would you check it?

> I confirmed that the html report and list-contributors work fine!!
> 
> When I mv the art folder and run it, the hayabusa logo did not appear, Could you please confirm? (Sorry if my confirmation procedure is wrong... 😅)

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! I checked that everything works as expected. Thanks so much!

**Pull request merged**
