### PR TITLE
feat: add support `expand` modifier

### LINKED ISSUE #1434: Support `expand` modifiers
`contains|expand` and `expand` are the last modifiers that are used by rules but are not supported.
This modifier is more difficult than the others because custom lists need to be created beforehand in order to use them.

Current list of expand possibilities:
```
Admins_Workstations
DC-MACHINE-NAME
Workstations
internal_domains
domain_controller_hostnames
```

Since these lists will need to be created on the user's end, I want to place them in the `./config/expand/` directory instead of `./rules/config/expand` as we will not need to dynamically upload them.

Example rule:
```
detection:
    selection:
        EventID: 5145
        RelativeTargetName|contains: '\winreg'
    filter_main:
        IpAddress|expand: '%Admins_Workstations%'
    condition: selection and not filter_main
```

If the `./config/expand/Admins_Workstations.txt` file exists, then Hayabusa will replace the placeholder `%Admins_Workstations%` with every string inside this text file. There can be multiple values inside the text file, so for example if there are 5 admin workstation names in the text file, then essentially Hayabusa will use 5 different variations of this rule.

For example, it will essentially check the same logic as:
```
- IpAddress: 'AdminWorkstation1'
- IpAddress: 'AdminWorkstation2'
- IpAddress: 'AdminWorkstation3'
- IpAddress: 'AdminWorkstation4'
- IpAddress: 'AdminWorkstation5'
```

As of now, the only variation of `expand` is `contains|expand` but we should also probably support `startswith|expand` and `endswith|expand` as well.

If `./config/expand/Admins_Workstations.txt` does NOT exist, then Hayabusa will just ignore this rule. 

We should add the number of loaded "expand rules":
```
Loading detection rules. Please wait.

Excluded rules: 26
Noisy rules: 12 (Disabled)

Deprecated rules: 214 (4.96%) (Disabled)
Experimental rules: 375 (8.70%)
Stable rules: 241 (5.59%)
Test rules: 3,696 (85.71%)
Unsupported rules: 42 (0.97%) (Disabled)

Correlation rules: 3 (0.07%)
Correlation referenced rules: 3 (0.07%)

Expand rules: 8 (0.07%)
Enabled expand rules: 0 (0%)

Hayabusa rules: 175
Sigma rules: 4,137
Total detection rules: 4,312
```

By default, since the expand config files need to be created, there should be 0 enabled expand rules.

I am thinking about creating 2 `expand` commands: One to list up the expand placeholder names and one to create lists to use in the expand config files. I will create separate issues for these.

@fukusuket This one is a little difficult, but do you think you could do this one?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #1434 

### Integration-Test
- https://github.com/Yamato-Security/hayabusa/actions/runs/12215234662

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Test
```yaml
title: TEST
id: f8d98d6c-7a07-4d74-b064-dd4a3c244521
status: test
description: test
author: TEST
date: 2024-12-07
logsource:
    product: windows
    service: security
    definition: TEST
detection:
    selection:
        Channel: Security
        EventID: 4624
        LogonType|expand: '%LogonType%'
    condition: selection
level: informational
```

```
% less ./config/expand/LogonType.txt
10
5
```

```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r test.yml -o timeline.csv -q -C
Start time: 2024/12/08 02:57
Total event log files: 598
Total file size: 139.2 MB

Loading detection rules. Please wait.


Test rules: 1 (100.00%)

Expand rules: 0 (0.00%)
Enabled expand rules: 0 (0.00%)

Other rules: 1
Total detection rules: 1

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 248
Detection rules enabled after channel filter: 1

Output profile: standard

Scanning in progress. Please wait.

[00:00:00] 248 / 248   [========================================] 100%

Scanning finished. Please wait while the results are being saved.
                                                                                                                                               Rule Authors:

╭──────────╮
│ TEST (1) │
╰──────────╯

Results Summary:

Events with hits / Total events: 439 / 26,393 (Data reduction: 25,954 events (98.34%))

Total | Unique detections: 439 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (100.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 439 (100.00%) | 1 (0.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: 2013-10-24 (207)

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: IE10Win7 (1), MSEDGEWIN10 (1), 01566s-win16-ir.threebeesco.com (1), PC01.example.corp (1), 37L4247D28-05 (1)

╭──────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts: │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ TEST (439)                  n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
╰───────────────────────────╌──────────────────╯

Saved file: timeline.csv (223.8 KB)

Elapsed time: 00:00:00.877

Please report any issues with Hayabusa rules to: https://github.com/Yamato-Security/hayabusa-rules/issues
Please report any false positives with Sigma rules to: https://github.com/SigmaHQ/sigma/issues
Please submit new Sigma rules with pull requests to: https://github.com/SigmaHQ/sigma/pulls
```

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! Looks good but it is not working for me. Can you tell me what I might be doing wrong?

`~/Desktop/test.yml`:
```
title: TEST
id: f8d98d6c-7a07-4d74-b064-dd4a3c244521
status: test
description: test
author: TEST
date: 2024-12-07
logsource:
    product: windows
    service: security
    definition: TEST
detection:
    selection:
        Channel: Security
        EventID: 4624
        LogonType|expand: '%LogonType%'
    condition: selection
level: informational
```

```
cat config/expand/LogonType.txt
10
5
```

```
./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ~/Desktop/test.yml -q
Start time: 2024/12/09 14:44
Total event log files: 598
Total file size: 139.2 MB

Loading detection rules. Please wait.


Test rules: 1 (100.00%)

Expand rules: 1 (100.00%)
Enabled expand rules: 0 (0.00%)

Other rules: 1
Total detection rules: 1

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 248
Detection rules enabled after channel filter: 1

Output profile: standard

Scanning in progress. Please wait.

Scanning finished.


Results Summary:

Events with hits / Total events: 0 / 26,393 (Data reduction: 26,393 events (100.00%))

Total | Unique detections: 0 | 0
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 0 (0.00%) | 0 (0.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: n/a

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: n/a
```

`Enabled expand rules` is still 0.

An issue beside this not working is that this expand rule is not enabled but we still get:
```
Evtx files loaded after channel filter: 248
Detection rules enabled after channel filter: 1
```

Shouldn't `Detection rules enabled after channel filter` also be 0 in this case?

**Comment by YamatoSecurity** [comment]
> Would it work if you put it on the same folder hierarchy as the release binary?

That was the issue, thanks so much! LGTM!

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Great job! Works perfect!

**Pull request merged**
