### PR TITLE
fix: output correlation(and referenced) rule count

### LINKED ISSUE #1374: Output correlation and correlation referenced rules count
Right now, when correlation rules are used, the following output is shown:

```
Loading detection rules. Please wait.


Undefined rules: 3 (100.00%)

Other rules: 3
Total detection rules: 3
```

It would be better to show as:
```
Loading detection rules. Please wait.

Correlation rules: 1 (xx.xx%)
Correlation referenced rules: 2 (xx.xx%)

Total detection rules: 3
```

@fukusuket could you look into this one since you are doing correlations?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #1374 

### csv-timeline/json-timeline diff check (compared with main branch)
No difference in the result file compared to the main branch.
https://github.com/Yamato-Security/hayabusa/actions/runs/10035816024

### Integration-test
All commands work properly.
https://github.com/Yamato-Security/hayabusa/actions/runs/10035814364

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### correlation rule(no ruletype and no status)
```yaml
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d
    - e87bd730-df45-4ae9-85de-6c75369c5d29
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
---
title: Logon Failure (User Does Not Exist)
description: Prints failed logons

id: 8afa97ce-a217-4f7c-aced-3e320a57756d
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
---
title: Logon Failure (Wrong Password)
description: Prints logon information.

id: e87bd730-df45-4ae9-85de-6c75369c5d29
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
```

```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -q -o out.csv -C -r test
Start time: 2024/07/22 15:48

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.


Undefined rules: 3 (100.00%)

Correlation rules: 1 (33.33%)
Correlation referenced rules: 2 (66.67%)

Other rules: 3
Total detection rules: 3

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 241
Detection rules enabled after channel filter: 1

Output profile: standard
```

**Comment by fukusuket** [comment]
### correlation rule(with ruletype and status)
```yaml
title: Value Count TEST
id: 0e95725d-7320-415d-80f7-004da920fc11
level: informational
correlation:
  type: value_count
  rules:
    - 8afa97ce-a217-4f7c-aced-3e320a57756d
    - e87bd730-df45-4ae9-85de-6c75369c5d29
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 2
    field: SubStatus
ruletype: Hayabusa
status: stable
---
title: Logon Failure (User Does Not Exist)
description: Prints failed logons

id: 8afa97ce-a217-4f7c-aced-3e320a57756d
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_user_not_exist:
    SubStatus: "0xc0000064" #Username does not exist error
  condition: selection_basic and selection_user_not_exist
ruletype: Hayabusa
status: stable
---
title: Logon Failure (Wrong Password)
description: Prints logon information.

id: e87bd730-df45-4ae9-85de-6c75369c5d29
logsource:
  product: windows
  service: security
detection:
  selection_basic:
    Channel: Security
    EventID: 4625
  selection_wrong_password:
    SubStatus: "0xc000006a" #Wrong password
  condition: selection_basic and selection_wrong_password
ruletype: Hayabusa
status: stable
```

```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -q -o out.csv -C -r test
Start time: 2024/07/22 15:55

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.


Stable rules: 3 (100.00%)

Correlation rules: 1 (33.33%)
Correlation referenced rules: 2 (66.67%)

Hayabusa rules: 3
Total detection rules: 3

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 241
Detection rules enabled after channel filter: 1

Output profile: standard

Scanning in progress. Please wait.
```

**Comment by fukusuket** [comment]
### Default rule count
There is no diff count main and This PR.

main
https://github.com/Yamato-Security/hayabusa/actions/runs/10035985161/job/27732894205

This PR
https://github.com/Yamato-Security/hayabusa/actions/runs/10035814364/job/27732439361

**Review by hitenkoku — APPROVED** [review]

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
