### PR TITLE
Added error message to indicate that trailing backslashes should not be used in a directory path specification

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Added error message to indicate that trailing backslashes should not be used in a directory path specification

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Review by fukusuket — CHANGES_REQUESTED** [review]
@hitenkoku 
I tried running the command below, but the error still seems to occur🤔Could you please confirm?
```
PS C:\tmp\hayabusa-2.8.0-win-64-bit> .\hayabusa.exe csv-timeline -d "C:\tmp\data with space\EVTX-to-MITRE-Attack\TA0001-Initial access\T1078-Valid accounts\" -o out.csv -C

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2023/09/03 08:57

[ERROR] No .evtx files were found.

Elapsed time: 00:00:00.015
Errors were generated. Please check ./logs/errorlog-20230903_085719.log for details.


PS C:\tmp\hayabusa-2.8.0-win-64-bit> dir "C:\tmp\data with space\EVTX-to-MITRE-Attack\TA0001-Initial access\T1078-Valid accounts\"


    ディレクトリ: C:\tmp\data with space\EVTX-to-MITRE-Attack\TA0001-Initial access\T1078-Valid accounts


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023/05/08     22:18          69632 ID1149-RDP success logins to multiple hosts.evtx
-a----        2023/05/08     22:18          69632 ID33205-SQL Server failed login with disabled SA account.evtx
-a----        2023/05/08     22:18          69632 ID4625-failed login with denied access due to account restriction.evtx


PS C:\tmp\hayabusa-2.8.0-win-64-bit> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
user input: "C:\\tmp\\hayabusa-2.8.0-win-64-bit\\hayabusa.exe csv-timeline -d C:\\tmp\\data with space\\EVTX-to-MITRE-Attack\\TA0001-Initial access\\T1078-Valid accounts\" -o out.csv -C"
[ERROR] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。 (os error 123)
```

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your review.
I apologize that I forgot output to log file.
I fixed following problem,

Could you check it?

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you for quick fix :) I confirmed following error msg. LGTM!!🚀
```
user input: C:\tmp\hayabusa-2.8.0-win-64-bit\hayabusa.exe csv-timeline -d C:\tmp\data with space\EVTX-to-MITRE-Attack\TA0001-Initial access\T1078-Valid accounts" -o out.csv -C
[ERROR] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。 (os error 123). When specifying a directory path in Windows, do not include a trailing slash at the end of the path.
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thanks so much!

**Pull request merged**
