### PR TITLE
Fixed Data in AccessMask field are not separated by spaces in the details field

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Fixed Data in AccessMask field are not separated by spaces in the details field

## Evidence

- main

```
 >./main.exe csv-timeline -d "../hayabusa-sample-evtx\EVTX-to-MITRE-Attack\TA0005-Defense Evasion" -m medium
...
2021-11-23 18:26:30.152 +09:00 ‖ fs03vuln.offsec.lan ‖ Sec ‖ 4674 ‖ med ‖ 937767 ‖ SCM Database Privileged Operation ‖ Svc: ServicesActive ¦ User: admmig ¦ AccessMask: %%1537%%1538%%1539%%7168%%7169%%7170%%7171%%7172%%7173 ¦ LID: 0x8157b29
...
```

- this PR

```
 >./1035.exe csv-timeline -d "../hayabusa-sample-evtx\EVTX-to-MITRE-Attack\TA0005-Defense Evasion" -m medium
...
2021-11-23 18:26:30.152 +09:00 ‖ fs03vuln.offsec.lan ‖ Sec ‖ 4674 ‖ med ‖ 937767 ‖ SCM Database Privileged Operation ‖ Svc: ServicesActive ¦ User: admmig ¦ AccessMask: %%1537 %%1538 %%1539 %%7168 %%7169 %%7170 %%7171 %%7172 %%7173 ¦ LID: 0x8157b29
...
```

**Note:** This modification was made only for the AcccessMask, because if it was made for Script-Block, etc., all line feed characters would be lost as well.

I would appreciate it if you could review🙇

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku 
Thank you!
Could you explain more about this?
> This modification was made only for the AcccessMask, because if it was made for Script-Block, etc., all line feed characters would be lost as well.
In PowerShell ScriptBlock logs as well, I want to get rid of all whitespace (including line feeds) and replace them with a single space. (We did that in a previous PR, right?)
Can you post a screenshot of an example of what happens if we try to fix this universally?
I only noticed no spaces in the AccessMask field but there may be other fields that have this problem so I would like to fix it universally and not just a special exception for AccessMask.
Or do you know if there is a reason that only AccessMask has this problem?

Sorry, I still don't understand the reason of why there are no spaces to begin with.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your comment.
We have revised it again and modified it to work for other field values as well.

Please check it out.

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks so much! `csv-timeline` terminal output and CSV file output look good. However, it seems that the new line characters and tabs are deleted in `json-timeline` as well. For `json-timeline`, I would like the logs to be saved as they are originally. We want to preserve all the whitespace, tabs, newlines for JSON only.

**Comment by hitenkoku** [comment]
@YamatoSecurity 
Sorry for the delay in confirmation.

I left spaces and tabs only when json-timeline at https://github.com/Yamato-Security/hayabusa/pull/1043/commits/addcfc987a88d56a1ed12fad9dd488f1726a422b I fixed it so that only spaces and tabs are left in json-timeline

Could you check it?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku I checked it and everything LGTM! Thanks so much!

**Comment by hitenkoku** [comment]
Thank you for your confirmation!

I will merge it.

**Pull request merged**
