### PR TITLE
fix: add another backslash before the asterisk when rule ends with a backslash

### LINKED ISSUE #1025: [bug] A rule whose last character is a backslash does not detect logs correctly
**Describe the bug**
A rule like the one below with a `backslash as the last character` does not detect logs correctly 🤔
```
e.g.
detection:
    selection:
        EventID: 1040
        Data|startswith: C:\Windows\
    condition: selection
```

**Step to Reproduce**

1. Create following rule and save the file as `test.yml`
  ```
  title: TEST
  id: 66366687-b855-4e12-a353-71cc52351cab
  status: test
  author: TEST
  date: 2023/05/02
  logsource:
      product: windows
      service: application
  detection:
      selection:
          EventID: 1040
          Data|startswith: C:\Windows\
      condition: selection
  falsepositives: unknown
  level: low
  ```
2. Execute following command.
  ```.\hayabusa-2.4.0-win-x64.exe csv-timeline -f C:\tmp\hayabusa-sample-evtx\DeepBlueCLI\many-events-application.evtx -r C:\tmp\test.yml  ```

**Expected behavior**
Logs containing `C:\Windows\` are detected. (`44` detections)

**Actual behavior**
Nothing detected.

**Environment**

- OS:  `Windows 10 Version 22H2`
- hayabusa version ~`v.2.4.0`
  - I was able to reproduce this issue with `v1.8.1` as well. It seems to be an issue since the initial release.

**Additional context**
The following rules also does not detect logs with hayabusa-sample-evtx, so it's a problem that happens regardless of fields or logs. It also happened with `contains`, not just `startswith`.
```
title: TEST2
id: d0edff07-38f9-4875-a407-2ad5d0c13f31
status: test
author: TEST2
date: 2023/05/02
logsource:
    product: windows
    category: process_creation
detection:
    selection:
        EventID: 1
        Channel: Microsoft-Windows-Sysmon/Operational
        ParentImage|contains: C:\Windows\
    condition: selection
falsepositives: unknown
level: low
```

e.g.(Example of rules affected by this issue in the Sigma repo)
- [SigmaHQ/sigma: win_msi_install_from_susp_locations.yml](https://github.com/SigmaHQ/sigma/blob/ef95e5278d9130de2a00c948156f05b959acfd02/rules/windows/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml)
  - but rules converted by `hayabusa-rules/converter.py` are not affected as they convert `startswith/contains` into `wildcard pattern`

I will investigate the cause some more 🤔

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Fixed #1025
- Add another backslash before the asterisk when rule ends with a backslash
  - e.g  `..|startswith: C:\Windows\` convert into(internally) `..: C:\Windows\\*`
    - and then `..:  C:\Windows\\*` convert into(internally) `..:  (?i)C:\\Windows\\(.|\a|\f|\t|\n|\r|\v)*`(regex)

### Environment 
- OS:  `Windows 10 Version 22H2`

### Test1
with steps to reproduce #1025,
```
title: TEST
id: 66366687-b855-4e12-a353-71cc52351cab
status: test
author: TEST
date: 2023/05/02
logsource:
    product: windows
    service: application
detection:
    selection:
        EventID: 1040
        Data|startswith: C:\Windows\
    condition: selection
falsepositives: unknown
level: low
```

`.\hayabusa-2.4.0-win-x64.exe csv-timeline -f C:\tmp\hayabusa-sample-evtx\DeepBlueCLI\many-events-application.evtx -r C:\tmp\test.yml`  detects `44` application logs as follows.

```
Rule Authors:

╭──────────╮
│ TEST (1) │
╰──────────╯

Results Summary:

First Timestamp: 2013-10-24 01:16:29.000 +09:00
Last Timestamp: 2016-09-20 22:15:31.000 +09:00

Events with hits / Total events: 44 / 2,216 (Data reduction: 2,172 events (98.01%))

Total | Unique detections: 44 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 44 (100.00%) | 1 (100.00%)
Total | Unique informational detections: 0 (0.00%) | 0 (0.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: 2016-09-03 (17), informational: n/a

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: IE10Win7 (1), IE8Win7 (1)
informational: n/a

╭──────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts: │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         TEST (44)        │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
╰───────────────────────────╌──────────────────╯

Saved file: out.csv (6.7 KB)
Elapsed time: 00:00:00.164
```

### Test2
with steps to reproduce #1025, following rule also detects `44` logs.
```
        Data|contains: C:\Windows\
```

### Test3
with steps to reproduce #1025, following rule also detects `0` logs.
```
        Data|contains: C:\NOTEXISTS\
```

I would appreciate it if you could review🙇

### CODE REVIEW

**Review by hitenkoku — APPROVED** [review]
Thanks for your pull request.

LGTM.

**Comment by hitenkoku** [comment]
I updated CHANGELOG.
I confirmed that the results of this exe for PR were no decreased in the number of detected cases from the results of the exe for the main branch.

**Comment by YamatoSecurity** [comment]
@fukusuket 
Thanks always for the quick fixes!!
Should we be changing the regular expressions as well?
I now get 4 parse errors with this PR:
```
cat ./logs/errorlog-20230503_054140.log
user input: ./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx
[WARN] Failed to parse rule file. (FilePath : rules/sigma/sysmon/registry/registry_set/registry_set_uac_bypass_sdclt.yml)
[WARN] Cannot parse regex. [regex:-1[0-9]{3}\\Software\\Classes\, key:detection -> selection -> Details|re]
[WARN] Failed to parse rule file. (FilePath : rules/sigma/sysmon/process_creation/proc_creation_win_wsl_windows_binaries_execution.yml)
[WARN] Cannot parse regex. [regex:[a-zA-Z]:\, key:detection -> selection -> Image|re]
[WARN] Failed to parse rule file. (FilePath : rules/sigma/builtin/registry/registry_set/registry_set_uac_bypass_sdclt.yml)
[WARN] Cannot parse regex. [regex:-1[0-9]{3}\\Software\\Classes\, key:detection -> selection -> NewValue|re]
[WARN] Failed to parse rule file. (FilePath : rules/sigma/builtin/process_creation/proc_creation_win_wsl_windows_binaries_execution.yml)
[WARN] Cannot parse regex. [regex:[a-zA-Z]:\, key:detection -> selection -> NewProcessName|re]
```

**Comment by YamatoSecurity** [comment]
@fukusuket 
This also seems to break rules that have exact matches and end with `\`.
For example, if I use this test rule:
`./hayabusa-2.4.0-mac-intel  csv-timeline -d ../hayabusa-sample-evtx -r ../hayabusa-rules/test.yml -p all-field-info`

```
detection:
    selection:
        Channel: 'Microsoft-Windows-Sysmon/Operational'
        EventID: 1
        CurrentDirectory: 'C:\Windows\'
    condition: selection
```
Hayabusa 2.4.0: 16 results (correctly matching on `CurrentDirectory: C:\Windows\`)
This PR: 3 results (incorrectly matching on only `CurrentDirectory: C:\Windows`)

Can you fix and write a test for exact match cases as well?

**Comment by YamatoSecurity** [comment]
@fukusuket 
This PR seems to fix another bug as well! That is, when the rule uses `|contains` but the string is located at the beginning, Hayabusa 2.4.0 would not match.
For example:
```
detection:
    selection:
        Channel: 'Microsoft-Windows-Sysmon/Operational'
        EventID: 1
        CurrentDirectory|contains: 'C:\Windows\'
    condition: selection
```
Hayabusa 2.4.0: No matches!
This PR: 728 matches (correct)

However, I found a bug when handling the case of `endswith`:
For example:
```
detection:
    selection:
        Channel: 'Microsoft-Windows-Sysmon/Operational'
        EventID: 1
        CurrentDirectory|endswith: 'system32\'
    condition: selection
```
Hayabusa 2.4.0: 645 matches (correct match on ending with `system32\`)
This PR: 16 matches (incorrect match on ending with `system32`, Example: `CurrentDirectory: C:\Windows\system32`)

Can you also write a test case for this?

**Comment by fukusuket** [comment]
@YamatoSecurity @hitenkoku 
Thank you so much for detailed review :) 
I'm sorry for the regression🙇 It looks like I'll have to take a different approach to fix it, but I'll check it out!

**Comment by fukusuket** [comment]
@YamatoSecurity 
>Should we be changing the regular expressions as well?
>I now get 4 parse errors with this PR:

I couldn't reproduce the above errors in my environment(Win10 and M1 Mac)🤔  Did you make any changes to the 4 rules?
(But I was able to reproduce it,
if changed `NewValue|re: -1[0-9]{3}\\Software\\Classes\\` to `NewValue|re: -1[0-9]{3}\\Software\\Classes\`)

**Comment by fukusuket** [comment]
I also checked following cases, the number of detections was the same for both v2.4.0 and PR🤔 
Could you please check again?🙏(I'm sorry if I overlooked any reproduction conditions...)

> Hayabusa 2.4.0: 16 results (correctly matching on CurrentDirectory: C:\Windows\)
> This PR: 3 results (incorrectly matching on only CurrentDirectory: C:\Windows)

> Hayabusa 2.4.0: 645 matches (correct match on ending with system32\)
> This PR: 16 matches (incorrect match on ending with system32, Example: CurrentDirectory: C:\Windows\system32)

But anyway, it's better to have a test case, so I'll add it!

**Comment by YamatoSecurity** [comment]
> @YamatoSecurity
> 
> > Should we be changing the regular expressions as well?
> > I now get 4 parse errors with this PR:
> 
> I couldn't reproduce the above errors in my environment(Win10 and M1 Mac)🤔 Did you make any changes to the 4 rules? (But I was able to reproduce it, if changed `NewValue|re: -1[0-9]{3}\\Software\\Classes\\` to `NewValue|re: -1[0-9]{3}\\Software\\Classes\`)

Humm... that is very weird..
No I didn't make any changes to the rules. I just ran `update-rules` to sync to the latest and tried again:
`./target/release/hayabusa  csv-timeline -d ../hayabusa-sample-evtx -p all-field-info` but still the same parse errors.

**Comment by YamatoSecurity** [comment]
@fukusuket Oh sorry, It looks like I am using a branch called `1025-bug-a-rule-whose-last-character-is-a-backslash-does-not-detect-logs-correctly`.
but it seems there is another branch that starts with `1025`. Sorry, I got confused because they were the same number.

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Sorry for testing the wrong branch!
I retested everything and all looks good. Thank you!!

**Comment by fukusuket** [comment]
I'm sorry for the confusing branch name🙇 Thank you so much for retesting :)

**Pull request merged**
