### PR TITLE
feat(matchers): added en-dash and other permutations for windash modifier

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- added en-dash and other permutations for windash modifier

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
I confirmed there is no diff between main and this PR!
https://github.com/Yamato-Security/hayabusa/actions/runs/10320299127

Also, I confirmed with following rules!
```yaml
title: Windash TEST
id: 0550d910-7787-4892-9791-c1c6a26ec16a
status: test
author: TEST
logsource:
    product: windows
    category: application
detection:
    selection:
        EventID: 1
        Channel: Application
        Data|contains|windash: "test -a"
    condition: selection
level: informational
```

```
eventcreate /t INFORMATION /id 1 /d "windash test -a "
eventcreate /t INFORMATION /id 1 /d "windash test –a (en dash)"
eventcreate /t INFORMATION /id 1 /d "windash test —a (em dash)"
eventcreate /t INFORMATION /id 1 /d "windash test ―a (horizontal bar) "
eventcreate /t INFORMATION /id 1 /d "windash test /a "
```

```
>hayabusa.exe csv-timeline -l -r test.yml -w
Timestamp · RuleTitle · Level · Computer · Channel · EventID · RecordID · Details · ExtraFieldInfo
2024-08-09 23:06:49.369 +09:00 · Windash TEST · info · mouse · App · 1 · 14711 · Data[1]: windash test -a · Data[1]: windash test -a
2024-08-09 23:06:49.379 +09:00 · Windash TEST · info · mouse · App · 1 · 14712 · Data[1]: windash test -a (en dash) · Data[1]: windash test -a (en dash)
2024-08-09 23:06:49.393 +09:00 · Windash TEST · info · mouse · App · 1 · 14713 · Data[1]: windash test -a (em dash) · Data[1]: windash test -a (em dash)
2024-08-09 23:06:50.370 +09:00 · Windash TEST · info · mouse · App · 1 · 14715 · Data[1]: windash test /a · Data[1]: windash test /a
```
For some reason, only the ― (horizontal bar)  doesn't seem to be a hit🤔 Could you please check?(Sorry if I have made a mistake in the procedure)

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for testing this out! Could you DM @hitenkoku the .evtx file you created so he can test?

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for your comment. I fixed following point outs in https://github.com/Yamato-Security/hayabusa/pull/1393/commits/090e15324170bca63ab03947f1483162933e332c.

Would you recheck it?

> @hitenkoku I confirmed there is no diff between main and this PR! https://github.com/Yamato-Security/hayabusa/actions/runs/10320299127
> 
> Also, I confirmed with following rules!
> 
> ```yaml
> title: Windash TEST
> id: 0550d910-7787-4892-9791-c1c6a26ec16a
> status: test
> author: TEST
> logsource:
>     product: windows
>     category: application
> detection:
>     selection:
>         EventID: 1
>         Channel: Application
>         Data|contains|windash: "test -a"
>     condition: selection
> level: informational
> ```
> 
> ```
> eventcreate /t INFORMATION /id 1 /d "windash test -a "
> eventcreate /t INFORMATION /id 1 /d "windash test –a (en dash)"
> eventcreate /t INFORMATION /id 1 /d "windash test —a (em dash)"
> eventcreate /t INFORMATION /id 1 /d "windash test ―a (horizontal bar) "
> eventcreate /t INFORMATION /id 1 /d "windash test /a "
> ```
> 
> ```
> >hayabusa.exe csv-timeline -l -r test.yml -w
> Timestamp · RuleTitle · Level · Computer · Channel · EventID · RecordID · Details · ExtraFieldInfo
> 2024-08-09 23:06:49.369 +09:00 · Windash TEST · info · mouse · App · 1 · 14711 · Data[1]: windash test -a · Data[1]: windash test -a
> 2024-08-09 23:06:49.379 +09:00 · Windash TEST · info · mouse · App · 1 · 14712 · Data[1]: windash test -a (en dash) · Data[1]: windash test -a (en dash)
> 2024-08-09 23:06:49.393 +09:00 · Windash TEST · info · mouse · App · 1 · 14713 · Data[1]: windash test -a (em dash) · Data[1]: windash test -a (em dash)
> 2024-08-09 23:06:50.370 +09:00 · Windash TEST · info · mouse · App · 1 · 14715 · Data[1]: windash test /a · Data[1]: windash test /a
> ```
> 
> Looking at the Eventviewer XML data, it appears that the `―a (horizontal bar)` has been created.
> 
> ```
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
> <System>
>   <Provider Name="EventCreate" /> 
>   <EventID Qualifiers="0">1</EventID> 
>   <Version>0</Version> 
>   <Level>4</Level> 
>   <Task>0</Task> 
>   <Opcode>0</Opcode> 
>   <Keywords>0x80000000000000</Keywords> 
>   <TimeCreated SystemTime="2024-08-09T14:06:49.4075162Z" /> 
>   <EventRecordID>14714</EventRecordID> 
>   <Correlation /> 
>   <Execution ProcessID="14108" ThreadID="0" /> 
>   <Channel>Application</Channel> 
>   <Computer>mouse</Computer> 
>   <Security UserID="S-1-5-21-2349003748-4255172932-178375392-1002" /> 
>   </System>
> - <EventData>
>   <Data>windash test ―a (horizontal bar)</Data> 
>   </EventData>
>   </Event>
> ```
> 
> For some reason, only the ― (horizontal bar) doesn't seem to be a hit🤔 Could you please check?(Sorry if I have made a mistake in the procedure)

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for quick fix! I confirmed horizontal bar detected as follows! LGTM!!🚀
```
Timestamp · RuleTitle · Level · Computer · Channel · EventID · RecordID · Details · ExtraFieldInfo
2024-08-09 23:06:49.369 +09:00 · Windash TEST · info · mouse · App · 1 · 14711 · Data[1]: windash test -a · Data[1]: windash test -a

2024-08-09 23:06:49.379 +09:00 · Windash TEST · info · mouse · App · 1 · 14712 · Data[1]: windash test -a (en dash) · Data[1]: windash test -a (en dash)

2024-08-09 23:06:49.393 +09:00 · Windash TEST · info · mouse · App · 1 · 14713 · Data[1]: windash test -a (em dash) · Data[1]: windash test -a (em dash)

2024-08-09 23:06:49.407 +09:00 · Windash TEST · info · mouse · App · 1 · 14714 · Data[1]: windash test ―a (horizontal bar) · Data[1]: windash test ―a (horizontal bar)

2024-08-09 23:06:50.370 +09:00 · Windash TEST · info · mouse · App · 1 · 14715 · Data[1]: windash test /a · Data[1]: windash test /a

2024-08-09 23:09:26.231 +09:00 · Windash TEST · info · mouse · App · 1 · 14716 · Data[1]: windash test ―a (horizontal bar) · Data[1]: windash test ―a (horizontal bar)
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thanks so much!

**Pull request merged**
