### PR TITLE
update color scheme

### PR DESCRIPTION
**Pull request by YamatoSecurity**
Closes https://github.com/Yamato-Security/hayabusa/issues/1480

@fukusuket Do you know how to update the colors in the scan wizard? For example, I want to use 0,255,0 green for selected answers, the brighter blue we use for field data unselected answers, etc...

### CODE REVIEW

**Comment by fukusuket** [comment]
@YamatoSecurity 
The color could be changed in the following two places! You can add your favorite color here!
https://github.com/Yamato-Security/hayabusa/pull/1481/commits/5f8fd98142b3b1ef9a5f4337fba8b26bf877fe86

**Review by fukusuket — COMMENTED** [review]
I would appreciate it if you could set the favorite color🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!
Screenshot 2024-11-09 at 07 57 57

I don't know how to change the color for `(y/n)` as well as the darker blue color `yes` / `no` before it is selected. (It looks almost like the `51` cyan but is a little darker and hard to see depending on the monitor.
Do you know how to change these both to `51` cyan?

**Comment by fukusuket** [comment]
@YamatoSecurity 
I updated `(yes/no)`,`yes`,`no` color to `51` cyan!

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! I've updated all the colors. Could you check?

**Comment by fukusuket** [comment]
@YamatoSecurity  Yes, Good color! I checked it. LGTM!!🚀

**Review by fukusuket — APPROVED** [review]

**Pull request merged**
