### PR TITLE
added category filtering

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- added `--include-category`
- added `--exclude-category`

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

- display check

```
> ./1119.exe help csv-timeline
Hayabusa v2.7.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)
Usage:
  hayabusa.exe csv-timeline <INPUT> [OPTIONS]

...
Filtering:
  -E, --EID-filter                   Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
  -D, --enable-deprecated-rules      Enable rules with status of deprecated
  -n, --enable-noisy-rules           Enable rules set to noisy (./rules/config/noisy_rules.txt)
  -u, --enable-unsupported-rules     Enable rules with status of unsupported
  -e, --exact-level <LEVEL>          Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-category <CATEGORY>  Do not load rules with certain logsource categories (ex: process_creation,pipe_created)
      --exclude-status <STATUS>      Ignore rules according to status (ex: experimental) (ex: stable,test)
      --include-category <CATEGORY>  Only load rules with certain logsource categories (ex: process_creation,pipe_created)
  -m, --min-level <LEVEL>            Minimum level for rules (default: informational)
      --tags <TAGS>                  Only load rules with specific tags (ex: attack.execution,attack.discovery)
      --timeline-end <DATE>          End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>        Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")
...
```

- conflict check

```
> ./1119.exe csv-timeline -d ..\hayabusa-sample-evtx\ --include-category process_creation  --exclude-category pipe_created
error: the argument '--include-category <CATEGORY>' cannot be used with '--exclude-category <CATEGORY>'

Usage: 1119.exe csv-timeline --directory <DIR> --include-category <CATEGORY>
```

- result check

  - this PR (without --include-category and --exclude-category)

```
 ./1119.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1119.csv -C -q --debug
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.50%) (Disabled)
Experimental rules: 1973 (53.77%)
Stable rules: 229 (6.24%)
Test rules: 1467 (39.98%)
Unsupported rules: 45 (1.23%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3510
Total enabled detection rules: 3669

Output profile: standard
...

Results Summary:
Events with hits / Total events: 19,642 / 47,472 (Data reduction: 27,830 events (58.62%))

Total | Unique detections: 32,228 | 561
Total | Unique critical detections: 56 (0.17%) | 20 (3.57%)
Total | Unique high detections: 6,043 (18.75%) | 245 (43.67%)
Total | Unique medium detections: 1,894 (5.88%) | 184 (32.80%)
Total | Unique low detections: 6,002 (18.62%) | 56 (9.98%)
Total | Unique informational detections: 18,233 (56.58%) | 56 (9.98%)


Saved file: 1119.csv (32.0 MB)

Elapsed time: 00:00:07.997
Rule Parse Processing Time: 00:00:01.572
Analysis Processing Time: 00:00:05.990
Output Processing Time: 00:00:00.434

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB

 committed:   818.1 MiB     1.3 GiB   886.8 MiB   498.9 MiB

     reset:     0
    purged:   429.8 MiB
   touched:    64.2 KiB     1.1 MiB     3.5 GiB    -3.5 GiB
      ok
  segments:    16          19           9          10
      not all freed!
-abandoned:     0           0           0           0
      ok
   -cached:     0           0           0           0
      ok
     pages:     0           0          33.2 Ki    -33.2 Ki
      ok
-abandoned:     0           0           0           0
      ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     7.2 Ki
    resets:     0
    purges:   310
   threads:    32          32           0          32
      not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     8.001 s
   process: user: 27.515 s, system: 1.015 s, faults: 266022, rss: 687.7 MiB, commit: 797.2 MiB
```

  - this PR (without --include-category)

```
> ./1119.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1119.csv -C -q --debug --include-category process_creation,pipe_created
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 1520
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (7.57%) (Disabled)
Experimental rules: 1175 (53.90%)
Stable rules: 74 (3.39%)
Test rules: 931 (42.71%)
Unsupported rules: 45 (2.06%) (Disabled)

Sigma rules: 2180
Total enabled detection rules: 2180

Output profile: standard

...

Results Summary:
Events with hits / Total events: 1,100 / 47,472 (Data reduction: 46,372 events (97.68%))

Total | Unique detections: 2,109 | 264
Total | Unique critical detections: 17 (0.81%) | 9 (3.41%)
Total | Unique high detections: 720 (34.14%) | 130 (49.24%)
Total | Unique medium detections: 721 (34.19%) | 97 (36.74%)
Total | Unique low detections: 578 (27.41%) | 26 (9.85%)
Total | Unique informational detections: 73 (3.46%) | 2 (0.76%)
...
Saved file: 1119.csv (3.0 MB)

Elapsed time: 00:00:05.031
Rule Parse Processing Time: 00:00:00.688
Analysis Processing Time: 00:00:04.252
Output Processing Time: 00:00:00.089

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB

 committed:   495.4 MiB     1.0 GiB   647.4 MiB   455.0 MiB

     reset:     0
    purged:   344.4 MiB
   touched:    64.2 KiB     1.1 MiB     3.1 GiB    -3.1 GiB
      ok
  segments:    10          18          10           8
      not all freed!
-abandoned:     0           0           0           0
      ok
   -cached:     0           0           0           0
      ok
     pages:     0           0          23.0 Ki    -23.0 Ki
      ok
-abandoned:     0           0           0           0
      ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     4.6 Ki
    resets:     0
    purges:   152
   threads:    32          32           0          32
      not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     5.035 s
   process: user: 15.500 s, system: 0.312 s, faults: 159412, rss: 370.9 MiB, commit: 472.6 MiB
```

  - this PR (with --exclude-category)

```
 ./1119.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1119.csv -C -q --debug --exclude-category process_creation,pipe_created
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 2211
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (11.08%) (Disabled)
Experimental rules: 798 (53.59%)
Stable rules: 155 (10.41%)
Test rules: 536 (36.00%)
Unsupported rules: 45 (3.02%) (Disabled)

Hayabusa rules: 159
Sigma rules: 1330
Total enabled detection rules: 1489

Output profile: standard

...
Results Summary:
Events with hits / Total events: 19,642 / 47,472 (Data reduction: 27,830 events (58.62%))

Total | Unique detections: 30,119 | 297
Total | Unique critical detections: 39 (0.13%) | 11 (3.70%)
Total | Unique high detections: 5,323 (17.67%) | 115 (38.72%)
Total | Unique medium detections: 1,173 (3.89%) | 87 (29.29%)
Total | Unique low detections: 5,424 (18.01%) | 30 (10.10%)
Total | Unique informational detections: 18,160 (60.29%) | 54 (18.18%)
...
Saved file: 1119.csv (29.0 MB)

Elapsed time: 00:00:03.757
Rule Parse Processing Time: 00:00:00.665
Analysis Processing Time: 00:00:02.754
Output Processing Time: 00:00:00.337

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB

 committed:   549.8 MiB     1.1 GiB   832.0 MiB   383.6 MiB

     reset:     0
    purged:   466.6 MiB
   touched:    64.2 KiB     1.4 MiB     2.1 GiB    -2.1 GiB
      ok
  segments:     9          23          17           6
      not all freed!
-abandoned:     0           0           0           0
      ok
   -cached:     0           0           0           0
      ok
     pages:     0           0          21.2 Ki    -21.2 Ki
      ok
-abandoned:     0           0           0           0
      ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     5.5 Ki
    resets:     0
    purges:   189
   threads:    32          32           0          32
      not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     3.761 s
   process: user: 7.859 s, system: 0.281 s, faults: 173051, rss: 395.5 MiB, commit: 502.8 MiB
```

**Review by YamatoSecurity — APPROVED** [review]
LGTM!

**Review by fukusuket — APPROVED** [review]
I confirmed as follows,  LGTM!!🚀
- No unnecessary diffs compared to v2.6.0
- No unnecessary diffs compared to After merging the results of `include` and `exclude`

### csv-timeline
```
hayabusa-2.6.0-all-platforms % ./hayabusa-2.6.0-mac-arm csv-timeline -d ../hayabusa-sample-evtx -o old.csv --debug -C -q
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 csv-timeline -d ../hayabusa-sample-evtx -o new.csv --debug -C -q
```

```
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 csv-timeline -d ../hayabusa-sample-evtx -o new-ex.csv --debug -C -q --exclude-category process_creation
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 csv-timeline -d ../hayabusa-sample-evtx -o new-in.csv --debug -C -q --include-category process_creation

hayabusa-2.6.0-all-platforms % cat new-ex.csv new-in.csv | sort > new-merged.csv
hayabusa-2.6.0-all-platforms % cat new.csv | sort > new-sorted.csv
hayabusa-2.6.0-all-platforms % diff new-merged.csv new-sorted.csv
32215d32214
< "Timestamp","Computer","Channel","EventID","Level","RecordID","RuleTitle","Details","ExtraFieldInfo"
```

### json-timeline
```
hayabusa-2.6.0-all-platforms % ./hayabusa-2.6.0-mac-arm json-timeline -d ../hayabusa-sample-evtx -o old.json --debug -C -q
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 json-timeline -d ../hayabusa-sample-evtx -o new.json --debug -C -q
hayabusa-2.6.0-all-platforms % diff new.json old.json
hayabusa-2.6.0-all-platforms % 
```
```
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 json-timeline -d ../hayabusa-sample-evtx -o new-in.json --debug -C -q --include-category process_creation
hayabusa-2.6.0-all-platforms % ./hayabusa-1123 json-timeline -d ../hayabusa-sample-evtx -o new-ex.json --debug -C -q --exclude-category process_creation

hayabusa-2.6.0-all-platforms % cat new-ex.json new-in.json | sort > new-merged.json
hayabusa-2.6.0-all-platforms % cat new.json | sort > new-sorted.json.txt
hayabusa-2.6.0-all-platforms % diff new-merged.json.txt new-sorted.json.txt
784308a784309
> {
816521c816522
< }{
---
> }
```

**Comment by hitenkoku** [comment]
@YamatoSecurity  @fukusuket Thanks for your check.
I will merge it.

**Pull request merged**
