### PR TITLE
added output search results to json

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Added output search results to json.

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

- option and conflict check
```
>.\1041.exe search -d ..\all-evtx\ -o 1041.json -J -L
error: the argument '--JSON-output' cannot be used with '--JSONL-output'

Usage: 1041.exe search --directory <DIR> --output <FILE> --JSON-output
>.\1041.exe search -d ..\all-evtx\ -J -L
error: the argument '--JSON-output' cannot be used with '--JSONL-output'

Usage: 1041.exe search --output <FILE> --directory <DIR> --JSON-output
>.\1041.exe search -d ..\all-evtx\ -J
error: the following required arguments were not provided:
  --output <FILE>

Usage: 1041.exe search --output <FILE> --directory <DIR> --JSON-output
>.\1041.exe search -d ..\all-evtx\ -L
error: the following required arguments were not provided:
  --output <FILE>

Usage: 1041.exe search --output <FILE> --directory <DIR> --JSONL-output
>.\1041.exe help search
Hayabusa v2.6.0-dev - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
  -v, --verbose   Output verbose information

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live_analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Filtering:
  -F, --filter <FILTER>      Filter by specific field(s)
  -i, --ignore-case          Case-insensitive keyword search
  -k, --keywords <KEYWORDS>  Search by keyword(s)
  -r, --regex <REGEX>        Search by regular expression

Output:
  -J, --JSON-output    Save the search results in JSON format (ex: -J -o results.json)
  -L, --JSONL-output   Save the timeline in JSONL format (ex: -L -o results.jsonl)
  -M, --multiline      Output event field information in multiple rows
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)

General Options:
  -C, --clobber                          Overwrite results files
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
```

- search output (JSON)

```
>.\1041.exe search -d ..\all-evtx\ -o 1041.json -J --debug --keywords "mimikatz" -C
...
Total event log files: 1858
Total file size: 6.1 GB

1858 / 1858 [======================================================================================================================================================================================] 100.00 %

Total findings: 22



Scanning finished. Please wait while the results are being saved.

Metrics results:: 1041.json (17.0 KB)

Elapsed time: 00:01:16.619
Rule Parse Processing Time: 00:00:02.653
Analysis Processing Time: 00:01:13.909
Output Processing Time: 00:00:00.055

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:     7.9 GiB    47.2 GiB    46.6 GiB   562.8 MiB
     reset:     0
    purged:    22.2 GiB
   touched:    64.2 KiB    65.3 MiB    47.2 GiB   -47.1 GiB                          ok
  segments:    16           1.0 Ki      1.0 Ki     11                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0         688.3 Ki   -688.3 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   138.2 Ki
    resets:     0
    purges:     6.4 Ki
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:    76.629 s
   process: user: 46.671 s, system: 3.484 s, faults: 3907526, rss: 581.6 MiB, commit: 641.1 MiB

>cat .\1041.json | jq . > jq-1041.json
>
```

- search output(JSONL)
```
>.\1041.exe search -d ..\all-evtx\ -o 1041.jsonl -L --debug --keywords "mimikatz" -C
...
Total event log files: 1858
Total file size: 6.1 GB

1858 / 1858 [======================================================================================================================================================================================] 100.00 %

Total findings: 22



Scanning finished. Please wait while the results are being saved.

Metrics results:: 1041.jsonl (14.5 KB)

Elapsed time: 00:01:09.759
Rule Parse Processing Time: 00:00:01.046
Analysis Processing Time: 00:01:08.655
Output Processing Time: 00:00:00.056

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB
 committed:     9.2 GiB    46.2 GiB    45.7 GiB   497.8 MiB
     reset:     0
    purged:    21.1 GiB
   touched:    64.2 KiB    65.5 MiB    47.2 GiB   -47.1 GiB                          ok
  segments:    16           1.0 Ki      1.0 Ki     11                                not all freed!
-abandoned:     0           0           0           0                                ok
   -cached:     0           0           0           0                                ok
     pages:     0           0         688.3 Ki   -688.3 Ki                           ok
-abandoned:     0           0           0           0                                ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:   138.7 Ki
    resets:     0
    purges:     6.4 Ki
   threads:    32          32           0          32                                not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:    69.765 s
   process: user: 51.453 s, system: 3.421 s, faults: 3760378, rss: 583.1 MiB, commit: 652.8 MiB
```

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku It is working good for me. Thank you!
@fukusuket Could you check this as well?

**Review by fukusuket — COMMENTED** [review]
@hitenkoku @YamatoSecurity 

I confirmed that the search command results can be output in json/jsonl and able to convert with jq! LGTM!🚀

Sorry, It's not an issue of this PR, ↓
https://github.com/Yamato-Security/hayabusa/blob/main/src/main.rs#L36 
`Metrics results:` is displayed when the search command finished, so is it better to change the msg to `Saved file`?

**Comment by hitenkoku** [comment]
@YamatoSecurity  @fukusuket Thank you for your review.
I have created a separate issue once about fukusuket's suggestion.

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for creating the issue! :)  LGTM!!🚀

**Pull request merged**
