### PR TITLE
feat: `expand-list` command

### LINKED ISSUE #1513: New `expand-list` command
In order to help users understand what `expand` config files they need to create, we should include a command that lists up the placeholders.

```
Usage:
  hayabusa.exe expand-list <INPUT> [OPTIONS]

Input:
  -r, --rules <DIR>  Directory of rules (default: ./rules)

General Options:
  -h, --help                           Show the help menu

Display Settings:
  -K, --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
```

Stdout:
```
5 unique expand placeholders found:

Admins_Workstations
DC-MACHINE-NAME
Workstations
internal_domains
domain_controller_hostnames
```

This command just recursively checks the `.yml` files in `./rules` or the specified rules directory, extracts out `Admins_Workstations`, etc.. from `IpAddress|expand: '%Admins_Workstations%'` and does `sort -u`

@fukusuket Could I ask you to do this one?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #1513 

### Integration-Test
- https://github.com/Yamato-Security/hayabusa/actions/runs/12207593933

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help
```
% ./hayabusa expand-list -h
Hayabusa v3.0.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe expand-list <INPUT> [OPTIONS]

General Options:
  -h, --help              Show the help menu
  -r, --rules <DIR/FILE>  Specify rule directory (default: ./rules)

Display Settings:
  -K, --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
```

**Comment by fukusuket** [comment]
### exapand-rule -r 
```
% ./hayabusa expand-list -r ~/Scripts/Python/sigma

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Giving you the Windows event logs you've always wanted~

Start time: 2024/12/07 08:33

12 unique expand placeholders found:
%Admins_Workstations%
%ApprovedUserUpn%
%ClosingTime%
%DC-MACHINE-NAME%
%LegitCountries%
%UnApprovedDevice%
%UnApprovedIp%
%UnLegitCountries%
%Workstations%
%domain_controller_hostnames%
%internal_domains%
%userdomain%

無念無想 - Munen Musou - No assumptions, no preconceptions.
```

### exapand-rule -r 
```
% ./hayabusa expand-list -r not-exists

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Since 2021~

Start time: 2024/12/07 08:34
[ERROR] The rules directory does not exist. Please check the path.
```

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@fukusuket Thanks so much! I think it will be easier to read without the `%`. What about removing these from the names?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking! I updated it!
```
% ./hayabusa expand-list -r ~/Scripts/Python/sigma

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Getting 80% of the work done in 20% of the time~

Start time: 2024/12/07 21:28

12 unique expand placeholders found:
LegitCountries
ApprovedUserUpn
ClosingTime
DC-MACHINE-NAME
domain_controller_hostnames
Admins_Workstations
UnApprovedDevice
UnApprovedIp
Workstations
internal_domains
UnLegitCountries
userdomain

困難に道あり - Konnan Ni Michi Ari - The obstacle is the way.
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
