### PR TITLE
added output which output profile is used

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- added profile name on stdout output which output profile is used
- added profile name on HTML output which output profile is used

I would appreciate it if you could review when you have time

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

- main

```
> ./main.exe csv-timeline -d ..\hayabusa-sample-evtx\ -H main-standard.html -o main.csv
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 30
Noisy rules: 7 (Disabled)

Deprecated rules: 164 (4.47%) (Disabled)
Experimental rules: 1948 (53.12%)
Stable rules: 225 (6.14%)
Test rules: 1488 (40.58%)
Undefined rules: 6 (0.16%)
Unsupported rules: 43 (1.17%) (Disabled)

Hayabusa rules: 152
Sigma rules: 3515
Total enabled detection rules: 3667

Scanning in progress. Please wait.

584 / 584 [==================================================================================================================================================================================================] 100.00 %  

Scanning finished. Please wait while the results are being saved.

Rule Authors: 
...
Results Summary:

First Timestamp: 2009-07-14 13:56:45.074 +09:00
Last Timestamp: 2023-01-24 20:54:42.899 +09:00

Events with hits / Total events: 19,663 / 47,472 (Data reduction: 27,809 events (58.58%))

Total | Unique detections: 32,109 | 622
Total | Unique critical detections: 55 (0.17%) | 21 (3.38%)
Total | Unique high detections: 6,047 (18.83%) | 277 (44.53%)
Total | Unique medium detections: 1,874 (5.84%) | 201 (32.32%)
Total | Unique low detections: 6,002 (18.69%) | 70 (11.25%)
Total | Unique informational detections: 18,131 (56.47%) | 53 (8.52%)
...

Saved file: main.csv (32.0 MB)
HTML report: main-standard.html
Elapsed time: 00:00:07.908
```
- main-standard.html
image

- this PR
```
a> ./1055.exe csv-timeline -d ..\hayabusa-sample-evtx\ -H 1055-standard.html -o 1055.csv
...

Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 30
Noisy rules: 7 (Disabled)

Deprecated rules: 164 (4.47%) (Disabled)
Experimental rules: 1948 (53.12%)
Stable rules: 225 (6.14%)
Test rules: 1488 (40.58%)
Undefined rules: 6 (0.16%)
Unsupported rules: 43 (1.17%) (Disabled)

Hayabusa rules: 152
Sigma rules: 3515
Total enabled detection rules: 3667


Output profile: standard


Scanning in progress. Please wait.

584 / 584 [==================================================================================================================================================================================================] 100.00 % 

Scanning finished. Please wait while the results are being saved.

Rule Authors: 
...
Results Summary:

First Timestamp: 2009-07-14 13:56:45.074 +09:00
Last Timestamp: 2023-01-24 20:54:42.899 +09:00

Events with hits / Total events: 19,663 / 47,472 (Data reduction: 27,809 events (58.58%))

Total | Unique detections: 32,109 | 622
Total | Unique critical detections: 55 (0.17%) | 21 (3.38%)
Total | Unique high detections: 6,047 (18.83%) | 277 (44.53%)
Total | Unique medium detections: 1,874 (5.84%) | 201 (32.32%)
Total | Unique low detections: 6,002 (18.69%) | 70 (11.25%)
Total | Unique informational detections: 18,131 (56.47%) | 53 (8.52%)

...
Saved file: 1055.csv (32.0 MB)
HTML report: 1055-standard.html
Elapsed time: 00:00:08.182

```

- 1055-standard.html

image

**Review by fukusuket — APPROVED** [review]
I copied `config/default_profile_name.txt` and I have checked the following :) LGTM!!🚀

- The profile is displayed in the stdout when the `json-timeline`
- After executing `set-default-profile minimal`, the changed profile is displayed.

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@hitenkoku Thank you!
Right now there are two spaces before and after:
```
Hayabusa rules: 152
Sigma rules: 3482
Total enabled detection rules: 3634


Output profile: standard


Scanning in progress. Please wait.
```

Can you change it to only one space?:
```
Hayabusa rules: 152
Sigma rules: 3482
Total enabled detection rules: 3634

Output profile: standard

Scanning in progress. Please wait.
```

**Comment by YamatoSecurity** [comment]
Screen Shot 2023-05-31 at 6 39 22 AM

Sorry, one more thing. The spaces between results in the top section is now big. Can you make it the same height as `Results Summary`?

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your review.

I fixed your point out at https://github.com/Yamato-Security/hayabusa/pull/1064/commits/7a028952681cf618802e143ac392b19522f83bca and https://github.com/Yamato-Security/hayabusa/pull/1064/commits/cc29cf16f91de5e65e16068bc297090f1f807657 .

Would you check it?

**Review by YamatoSecurity — APPROVED** [review]
LGTM!
Thanks so much! I changed the wording of the title in the HTML report. Please check.
It said "Top critical alerts", etc... but since it is displaying all alerts (not just the top 10, etc..) I changed the wording to "All xxxx alerts"

**Comment by hitenkoku** [comment]
@YamatoSecurity Thanks for your review! I checked HTML title changed.  LGTM.

@fukusuket 
Thanks for your review. I'll merge it.

**Comment by hitenkoku** [comment]
adjusted https://github.com/Yamato-Security/hayabusa/pull/1064/commits/1be95819a17ebabaac7355cec98ee062e3d3d750 id change  in https://github.com/Yamato-Security/hayabusa/pull/1064/commits/4f5b242ca535beb5f1b82d7156e8f9c2ad99ce08

**Pull request merged**
