### PR TITLE
1088 speed up results summary calculation

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Reverted MESSAGEKEYS DashMap to HashMap

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@hitenkoku 1.8GBのデータで試したところ、あいにく変わりませんでした。

**Comment by hitenkoku** [comment]
@YamatoSecurity  I merged #1090 . Would you check it?

```
 >.\1088-test3.exe csv-timeline -d ..\all-evtx\ --debug -u -D -p super-verbose -o 1088.csv -C
...
Total event log files: 1858
Total file size: 6.1 GB
Saved file: 1088.csv (1.7 GB)
...
Elapsed time: 00:04:35.649
Rule Parse Processing Time: 00:00:01.932
Analysis Processing Time: 00:04:13.716
Output Processing Time: 00:00:19.998
```

**Comment by hitenkoku** [comment]
@YamatoSecurity Thanks for your check.
hmm... I will continue to improve...

**Review by YamatoSecurity — APPROVED** [review]
LGTM! It is now faster than 2.5.1 in my tests.
@fukusuket Can you check this as well?

**Review by fukusuket — APPROVED** [review]
I confirmed that the output time of 6.1GB data is almost the same as v2.5.1. Great! :) LGTM!!🚀

**Comment by hitenkoku** [comment]
@YamatoSecurity  @fukusuket Thank you very much for your confirmation.

**Pull request merged**
