### PR TITLE
added clobber option and fixed file exist check bug

### PR DESCRIPTION
**Pull request by hitenkoku**
…g in pivot-keywords-list #1125

## What Changed

- added `-C | --clobber` option to `pivot-keywords-list` command.
- fixed file exist check bug in `pivot-keywords-list` command.

### CODE REVIEW

**Review by fukusuket — APPROVED** [review]
I confirmed -C option and error message :) LGTM!!🚀

**Comment by hitenkoku** [comment]
## Evidence

### main

- help output

<details>
<summary> result </summary>

```
> .\main.exe help pivot-keywords-list
Hayabusa v2.7.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe pivot-keywords-list <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live_analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
  -J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)

Output:
  -o, --output <FILENAMES-BASE>  Save pivot words to separate files (ex: PivotKeywords)

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
  -v, --verbose   Output verbose information

Filtering:
  -E, --EID-filter                Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
  -D, --enable-deprecated-rules   Enable rules with status of deprecated
  -n, --enable-noisy-rules        Enable rules set to noisy (./rules/config/noisy_rules.txt)
  -u, --enable-unsupported-rules  Enable rules with status of unsupported
  -e, --exact-level <LEVEL>       Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>   Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>         Minimum level for rules (default: informational)
      --timeline-end <DATE>       End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>     Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

General Options:
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
```

</details>

- file name duplicated
<details>
<summary> result </summary>

```
>  .\main.exe pivot-keywords-list -d ..\hayabusa-sample-evtx\ -o test -q                                                                    

Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.49%) (Disabled)
Experimental rules: 1973 (53.67%)
Stable rules: 233 (6.34%)
Test rules: 1470 (39.99%)
Unsupported rules: 45 (1.22%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3517
Total enabled detection rules: 3676

Output profile: standard

Scanning in progress. Please wait.

584 / 584 [========================================================================================================================] 100.00 %

Scanning finished. Please wait while the results are being saved.

Pivot keyword results were saved to the following files:
test-Source Computers.txt
test-Subject Users.txt
test-Target Users.txt
test-Users.txt
test-Subject Logon IDs.txt
test-Target Logon IDs.txt
test-Logon IDs.txt
test-IP Addresses.txt
test-Source IP Addresses.txt
test-Target IP Addresses.txt
test-Processes.txt
test-Command Lines.txt

Elapsed time: 00:00:07.043
>  .\main.exe pivot-keywords-list -d ..\hayabusa-sample-evtx\ -o test -q
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.49%) (Disabled)
Experimental rules: 1973 (53.67%)
Stable rules: 233 (6.34%)
Test rules: 1470 (39.99%)
Unsupported rules: 45 (1.22%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3517
Total enabled detection rules: 3676

Output profile: standard

Scanning in progress. Please wait.

584 / 584 [========================================================================================================================] 100.00 %

Scanning finished. Please wait while the results are being saved.

Pivot keyword results were saved to the following files:
test-Source Computers.txt
test-Subject Users.txt
test-Target Users.txt
test-Users.txt
test-Subject Logon IDs.txt
test-Target Logon IDs.txt
test-Logon IDs.txt
test-IP Addresses.txt
test-Source IP Addresses.txt
test-Target IP Addresses.txt
test-Processes.txt
test-Command Lines.txt

Elapsed time: 00:00:07.045
```

</details>

### This PR


- help output

<details>
<summary> result </summary>

```
>  .\1125.exe help pivot-keywords-list
Hayabusa v2.7.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)

Usage:
  hayabusa.exe pivot-keywords-list <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live_analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
  -J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)

Output:
  -o, --output <FILENAMES-BASE>  Save pivot words to separate files (ex: PivotKeywords)

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
  -v, --verbose   Output verbose information

Filtering:
  -E, --EID-filter                Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
  -D, --enable-deprecated-rules   Enable rules with status of deprecated
  -n, --enable-noisy-rules        Enable rules set to noisy (./rules/config/noisy_rules.txt)
  -u, --enable-unsupported-rules  Enable rules with status of unsupported
  -e, --exact-level <LEVEL>       Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>   Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>         Minimum level for rules (default: informational)
      --timeline-end <DATE>       End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>     Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

General Options:
  -C, --clobber                          Overwrite results files
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
```
</details>

- file name duplicated

<details>
<summary>result</summary>

```
 > .\1125.exe pivot-keywords-list -d ..\hayabusa-sample-evtx\ -o 1125 -q                                                      
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.49%) (Disabled)
Experimental rules: 1973 (53.67%)
Stable rules: 233 (6.34%)
Test rules: 1470 (39.99%)
Unsupported rules: 45 (1.22%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3517
Total enabled detection rules: 3676

Output profile: standard

Scanning in progress. Please wait.

584 / 584 [========================================================================================================================] 100.00 %

Scanning finished. Please wait while the results are being saved.

Pivot keyword results were saved to the following files:
1125-Source Computers.txt
1125-Subject Users.txt
1125-Target Users.txt
1125-Users.txt
1125-Subject Logon IDs.txt
1125-Target Logon IDs.txt
1125-Logon IDs.txt
1125-IP Addresses.txt
1125-Source IP Addresses.txt
1125-Target IP Addresses.txt
1125-Processes.txt
1125-Command Lines.txt

Elapsed time: 00:00:07.059
>  .\1125.exe pivot-keywords-list -d ..\hayabusa-sample-evtx\ -o 1125 -q

[ERROR]  The file 1125-Source Computers.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Subject Users.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Target Users.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Users.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Subject Logon IDs.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Target Logon IDs.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Logon IDs.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-IP Addresses.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Source IP Addresses.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Target IP Addresses.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Processes.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.
[ERROR]  The file 1125-Command Lines.txt already exists. Please specify a different filename or add the -C, --clobber option to overwrite.

>  .\1125.exe pivot-keywords-list -d ..\hayabusa-sample-evtx\ -o 1125 -q -C

Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.49%) (Disabled)
Experimental rules: 1973 (53.67%)
Stable rules: 233 (6.34%)
Test rules: 1470 (39.99%)
Unsupported rules: 45 (1.22%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3517
Total enabled detection rules: 3676

Output profile: standard

Scanning in progress. Please wait.

584 / 584 [========================================================================================================================] 100.00 %

Scanning finished. Please wait while the results are being saved.

Pivot keyword results were saved to the following files:
1125-Source Computers.txt
1125-Subject Users.txt
1125-Target Users.txt
1125-Users.txt
1125-Subject Logon IDs.txt
1125-Target Logon IDs.txt
1125-Logon IDs.txt
1125-IP Addresses.txt
1125-Source IP Addresses.txt
1125-Target IP Addresses.txt
1125-Processes.txt
1125-Command Lines.txt

Elapsed time: 00:00:07.100
```

</details>

**Review by YamatoSecurity — APPROVED** [review]
LGTM! Thank you for supporting this command as well.

**Comment by hitenkoku** [comment]
@fukusuket  @YamatoSecurity  Thanks for your quick review.
I will merge it.

**Pull request merged**
