### PR TITLE
enabled low memory mode by default

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- enabled low memory mode by default

I would appreciate it if you could check it out when you have time

### CODE REVIEW

**Review by fukusuket — APPROVED** [review]
I confirmed that it works :) LGTM!!🚀
#### hayabusa-sample-evtx
```
%./hayabusa-2.16.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -D -n -u -q -w -o old.csv --debug
%./hayabusa-low-memory csv-timeline -d ../hayabusa-sample-evtx -D -n -u -q -w -o new.csv --debug -s
%diff old.csv new.csv

```
#### all-evtx
##### 2.16.0
```
% ./hayabusa-2.16.0-mac-aarch64 csv-timeline -d ../all-evtx -D -n -u -q -w -o old-big.csv --debug
Rule Parse Processing Time: 00:00:01.799
Analysis Processing Time: 00:08:03.302
Output Processing Time: 00:01:58.302

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:    16.0 GiB    17.1 GiB     1.1 GiB    16.0 GiB
```

##### This PR
```
% ./hayabusa-low-memory csv-timeline -d ../all-evtx -D -n -u -q -w --debug -o new-big.csv
...
Rule Parse Processing Time: 00:00:01.911
Analysis Processing Time: 00:08:57.270
Output Processing Time: 00:00:00.112

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     5.2 GiB     5.3 GiB   384.0 MiB     5.0 GiB
```

**Comment by fukusuket** [comment]
Unrelated to this PR, but since memory usage has increased since low-memory was released, I will look into this as a separate issue. (In version 2.13.0, memory usage was 5 GB as shown below🤔)
- https://github.com/Yamato-Security/hayabusa/pull/1292#pullrequestreview-1912925159

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! When low memory mode in enabled, we shouldn't be able to use `-R, --remove-duplicate-data` and `-X, --remove-duplicate-detections`, right? I can still add these options without getting an error so could you configure it so that `-R` and `-X` require the option `-s`?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Sorry, I figured out the bug, `requires = "sort-events"` needed to be `requires = "sort_events"` so I just updated it.

**Pull request merged**
