### PR TITLE
change license to AGPL

### PR DESCRIPTION
**Pull request by YamatoSecurity**
I change the license to AGPL. Please check whenever you have time.

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@YamatoSecurity 
We need to change the following two points in README? Other than that, I think it's OK!
- https://github.com/Yamato-Security/hayabusa/tree/change-license?tab=readme-ov-file#license
- https://github.com/Yamato-Security/hayabusa/blob/change-license/README-Japanese.md#%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9

**Comment by fukusuket** [comment]
FYI:
Maybe after this PR, We will create a PR to change the license in the Takajo project as well?
- https://github.com/Yamato-Security/takajo/blob/main/LICENSE.txt
- https://github.com/Yamato-Security/takajo/blob/main/takajo.nimble#L6
- https://github.com/Yamato-Security/takajo/tree/main?tab=readme-ov-file#license
- https://github.com/Yamato-Security/takajo/blob/main/README-Japanese.md#%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! I forgot about the readme. Yes, we should probably change Takajo to AGPL as well. I'll add that later

**Review by fukusuket — APPROVED** [review]
@YamatoSecurity 
Thank you for updating README :) LGTM!!🚀

**Pull request merged**
