### PR TITLE
fixed UI in Search Command

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Changed the help menu to output when the condition is not satisfied by the search command
- Changed the search command to output the result in red color when there are zero detections.

### CODE REVIEW

**Review by YamatoSecurity — APPROVED** [review]
LGTM. The help menu shows like before and "No matches" is is in red.
Thank you!
@itiB Can you check?

**Comment by itiB** [comment]
## when the keyword or regex option is not used, the Help menu is displayed

```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx
~~~

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]
```

## ignore-case option can only be used with the keyword option.

```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx -r ".*" -i
~~~

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]
```

```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx -k ".*" -i
~~~

Searching...

Start time: 2023/04/16 11:56

Total event log files: 583
Total file size: 137.1 M
```
Looks good at these points.

## if nothing is found, a red message will be displayed.

```
❯ ./target/debug/hayabusa search -f ../hayabusa-sample-evtx/YamatoSecurity/Sysmon/Sysmon-27-BlockExeWrite_AbusingCertutil.evtx -k "hogehogehogehooge" -i
~~~

No matches found.

Elapsed time: 00:00:20.675
```

**Comment by itiB** [comment]
@YamatoSecurity 
The Help menu does not mention that the regex option and ignore-case option cannot be used together, so some users might be confused about why they are getting the help menu.
How abotu to add a note about this limitation in the help menu?

```
❯ ./target/debug/hayabusa search -d ../hayabusa-sample-evtx -r ".*" -i
~~~

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]
```

**Comment by YamatoSecurity** [comment]
@itiB Thank you! I didn't notice those `conflict_with` lines were deleted. I added them back.
What about now?

**Comment by hitenkoku** [comment]
@YamatoSecurity  @itiB I shared results in https://github.com/Yamato-Security/hayabusa/pull/1011/commits/0e1c79db42b7d9587014e7d56409ec7ed36dd9ab

- when the keyword or regex option is not used, the Help menu is displayed
```
PS >./1011-2.exe search -d ..\hayabusa-sample-evtx\

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]

Display Settings:
      --no-color  Disable color output
  -q, --quiet     Quiet mode: do not display the launch banner
  -v, --verbose   Output verbose information

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Filtering:
  -F, --filter <FILTER>      Filter by specific field(s)
  -i, --ignore-case          Case-insensitive keyword search
  -k, --keywords <KEYWORDS>  Search by keyword(s)
  -r, --regex <REGEX>        Search by regular expression

Output:
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)

General Options:
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
```

- ignore-case option can only be used with the keyword option.


```
PS >./1011-2.exe search -d ..\hayabusa-sample-evtx\ -r ".*Mimikatz." -i
error: the argument '--regex <REGEX>' cannot be used with '--ignore-case'

Usage: 1011-2.exe search --directory <DIR> --regex <REGEX>

```


- regex and keyword conflict output

```
>./1011-2.exe search -d ..\hayabusa-sample-evtx\ -r ".*Mimikatz." -k "test"
error: the argument '--regex <REGEX>' cannot be used with '--keywords <KEYWORDS>'

Usage: 1011-2.exe search --directory <DIR> --regex <REGEX>

```

**Comment by hitenkoku** [comment]
@YamatoSecurity @itiB 

If `conflicts_with` is used, it is processed by clap, so it is not possible to output a help statement.

Therefore, https://github.com/Yamato-Security/hayabusa/pull/1011/commits/12abdf340f8509c5a65a3dd5d71128defd89c649 removes conflicts_with The following is an example of the use of conflicts_with in a clap

If you want to include help text as well as warning text, it is possible.
It is not possible to put the warning text in the middle of the help text, but we can put the warning text even in the back.

**Comment by hitenkoku** [comment]
Changed to draft to prevent merge in wrong order

**Review by itiB — APPROVED** [review]
LGTM!!
I checked these cases.
All most works good.

<details><summary>TestPattern</summary>
<p>

```
❯ ./target/debug/hayabusa search
Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]

Display Settings:
~~~
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -k "hoge"
~~~
Searching...
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -k "hoge" -i
~~~
Searching...
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -k "hoge" -q
Searching...
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -r "hogehoge"
~~
Searching...
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -r "hogehoge" -i
error: the argument '--regex <REGEX>' cannot be used with '--ignore-case'

Usage: hayabusa search --file <FILE> --regex <REGEX>
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -r "hoge" -k "hoge"
error: the argument '--regex <REGEX>' cannot be used with '--keywords <KEYWORDS>'

Usage: hayabusa search --file <FILE> --regex <REGEX>
```

```
❯ ./target/debug/hayabusa search -f sample.evtx -k "hogehooge" -r "hogehoge" -i
error: the argument '--keywords <KEYWORDS>' cannot be used with '--regex <REGEX>'

Usage: hayabusa search --file <FILE> --keywords <KEYWORDS> --ignore-case
```

```
❯ ./target/debug/hayabusa search -f
error: a value is required for '--file <FILE>' but none was supplied
```

```
❯ ./target/debug/hayabusa search -q
Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]
```

```
❯ ./target/debug/hayabusa search -f sample.evtx
~~~

Hayabusa v2.4.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)

Usage:
  hayabusa.exe search <INPUT> <--keywords "<KEYWORDS>" OR --regex "<REGEX>"> [OPTIONS]
```


</p>
</details>

**Pull request merged**
