### PR TITLE
feat: add support for Sigma Correlation Event count

### LINKED ISSUE #1337: Sigma correlations support: Event Count
@fukusuket Here is a (maybe) hard one for you. I'd like to start supporting sigma correlations starting with Event Count and Value Count types since we already have the logic for those with `| count`. We should probably start with `Event Count` as that is the easiest.

Both are explained here: https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md

Event Count sample:
```
title: Many failed logins to the same computer
id: 0e95725d-7320-415d-80f7-004da920fc11
correlation:
  type: event_count
  rules:
    - e87bd730-df45-4ae9-85de-6c75369c5d29 # Logon Failure (Wrong Password)
    - 8afa97ce-a217-4f7c-aced-3e320a57756d # Logon Failure (User Does Not Exist)
  group-by:
    - Computer
  timespan: 5m
  condition:
    gte: 3
```

This is example uses multiple rules but at first we can just support one rule if that is easier.
Or you could create a generic rule with a new ID and the following logic to test:
```
logsource:
    product: windows
    service: security
detection:
    selection:
        Channel: Security
        EventID: 4625
```
This just detects any failed logon.

I think this should be the same as the following `count` rule:
```
logsource:
    product: windows
    service: security
detection:
    selection:
        Channel: Security
        EventID: 4625
    condition: selection | count() by Computer >= 3 
    timeframe: 5m
```

If there a 3 or more failed logons to the **same** Computer, then there will be an alert.

Things to consider:
* There *may* be multiple rules...  If it is difficult to implement checking multiple conditions from multiple rules then we might want to just start off by supporting one rule
* Rules may be defined by `name` instead of `ID` so we need a way to look this up internally. Info: https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md#related-rules
* There may be multiple fields in `group-by`. I believe this means that, for example if `Computer` and `IpAddress` were defined in `group-by` then if the combination of the  **same** `ComputerName` **AND** the **same** `IpAddress` reaches 3 or more, then we should give an alert.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1337 

## Limitations of current implementation
The following points are not supported because they require more time to implement. 
I will consider addressing them as separate PR depending on priority.
- https://github.com/Yamato-Security/hayabusa/issues/1342
- [Multiple yaml in one file](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md#failed-logins-followed-by-successful-login)
- Multiple `Condition`(e.g.  100 > count > 1)
- Recursive Correlation rule

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Correlation

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
I confirmed that there are no differences in the result files as follows
#### csv-timeline
```
% ./hayabusa-old csv-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o old.csv
% ./hayabusa-new csv-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o new.csv
% diff new.csv old.csv
%
```

#### json-timeline
```
% ./hayabusa-old json-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o old.json
% ./hayabusa-new json-timeline -d ../hayabusa-sample-evtx -w -D -u -n -q -C -o new.json
% diff new.json old.json
%
```
#### Integration-Test
https://github.com/Yamato-Security/hayabusa/actions/runs/9342831069

**Review by hitenkoku — APPROVED** [review]
LGTM

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
