### PR TITLE
organized options grouping

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- organized options grouping
  -  rename `Options` to `General Options` .
  - remove `Advanced` and put `-r, --rules` and `--target-file-ext` options in `General Options`.
- fixed output when typing `hayabusa.exe csv-timeline` or `hayabusa.exe json-timeline` in `hayabusa.exe help csv-timeline`( --no-color and -q, --quiet show up but they do not show up )

## Evidence

<details>
<summary> help csv-timeline </summary>

```
>./918.exe help csv-timeline
...
Usage:
  hayabusa.exe csv-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -H, --HTML-report <FILE>  Save Results Summary details to an HTML report (ex: results.html)
  -o, --output <FILE>       Save the timeline in CSV format (ex: results.csv)
  -p, --profile <PROFILE>   Specify output profile

General Options:
  -G, --GeoIP <MAXMIND-DB-DIR>           Add GeoIP (ASN, city, country) info to IP addresses
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -r, --rules <DIR/FILE>                 Specify a custom rule directory or file (default: ./rules)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information

Filtering:
  -E, --EID-filter               Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
      --enable-deprecated-rules  Enable rules marked as deprecated (no longer included by default)
  -n, --enable-noisy-rules       Enable rules marked as noisy (./rules/config/noisy_rules.txt)
  -e, --exact-level <LEVEL>      Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>  Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>        Minimum level for rules (default: informational)
      --timeline-end <DATE>      End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>    Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

Time Format:
      --European-time     Output timestamp in European time format (ex: 22-02-2022 22:00:00.123 +02:00)
      --ISO-8601          Output timestamp in ISO-8601 format (ex: 2022-02-22T10:10:10.1234567Z) (Always UTC)
      --RFC-2822          Output timestamp in RFC 2822 format (ex: Fri, 22 Feb 2022 22:00:00 -0600)
      --RFC-3339          Output timestamp in RFC 3339 format (ex: 2022-02-22 22:00:00.123456-06:00)
      --US-military-time  Output timestamp in US military time format (ex: 02-22-2022 22:00:00.123 -06:00)
      --US-time           Output timestamp in US time format (ex: 02-22-2022 10:00:00.123 PM -06:00)
  -U, --UTC               Output time in UTC format (default: local time)

Display Settings:
      --no-summary          Do not display Results Summary (slightly faster speed)
  -T, --visualize-timeline  Output event frequency timeline (terminal needs to support unicode)
```
</summary>
</details>

<details>
<summary> help json-timeline </summary>

```
>./918.exe help json-timeline
..
Usage:
  hayabusa.exe json-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -H, --HTML-report <FILE>  Save Results Summary details to an HTML report (ex: results.html)
  -L, --JSONL-output        Save the timeline in JSONL format (ex: -L -o results.jsonl)
  -o, --output <FILE>       Save the timeline in JSON format (ex: results.json)
  -p, --profile <PROFILE>   Specify output profile

General Options:
  -G, --GeoIP <MAXMIND-DB-DIR>           Add GeoIP (ASN, city, country) info to IP addresses
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -r, --rules <DIR/FILE>                 Specify a custom rule directory or file (default: ./rules)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information

Filtering:
  -E, --EID-filter               Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
      --enable-deprecated-rules  Enable rules marked as deprecated (no longer included by default)
  -n, --enable-noisy-rules       Enable rules marked as noisy (./rules/config/noisy_rules.txt)
  -e, --exact-level <LEVEL>      Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>  Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>        Minimum level for rules (default: informational)
      --timeline-end <DATE>      End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>    Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

Time Format:
      --European-time     Output timestamp in European time format (ex: 22-02-2022 22:00:00.123 +02:00)
      --ISO-8601          Output timestamp in ISO-8601 format (ex: 2022-02-22T10:10:10.1234567Z) (Always UTC)
      --RFC-2822          Output timestamp in RFC 2822 format (ex: Fri, 22 Feb 2022 22:00:00 -0600)
      --RFC-3339          Output timestamp in RFC 3339 format (ex: 2022-02-22 22:00:00.123456-06:00)
      --US-military-time  Output timestamp in US military time format (ex: 02-22-2022 22:00:00.123 -06:00)
      --US-time           Output timestamp in US time format (ex: 02-22-2022 10:00:00.123 PM -06:00)
  -U, --UTC               Output time in UTC format (default: local time)

Display Settings:
      --no-summary          Do not display Results Summary (slightly faster speed)
  -T, --visualize-timeline  Output event frequency timeline (terminal needs to support unicode)
```
</summary>
</details>

<details>
<summary> no option in csv-timeline </summary>

```
 >./918.exe csv-timeline

...
Usage:
  hayabusa.exe csv-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -H, --HTML-report <FILE>  Save Results Summary details to an HTML report (ex: results.html)
  -o, --output <FILE>       Save the timeline in CSV format (ex: results.csv)
  -p, --profile <PROFILE>   Specify output profile

General Options:
  -G, --GeoIP <MAXMIND-DB-DIR>           Add GeoIP (ASN, city, country) info to IP addresses
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -r, --rules <DIR/FILE>                 Specify a custom rule directory or file (default: ./rules)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information

Filtering:
  -E, --EID-filter               Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
      --enable-deprecated-rules  Enable rules marked as deprecated (no longer included by default)
  -n, --enable-noisy-rules       Enable rules marked as noisy (./rules/config/noisy_rules.txt)
  -e, --exact-level <LEVEL>      Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>  Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>        Minimum level for rules (default: informational)
      --timeline-end <DATE>      End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>    Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

Time Format:
      --European-time     Output timestamp in European time format (ex: 22-02-2022 22:00:00.123 +02:00)
      --ISO-8601          Output timestamp in ISO-8601 format (ex: 2022-02-22T10:10:10.1234567Z) (Always UTC)
      --RFC-2822          Output timestamp in RFC 2822 format (ex: Fri, 22 Feb 2022 22:00:00 -0600)
      --RFC-3339          Output timestamp in RFC 3339 format (ex: 2022-02-22 22:00:00.123456-06:00)
      --US-military-time  Output timestamp in US military time format (ex: 02-22-2022 22:00:00.123 -06:00)
      --US-time           Output timestamp in US time format (ex: 02-22-2022 10:00:00.123 PM -06:00)
  -U, --UTC               Output time in UTC format (default: local time)

Display Settings:
      --no-summary          Do not display Results Summary (slightly faster speed)
  -T, --visualize-timeline  Output event frequency timeline (terminal needs to support unicode)

```
</summary>
</details>

<details>
<summary> no option in json-timeline </summary>

```
>./918.exe json-timeline

...
Usage:
  hayabusa.exe json-timeline <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -H, --HTML-report <FILE>  Save Results Summary details to an HTML report (ex: results.html)
  -L, --JSONL-output        Save the timeline in JSONL format (ex: -L -o results.jsonl)
  -o, --output <FILE>       Save the timeline in JSON format (ex: results.json)
  -p, --profile <PROFILE>   Specify output profile

General Options:
  -G, --GeoIP <MAXMIND-DB-DIR>           Add GeoIP (ASN, city, country) info to IP addresses
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -r, --rules <DIR/FILE>                 Specify a custom rule directory or file (default: ./rules)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information

Filtering:
  -E, --EID-filter               Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
      --enable-deprecated-rules  Enable rules marked as deprecated (no longer included by default)
  -n, --enable-noisy-rules       Enable rules marked as noisy (./rules/config/noisy_rules.txt)
  -e, --exact-level <LEVEL>      Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>  Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>        Minimum level for rules (default: informational)
      --timeline-end <DATE>      End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>    Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")

Time Format:
      --European-time     Output timestamp in European time format (ex: 22-02-2022 22:00:00.123 +02:00)
      --ISO-8601          Output timestamp in ISO-8601 format (ex: 2022-02-22T10:10:10.1234567Z) (Always UTC)
      --RFC-2822          Output timestamp in RFC 2822 format (ex: Fri, 22 Feb 2022 22:00:00 -0600)
      --RFC-3339          Output timestamp in RFC 3339 format (ex: 2022-02-22 22:00:00.123456-06:00)
      --US-military-time  Output timestamp in US military time format (ex: 02-22-2022 22:00:00.123 -06:00)
      --US-time           Output timestamp in US time format (ex: 02-22-2022 10:00:00.123 PM -06:00)
  -U, --UTC               Output time in UTC format (default: local time)

Display Settings:
      --no-summary          Do not display Results Summary (slightly faster speed)
  -T, --visualize-timeline  Output event frequency timeline (terminal needs to support unicode)
```
</summary>
</details>

### CODE REVIEW

**Comment by hitenkoku** [comment]
Additional Evidence

<details>
<summary> help metrics </summary>

```
>./918.exe help metrics
...
Usage:
  hayabusa.exe metrics <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -o, --output <FILE>  Save the Metrics in CSV format (ex: metrics.csv)

General Options:
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information
```
</summary>
</details>

<details>
<summary> help logon-summary </summary>

```
>./918.exe help logon-summary
...
Usage:
  hayabusa.exe logon-summary <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -o, --output <FILE>  Save the Logon summary in CSV format (ex: logon-summary.csv)

General Options:
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information
```
</summary>
</details>

<details>
<summary> help pivot-keywords-list </summary>

```
>./918.exe help pivot-keywords-list
...
Usage:
  hayabusa.exe pivot-keywords-list <INPUT> [OPTIONS]

Input:
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder

Output:
  -o, --output <FILENAMES-BASE>  Save pivot words to separate files (ex: PivotKeywords)

General Options:
  -J, --JSON-input                       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
      --no-color                         Disable color output
  -q, --quiet                            Quiet mode: do not display the launch banner
  -Q, --quiet-errors                     Quiet errors mode: do not save error logs
  -c, --rules-config <DIR>               Specify custom rule config directory (default: ./rules/config)
  -t, --threads <NUMBER>                 Number of threads (default: optimal number for performance)
      --target-file-ext <EVTX_FILE_EXT>  Specify additional file extensions (ex: evtx_data) (ex: evtx1,evtx2)
  -v, --verbose                          Output verbose information

Filtering:
  -E, --EID-filter               Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
      --enable-deprecated-rules  Enable rules marked as deprecated (no longer included by default)
  -n, --enable-noisy-rules       Enable rules marked as noisy (./rules/config/noisy_rules.txt)
  -e, --exact-level <LEVEL>      Scan for only specific levels (informational, low, medium, high, critical)
      --exclude-status <STATUS>  Ignore rules according to status (ex: experimental) (ex: stable,test)
  -m, --min-level <LEVEL>        Minimum level for rules (default: informational)
      --timeline-end <DATE>      End time of the event logs to load (ex: "2022-02-22 23:59:59 +09:00")
      --timeline-start <DATE>    Start time of the event logs to load (ex: "2020-02-22 00:00:00 +09:00")
```
</summary>
</details>

<details>
<summary> help update-rules </summary>

```
>./918.exe help update-rules
...
Usage:
  918.exe update-rules [OPTIONS]

General Options:
      --no-color          Disable color output
  -q, --quiet             Quiet mode: do not display the launch banner
  -r, --rules <DIR/FILE>  Specify a custom rule directory or file (default: ./rules)
</summary>
</details>

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you!
1. Can you move `-J, --JSON-input` from `General Options` to `Input`? (以前にGeneral Optionsにしたいと言ったと思いますが、Inputの方が良さそうです。申し訳ありません。）
2. Can you move `-G, --GeoIP` from `General Options` to `Output`?
3. Can you move `--no-color`, `-q, quiet` and `-v, --verbose` from `General Options` to `Display Settings`?

**Review by fukusuket — APPROVED** [review]
LGTM ! 🚀 The new order is very easy to understand :)

**Comment by hitenkoku** [comment]
Thank you for your review.

The following comments have been corrected. Thank you for your confirmation.

> 
> 1. Can you move `-J, --JSON-input` from `General Options` to `Input`? (以前にGeneral Optionsにしたいと言ったと思いますが、Inputの方が良さそうです。申し訳ありません。）
> 2. Can you move `-G, --GeoIP` from `General Options` to `Output`?
> 3. Can you move `--no-color`, `-q, quiet` and `-v, --verbose` from `General Options` to `Display Settings`?

**Comment by YamatoSecurity** [comment]
@hitenkoku 
Thank you!
For `csv-timeline` and `json-timeline`, can you move `-J, --JSON-input` alphabetically?
before:
```  
-J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
```

after:
```  

  -d, --directory <DIR>  Directory of multiple .evtx files
  -f, --file <FILE>      File path to one .evtx file
-J, --JSON-input       Scan JSON formatted logs instead of .evtx (.json or .jsonl)
  -l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
```

In `json-timeline`, `-G, --GeoIP` is still under `General Options`. Can you move it to `Output` like in `csv-timeline`?

**Comment by YamatoSecurity** [comment]
@hitenkoku 
Sorry, one last thing. Can you organize the groups for `csv-timeline` and `json-timeline` alphabetically after Input and Output?

Ex:
```
Usage
Input
Output
Display Settings
Filtering
General Options
Time Format
```

**Comment by hitenkoku** [comment]
@YamatoSecurity I fixed the following comments in  https://github.com/Yamato-Security/hayabusa/pull/922/commits/c75f6ebbc75ac89aed280ddd704cdd70525d0956

Would you check it?

> @hitenkoku Sorry, one last thing. Can you organize the groups for `csv-timeline` and `json-timeline` alphabetically after Input and Output?
> 
> Ex:
> 
> ```
> Usage
> Input
> Output
> Display Settings
> Filtering
> General Options
> Time Format
> ```

**Review by YamatoSecurity — APPROVED** [review]
LGTM!
I just changed the order of a few more things.

**Comment by hitenkoku** [comment]
There was an omission in the correction. Our apologies.
Thank you for your response. I think the information you have provided is correct.

LGTM.

**Pull request merged**
