### PR TITLE
feat: embedded config files to binary #1370

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- embedded config files in binary

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
I confirmed csv result has no diff between before/after :)
But the progress bar is output twice as follows only when run without config directory🤔 Could you please confirm this?🙏
```
% ./hayabusa-new csv-timeline -d ../hayabusa-sample-evtx -o new.csv -D -n -u -w -q -C
Start time: 2024/07/15 19:06

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.

Excluded rules: 20
Noisy rules: 12

Deprecated rules: 209 (4.72%)
Experimental rules: 566 (12.78%)
Stable rules: 253 (5.71%)
Test rules: 3,355 (75.77%)
Unsupported rules: 45 (1.02%)

Hayabusa rules: 179
Sigma rules: 4,249
Total detection rules: 4,428

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 575
Detection rules enabled after channel filter: 4,355

Output profile: standard

Scanning in progress. Please wait.

[00:00:00] 0 / 575 ⠁ [                                        ] 0%

[00:00:05] 575 / 575   [========================================] 100%

Scanning finished. Please wait while the results are being saved.
```

**Comment by hitenkoku** [comment]
@fukusuket Thank you for your review.
I checking your point out problem.

**Comment by hitenkoku** [comment]
@fukusuket  Sorry for late fix.

I fixed follwoing problem in
https://github.com/Yamato-Security/hayabusa/pull/1385/commits/62e14f7529121687a664fac6a784bc22883f1a8a .

Could you review it?

> @hitenkoku I confirmed csv result has no diff between before/after :) But the progress bar is output twice as follows only when run without config directory🤔 Could you please confirm this?🙏 (When there is a config directory, the progress bar is printed only once)
>

**Review by fukusuket — APPROVED** [review]
@hitenkoku 
Thank you so much for fix! I confirmed https://github.com/Yamato-Security/hayabusa/pull/1385#pullrequestreview-2177335169 is fixed! LGTM!!🚀

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks for this. I have confirmed that if I rename `config` to `config2` it still works. However, Hayabusa does not read the config files in the `config` directory by default so users cannot change the config files unless they recompile the binary. This is inconvenient for those who want to customize color, profiles, etc...
And it also breaks the `set-default-profile` command. Ex: `./target/release/hayabusa set-default-profile -p super-verbose`
Event if the default profile is changed in `default_profile.yaml`, Hayabusa will read from the embedded file which does not change.
Can you change it so that Hayabusa only reads the embedded file if the `config` directory does not exist?

**Comment by hitenkoku** [comment]
@YamatoSecurity  Fixed follwing problem. Please recheck it.

> @hitenkoku Thanks for this. I have confirmed that if I rename `config` to `config2` it still works. However, Hayabusa does not read the config files in the `config` directory by default so users cannot change the config files unless they recompile the binary. This is inconvenient for those who want to customize color, profiles, etc... And it also breaks the `set-default-profile` command. Ex: `./target/release/hayabusa set-default-profile -p super-verbose` Event if the default profile is changed in `default_profile.yaml`, Hayabusa will read from the embedded file which does not change. Can you change it so that Hayabusa only reads the embedded file if the `config` directory does not exist?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks! When i run the following it updates the config file correctly but it displays an error:
```
./target/release/hayabusa set-default-profile -p minimal
Successfully updated the default profile.

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Start time: 2024/07/28 16:13

Default profile cannot be set due to the absence of a config folder. Please check config folder.
```

Can you remove the `Default profile cannot be set due to the absence of a config folder. Please check config folder.` error message when there is a success?

Also, when I change the `level_color.txt` settings to the same colors:
```
level,colorcode
critical,00ff00
high,00ff00
medium,00ff00
low,00ff00
```
just to test, the colors do not change anymore. Can you check this?

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your review. I following problems. Please recheck it.

> @hitenkoku Thanks! When i run the following it updates the config file correctly but it displays an error:
> 
> ```
> ./target/release/hayabusa set-default-profile -p minimal
> Successfully updated the default profile.
> 
> ┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
> ┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
> ┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
> ┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
> ┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
> ┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
>    by Yamato Security
> 
> Start time: 2024/07/28 16:13
> 
> Default profile cannot be set due to the absence of a config folder. Please check config folder.
> ```
> 
> Can you remove the `Default profile cannot be set due to the absence of a config folder. Please check config folder.` error message when there is a success?
> 
> Also, when I change the `level_color.txt` settings to the same colors:
> 
> ```
> level,colorcode
> critical,00ff00
> high,00ff00
> medium,00ff00
> low,00ff00
> ```
> 
> just to test, the colors do not change anymore. Can you check this?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you!
I checked that the error message now does not get displayed: 
```./target/release/hayabusa set-default-profile -p minimal
Successfully updated the default profile.

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Start time: 2024/07/29 19:57
```

However, it is easy to miss the message as it gets displayed before the logo. Can you change it to:
```
./target/release/hayabusa set-default-profile -p minimal

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Successfully updated the default profile.
```

or just
```
./target/release/hayabusa set-default-profile -p minimal

Successfully updated the default profile.

```

I changed the colors for the levels in `level_color.txt` to
```
level,colorcode
critical,00ff00
high,00ff00
medium,00ff00
low,00ff00
```
but the colors still do not change. Can you check this?

**Comment by YamatoSecurity** [comment]
The `mitre_tactics.txt` settings also do not seem to be read from the `config` file, just the embedded config file.
To test, I changed `attack.credential_access,CredAccess,08. Credential Access` to `attack.credential_access,CredHogeAccess,08. Credential Access` and searched for `CredHogeAccess` after running Hayabusa with the `super-verbose` file but it still shows up as `CredAccess`.

Could you please check this as well.

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.

 I fixed following point out in https://github.com/Yamato-Security/hayabusa/pull/1385/commits/c12a06ac321ad145ea6c4e9a387ef489a61e8095.

> The `mitre_tactics.txt` settings also do not seem to be read from the `config` file, just the embedded config file. To test, I changed `attack.credential_access,CredAccess,08. Credential Access` to `attack.credential_access,CredHogeAccess,08. Credential Access` and searched for `CredHogeAccess` after running Hayabusa with the `super-verbose` file but it still shows up as `CredAccess`.
> 
> Could you please check this as well.

I fixed following point out in https://github.com/Yamato-Security/hayabusa/pull/1385/commits/562c1172aa7e1b8733125aebb18353a0339d191c.

> @hitenkoku Thank you! I checked that the error message now does not get displayed:
> 
> ```
> Successfully updated the default profile.
> 
> ┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
> ┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
> ┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
> ┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
> ┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
> ┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
>    by Yamato Security
> 
> Start time: 2024/07/29 19:57
> ```
> 
> However, it is easy to miss the message as it gets displayed before the logo. Can you change it to:
> 
> ```
> ./target/release/hayabusa set-default-profile -p minimal
> 
> ┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
> ┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
> ┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
> ┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
> ┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
> ┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
>    by Yamato Security
> 
> Successfully updated the default profile.
> ```
> 
> or just
> 
> ```
> ./target/release/hayabusa set-default-profile -p minimal
> 
> Successfully updated the default profile.
> ```
> 

I fixed following your point out in https://github.com/Yamato-Security/hayabusa/pull/1385/commits/dbd04172b4f32dbad3447a8d3e4458aea1f9f7ce.

> I changed the colors for the levels in `level_color.txt` to
> 
> ```
> level,colorcode
> critical,00ff00
> high,00ff00
> medium,00ff00
> low,00ff00
> ```
> 
> but the colors still do not change. Can you check this?

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku I checked that everything works on my environment. Thanks so much!

**Pull request merged**
