### PR TITLE
added new feature `-P, --proven-rules`

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- Added `-P, --proven-rules` option in `csv-timeline` and `json-timeline` command. To scan only target rule ids that there are detection rules for defined in `./rules/config/proven_rules.txt`.

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

- this PR(without -P)

```
> ./1115.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1115-no-pr.csv --debug
...

Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 31
Noisy rules: 12 (Disabled)

Deprecated rules: 165 (4.50%) (Disabled)
Experimental rules: 1973 (53.77%)
Stable rules: 229 (6.24%)
Test rules: 1467 (39.98%)
Unsupported rules: 45 (1.23%) (Disabled)

Hayabusa rules: 159
Sigma rules: 3510
Total enabled detection rules: 3669

Output profile: standard

...

Saved file: 1115-no-pr.csv (32.0 MB)

Elapsed time: 00:00:08.081
Rule Parse Processing Time: 00:00:01.021
Analysis Processing Time: 00:00:06.623
Output Processing Time: 00:00:00.436

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB             

 committed:   819.2 MiB     1.3 GiB   869.7 MiB   498.0 MiB             

     reset:     0
    purged:   403.8 MiB
   touched:    64.2 KiB     1.1 MiB     3.5 GiB    -3.5 GiB             
             ok
  segments:    16          19           9          10                   
             not all freed!
-abandoned:     0           0           0           0                   
             ok
   -cached:     0           0           0           0                   
             ok
     pages:     0           0          33.1 Ki    -33.1 Ki              
             ok
-abandoned:     0           0           0           0                   
             ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     6.9 Ki
    resets:     0
    purges:   300
   threads:    32          32           0          32                   
             not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     8.087 s
   process: user: 26.937 s, system: 0.453 s, faults: 260103, rss: 687.4 MiB, commit: 798.3 MiB
```

- this PR(with -P)

```
```
> ./1115.exe csv-timeline -d ..\hayabusa-sample-evtx\ -o 1115-pr.csv --debug -P   
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 2540
Noisy rules: 12 (Disabled)

Deprecated rules: 80 (6.28%) (Disabled)
Experimental rules: 605 (47.53%)
Stable rules: 153 (12.02%)
Test rules: 515 (40.46%)
Unsupported rules: 17 (1.34%) (Disabled)

Hayabusa rules: 139
Sigma rules: 1134
Total enabled detection rules: 1273

Output profile: standard

...

Results Summary:
Events with hits / Total events: 19,603 / 47,472 (Data reduction: 27,869 events (58.71%))

Total | Unique detections: 32,130 | 557
Total | Unique critical detections: 55 (0.17%) | 19 (3.41%)
Total | Unique high detections: 6,043 (18.81%) | 245 (43.99%)
Total | Unique medium detections: 1,891 (5.89%) | 183 (32.85%)
Total | Unique low detections: 6,002 (18.68%) | 56 (10.05%)
Total | Unique informational detections: 18,139 (56.46%) | 54 (9.69%)   

...

Saved file: 1115-pr.csv (32.0 MB)

Elapsed time: 00:00:05.325
Rule Parse Processing Time: 00:00:00.665
Analysis Processing Time: 00:00:04.254
Output Processing Time: 00:00:00.404

Memory usage stats:
heap stats:     peak       total       freed     current        unit       count
  reserved:     2.0 GiB     2.0 GiB     0           2.0 GiB             

 committed:   545.7 MiB     1.2 GiB   903.2 MiB   406.3 MiB             

     reset:     0
    purged:   501.7 MiB
   touched:    64.2 KiB     1.3 MiB     1.8 GiB    -1.8 GiB             
             ok
  segments:     9          22          15           7                   
             not all freed!
-abandoned:     0           0           0           0                   
             ok
   -cached:     0           0           0           0                   
             ok
     pages:     0           0          16.9 Ki    -16.9 Ki              
             ok
-abandoned:     0           0           0           0                   
             ok
 -extended:     0
 -noretire:     0
     mmaps:     0
   commits:     5.9 Ki
    resets:     0
    purges:   240
   threads:    32          32           0          32                   
             not all freed!
  searches:     0.0 avg
numa nodes:     1
   elapsed:     5.332 s
   process: user: 10.531 s, system: 0.468 s, faults: 183722, rss: 415.4 MiB, commit: 524.0 MiB
```

**Review by fukusuket — COMMENTED** [review]
@hitenkoku @YamatoSecurity 
I confirmed that the **default** `proven_rules.txt` has fewer detection rules to load :)

I have a question about the detection result **after changing** `proven_rules.txt`!
I expect that `only 1 rule will be detected` when only `1` rule is described in `proven_rules.txt` as follows,
```
hayabusa-2.6.0-all-platforms % cat ./rules/config/proven_rules.txt
002bdb95-0cf1-46a6-9e08-d38c128a6127
```

However, when comparing the detection results for `hayabusa-sample-evtx`, there is no difference from main as shown below.(`no-p.csv` == **without -P** option, `with-p.csv` == **with -P** option)
```
hayabusa-2.6.0-all-platforms % ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -o no-p.csv -q -C
...
hayabusa-2.6.0-all-platforms % ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -o with-p.csv -q -C -P
...
hayabusa-2.6.0-all-platforms % diff no-p.csv with-p.csv
hayabusa-2.6.0-all-platforms %
```
Is the above expected behavior?
I would appreciate it if you could check it🙏

**Comment by YamatoSecurity** [comment]
@fukusuket
The number of rules in `proven_rules.txt` is less than the number of rules available. I made this list by scanning all of the evtx files I have available. If you or @hitenkoku have proven detection rules that are not in this list, please add the rule ID to this file.
If, for example, you only put one rule `002bdb95-0cf1-46a6-9e08-d38c128a6127` inside this file and use the `-P` option, then hayabusa should only find detections with that rule ID. (Usually just one rule, but might be 2 if it is a `process_creation` rule that is actually two different yml files)
So it is indeed strange that the unique detections would decrease so much.
In all of our tests, the detections should be the same but I want to decrease the amount of loaded rules which will decrease the processing time and memory usage.

**Comment by hitenkoku** [comment]
The `proven_rules.txt` file is the latest version from the hayabusa-rules repository and has not been modified.

I will check how it looks like when only one element is used.

**Comment by hitenkoku** [comment]
We are very sorry. There was an error in the condition when filtering the rules at https://github.com/Yamato-Security/hayabusa/pull/1120/commits/ea444a8b87a26f1abaa8c37d5686bcb5342180e4 Corrected.

```
> cat .\rules\config\proven_rules.txt
002bdb95-0cf1-46a6-9e08-d38c128a6127
>  ./1115.exe csv-timeline -d ../hayabusa-sample-evtx -o with-p.csv -q -C -P
...
Total event log files: 584
Total file size: 137.1 MB

Loading detections rules. Please wait.

Excluded rules: 3909
Noisy rules: 12 (Disabled)

Experimental rules: 1 (100.00%)

Sigma rules: 1
Total enabled detection rules: 1

Output profile: standard

Scanning in progress. Please wait.

584 / 584 [========================================================] 100.00 %

Scanning finished. Please wait while the results are being saved.


Results Summary:
Events with hits / Total events: 0 / 47,472 (Data reduction: 47,472 events (100.00%))

Total | Unique detections: 0 | 0
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 0 (0.00%) | 0 (0.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: n/a

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: n/a
informational: n/a

...
Saved file: with-p.csv (0 B)

Elapsed time: 00:00:01.488
```

**Review by fukusuket — APPROVED** [review]
@hitenkoku @YamatoSecurity 
Thank you so much for a quick fix :) 
I confirmed that only `proven_rules.txt` loads the rules! LGTM🚀

Although It the issue on the hayabusa_rule(`proven_rules.txt`) side, when I checked the diff, it was as follows.
```
hayabusa-2.6.0-all-platforms % cat old.csv | awk -F"," '{print $5, $7}' | sort | uniq -c > old-rule-count.csv
hayabusa-2.6.0-all-platforms % cat fix.csv | awk -F"," '{print $5, $7}' | sort | uniq -c > fix-rule-count.csv
hayabusa-2.6.0-all-platforms % diff old-rule-count.csv fix-rule-count.csv
3d2
<    1 "crit" "Audit CVE Event"
291c290
<  243 "info" "Net Conn"
---
>  151 "info" "Net Conn"
302d300
<    2 "info" "RDP Denied"
462d459
<    3 "med" "Potential RDP Session Hijacking Activity"
```
Based on the above diff results, I think we should add the following to `proven_rules.txt`, what do you think?
- ["crit" "Audit CVE Event"](https://github.com/Yamato-Security/hayabusa-rules/blob/8ae4f72334b4a85f543fefa084ce621ee39a2caf/sigma/builtin/application/microsoft-windows_audit_cve/win_audit_cve.yml#L2)
- ["info" "Net Conn"](https://github.com/Yamato-Security/hayabusa-rules/blob/8ae4f72334b4a85f543fefa084ce621ee39a2caf/hayabusa/builtin/Security/ObjectAccess/FilteringPlatformConnection/Sec_5156_Info_NetConn.yml#L8)
- ["info" "Net Conn"](https://github.com/Yamato-Security/hayabusa-rules/blob/8ae4f72334b4a85f543fefa084ce621ee39a2caf/hayabusa/sysmon/Sysmon_3_Info_NetConn.yml#L8)
- ["info" "RDP Denied"](https://github.com/Yamato-Security/hayabusa-rules/blob/8ae4f72334b4a85f543fefa084ce621ee39a2caf/hayabusa/builtin/Security/System/OtherSystemEvents/Sec_4825_Low_RDP-Denied.yml#L8)
- ["med" "Potential RDP Session Hijacking Activity"](https://github.com/Yamato-Security/hayabusa-rules/blob/8ae4f72334b4a85f543fefa084ce621ee39a2caf/sigma/builtin/process_creation/proc_creation_win_tscon_rdp_session_hijacking.yml#L2)

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku Thank you for the update! I confirmed that it is working well for me too.
@fukusuket Thank you for checking. I am currently in the process of rechecking the rules to enable. I will be sure to add the rules that you mentioned. I'll submit a PR to hayabusa-rules later to fix this. I think we can merge this for now.

**Comment by hitenkoku** [comment]
@YamatoSecurity @fukusuket  Thanks for your review. I will merge it.

**Pull request merged**
