### PR TITLE
removed new line characters in search output

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- removed newline characters in search command output

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Comment by hitenkoku** [comment]
## Evidence

```
❯  ./1253.exe  search -d ../hayabusa-sample-evtx -r ".*" -F EventID:"5145"

...

2022-02-16 19:37:20.451 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988531 · Network share object checked for client access · AccessList: %%1538 %%1541 %%4416 %%4417 %%4418 %%4419 %%4420 %%4423 %%4424 ¦ AccessMask: 0x12019f ¦ AccessReason: - ¦ IpAddress: 172.16.66.25 ¦ IpPort: 50251 ¦ ObjectType: File ¦ RelativeTargetName: winreg ¦ ShareLocalPath:  ¦ ShareName: \\*\IPC$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567515 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.508 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988532 · Network share object checked for client access · AccessList: %%1538 %%1541 %%4416 %%4417 %%4418 %%4419 %%4420 %%4423 %%4424 ¦ AccessMask: 0x12019f ¦ AccessReason: - ¦ IpAddress: 172.16.66.25 ¦ IpPort: 50251 ¦ ObjectType: File ¦ RelativeTargetName: winreg ¦ ShareLocalPath:  ¦ ShareName: \\*\IPC$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567515 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.534 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988537 · Network share object checked for client access · AccessList: %%1538 %%1541 %%4417 %%4418 %%4420 %%4423 %%4424 ¦ AccessMask: 0x120196 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSAM ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.534 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988538 · Network share object checked for client access · AccessList: %%4417 ¦ AccessMask: 0x2 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSAM ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.550 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988539 · Network share object checked for client access · AccessList: %%1538 %%1541 %%4417 %%4418 %%4420 %%4423 %%4424 ¦ AccessMask: 0x120196 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSYSTEM ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.550 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988540 · Network share object checked for client access · AccessList: %%4417 ¦ AccessMask: 0x2 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSYSTEM ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.934 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988542 · Network share object checked for client access · AccessList: %%4417 ¦ AccessMask: 0x2 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSECURITY ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx
2022-02-16 19:37:20.934 +09:00 · 01566s-win16-ir.threebeesco.com · Sec · 5145 · 2988541 · Network share object checked for client access · AccessList: %%1538 %%1541 %%4417 %%4418 %%4420 %%4423 %%4424 ¦ AccessMask: 0x120196 ¦ AccessReason: - ¦ IpAddress: 172.16.66.36 ¦ IpPort: 64224 ¦ ObjectType: File ¦ RelativeTargetName: Users\PSECURITY ¦ ShareLocalPath: \??\C:\ ¦ ShareName: \\*\C$ ¦ SubjectDomainName: 3B ¦ SubjectLogonId: 0x567758 ¦ SubjectUserName: samir ¦ SubjectUserSid: S-1-5-21-308926384-506822093-3341789130-220106 · ../hayabusa-sample-evtx\EVTX-ATTACK-SAMPLES\Credential Access\remote_sam_registry_access_via_backup_operator_priv.evtx


Total findings: 3059


Elapsed time: 00:00:13.423

```

**Review by YamatoSecurity — APPROVED** [review]
LGTM! Thank you!

**Review by fukusuket — APPROVED** [review]
I confirmed -k -r both option works :) LGTM!!🚀

**Comment by hitenkoku** [comment]
Thanks for review!
I will merge it.

**Pull request merged**
