### PR TITLE
add mitre tactics info to html report

### PR DESCRIPTION
**Pull request by hitenkoku**
## What Changed

- add mitre tactics info to html report

I would appreciate it if you could review when you have time.

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@hitenkoku 
I confirmed that the miter tactics are output as shown below :)
I have a question! MITRE tactics are in descending order, is this the expected behavior?
(If it works as expected, it's LGTM!!🚀)

スクリーンショット 2023-12-19 8 38 27

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you for checking. Yes, it would be better if the tactics order was sorted from top to bottom.

**Comment by hitenkoku** [comment]
@fukusuket @YamatoSecurity 
Thanks for your comment.

I modified code for following comment in https://github.com/Yamato-Security/hayabusa/pull/1234/commits/8f18f7ede6d8d26f9819ea1d3419ec1b2d9884bf.

Could you check it?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I updated the message:
tactics

Can you make it into a bullet point (・) like the other items?
Also, it would be nice to add a new line between the sentences and after as well.

**Review by fukusuket — APPROVED** [review]
Thank you so much for quick fix :) LGTM!!🚀

**Comment by YamatoSecurity** [comment]
I changed the red color to gray as red usually signifies some high alert, etc.. so I want to make it more neutral.

**Review by YamatoSecurity — APPROVED** [review]
@hitenkoku LGTM! Thanks so much!

**Pull request merged**
