### PR TITLE
fix: output agg result string when `all-field-info` profile

### LINKED ISSUE #1450: Field information is not outputted when the profile is `all-field-info`
@fukusuket Sorry for the many issues! I noticed there is a bug in both the correlation rules and the old `count` aggregation rules.
When using the `all-field-info` and `all-field-info-verbose` profiles which use the original field names, the field information does not get outputted.

Example:
```
./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml
```
gives the output:
```
2016-09-20 01:50:06.513 +09:00 · PW Guessing · med · DESKTOP-M5SN04R · Sec · 4625 · - · Count: 3558 ¦ TargetUserName: Administrator ¦ TargetDomainName: . ¦ IpAddress: 192.168.198.149 ¦ LogonType: 3 ¦ ProcessName: - ¦ LogonProcessName: NtLmSsp · -
```

However,
```
./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml -p all-field-info
```

gives:
```
2016-09-20 01:50:06.513 +09:00 · PW Guessing · med · DESKTOP-M5SN04R · Sec · 4625 · - · - · Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml · ../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx
```

Same thing happens when using the `../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt_Deprecated.yml` rule.

I would like to output the same regardless of what profile is being used. 
These are the original field names and no name conversion is done so they are expected when `all-field-info` profiles are used. 
In the future, I want to rename the fields like we do in `details`, etc.. but that will take some planning.
(See issue: https://github.com/Yamato-Security/hayabusa/issues/1445)

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Closed #1450 

#### Integration-Test
All commands completed successfully.
https://github.com/Yamato-Security/hayabusa/actions/runs/11325635098

#### CSV timeline and JSON timeline Diff(when rule/config folder exists) ... -p super-verbose
No difference(csv/json) from main branch's results as follows.
https://github.com/Yamato-Security/hayabusa/actions/runs/11325632998

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### csv-timeline(-p all-field-info)
```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -q -C -o new.csv -p all-field-info
% ./hayabusa-2.18.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -w -q -C -o old.csv -p all-field-info
% diff old.csv new.csv
32209,32211c32209,32211
< "2019-05-01 04:27:02.847 +09:00","PW Spray","med","DESKTOP-JR78RLP","Sec",4648,"-","-","Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx"
< "2019-05-01 04:32:03.525 +09:00","PW Spray","med","DESKTOP-JR78RLP","Sec",4648,"-","-","Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx"
< "2016-09-20 01:50:06.513 +09:00","PW Guessing","med","DESKTOP-M5SN04R","Sec",4625,"-","-","Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx"
---
> "2019-05-01 04:27:02.847 +09:00","PW Spray","med","DESKTOP-JR78RLP","Sec",4648,"-","Count:41 ¦ TargetUserName:tbennett/cfleener/econrad/kperryman/ssims/cdavis/dmashburn/cspizor/Administrator/sanson/lpesce/psmith/jorchilles/bhostetler/smisenar/jlake/jleytevidal/edygert/lschifano/celgee/zmathis/bking/dpendolino/mdouglas/cmoody/cragoso/gsalinas/bgreenwood/thessman/melliott/jwright/mtoussain/rbowes/drook/bgalbraith/baker/jkulikowski/eskoudis/sarmstrong/wstrzelec/ebooth ¦ IpAddress:172.16.144.128","Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx"
> "2019-05-01 04:32:03.525 +09:00","PW Spray","med","DESKTOP-JR78RLP","Sec",4648,"-","Count:14 ¦ TargetUserName:ssims/dmashburn/cspizor/jorchilles/smisenar/jlake/edygert/bking/mdouglas/cragoso/bgreenwood/drook/bgalbraith/baker ¦ IpAddress:172.16.144.128","Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx"
> "2016-09-20 01:50:06.513 +09:00","PW Guessing","med","DESKTOP-M5SN04R","Sec",4625,"-","Count:3558 ¦ IpAddress:192.168.198.149","Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt.yml","../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx"
```

**Comment by fukusuket** [comment]
### json-timeline(-p all-field-info)
```
% ./hayabusa json-timeline -d ../hayabusa-sample-evtx -w -q -C -o new.jsonl -L -p all-field-info
% ./hayabusa-2.18.0-mac-aarch64 json-timeline -d ../hayabusa-sample-evtx -w -q -C -o old.jsonl -L -p all-field-info
% diff old.jsonl new.jsonl
32208,32210c32208,32210
< { "Timestamp": "2019-05-01 04:27:02.847 +09:00","RuleTitle": "PW Spray","Level": "med","Computer": "DESKTOP-JR78RLP","Channel": "Sec","EventID": 4648,"RecordID": "-","RuleFile": "Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx" }
< { "Timestamp": "2019-05-01 04:32:03.525 +09:00","RuleTitle": "PW Spray","Level": "med","Computer": "DESKTOP-JR78RLP","Channel": "Sec","EventID": 4648,"RecordID": "-","RuleFile": "Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx" }
< { "Timestamp": "2016-09-20 01:50:06.513 +09:00","RuleTitle": "PW Guessing","Level": "med","Computer": "DESKTOP-M5SN04R","Channel": "Sec","EventID": 4625,"RecordID": "-","RuleFile": "Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx" }
\ No newline at end of file
---
> { "Timestamp": "2019-05-01 04:27:02.847 +09:00","RuleTitle": "PW Spray","Level": "med","Computer": "DESKTOP-JR78RLP","Channel": "Sec","EventID": 4648,"RecordID": "-","AllFieldInfo": {"Count": 41,"TargetUserName": "tbennett/cfleener/econrad/kperryman/ssims/cdavis/dmashburn/cspizor/Administrator/sanson/lpesce/psmith/jorchilles/bhostetler/smisenar/jlake/jleytevidal/edygert/lschifano/celgee/zmathis/bking/dpendolino/mdouglas/cmoody/cragoso/gsalinas/bgreenwood/thessman/melliott/jwright/mtoussain/rbowes/drook/bgalbraith/baker/jkulikowski/eskoudis/sarmstrong/wstrzelec/ebooth","IpAddress": "172.16.144.128"},"RuleFile": "Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx" }
> { "Timestamp": "2019-05-01 04:32:03.525 +09:00","RuleTitle": "PW Spray","Level": "med","Computer": "DESKTOP-JR78RLP","Channel": "Sec","EventID": 4648,"RecordID": "-","AllFieldInfo": {"Count": 14,"TargetUserName": "ssims/dmashburn/cspizor/jorchilles/smisenar/jlake/edygert/bking/mdouglas/cragoso/bgreenwood/drook/bgalbraith/baker","IpAddress": "172.16.144.128"},"RuleFile": "Sec_4648_Med_ExplicitLogon_PW-Spray_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx" }
> { "Timestamp": "2016-09-20 01:50:06.513 +09:00","RuleTitle": "PW Guessing","Level": "med","Computer": "DESKTOP-M5SN04R","Channel": "Sec","EventID": 4625,"RecordID": "-","AllFieldInfo": {"Count": 3558,"IpAddress": "192.168.198.149"},"RuleFile": "Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt.yml","EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx" }
\ No newline at end of file
```

**Comment by YamatoSecurity** [comment]
thanks so much! since it is adding `clone` usage I'm going to take some memory benchmarks just in case to see if there is any significant increase in memory usage.

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket I checked benchmarks and it was actually a few seconds faster and went from 2.6GB of memory to 2.5GB so LGTM! Thank you!

**Pull request merged**
